//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.11.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Approve Member</summary>
	[PublishedModel("approveMember")]
	public partial class ApproveMember : PublishedContentModel, IDesign, IMetadata
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.3")]
		public new const string ModelTypeAlias = "approveMember";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ApproveMember, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ApproveMember(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Approval failed: Displays when approval failed for any reason.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.3")]
		[ImplementPropertyType("approvalFailed")]
		public global::System.Web.IHtmlString ApprovalFailed => this.Value<global::System.Web.IHtmlString>("approvalFailed");

		///<summary>
		/// Approval successful: Displays when the member is approved. You can use {{NAME}} to insert the member's name.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.3")]
		[ImplementPropertyType("approvalSuccessful")]
		public global::System.Web.IHtmlString ApprovalSuccessful => this.Value<global::System.Web.IHtmlString>("approvalSuccessful");

		///<summary>
		/// Header photo: The photo which appears across the site header. Leave blank to use the one from the parent page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.3")]
		[ImplementPropertyType("headerPhoto")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent HeaderPhoto => global::Umbraco.Web.PublishedModels.Design.GetHeaderPhoto(this);

		///<summary>
		/// Custom stylesheet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.3")]
		[ImplementPropertyType("stylesheet")]
		public string Stylesheet => global::Umbraco.Web.PublishedModels.Design.GetStylesheet(this);

		///<summary>
		/// Description: A short summary of this page that may appear in search results
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.3")]
		[ImplementPropertyType("description")]
		public string Description => global::Umbraco.Web.PublishedModels.Metadata.GetDescription(this);

		///<summary>
		/// Don't show this in menus
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.3")]
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide => global::Umbraco.Web.PublishedModels.Metadata.GetUmbracoNaviHide(this);

		///<summary>
		/// URL segment: Sets the URL for this page. Defaults to the page title.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.11.3")]
		[ImplementPropertyType("umbracoUrlName")]
		public string UmbracoUrlName => global::Umbraco.Web.PublishedModels.Metadata.GetUmbracoUrlName(this);
	}
}
