//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.5.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Login Member</summary>
	[PublishedModel("loginMember")]
	public partial class LoginMember : PublishedContentModel, IMetadata
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		public new const string ModelTypeAlias = "loginMember";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LoginMember, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public LoginMember(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Logged in: Displays instead of the form when a member is logged in. You can use {{NAME}} to insert the member's name.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("loggedIn")]
		public global::System.Web.IHtmlString LoggedIn => this.Value<global::System.Web.IHtmlString>("loggedIn");

		///<summary>
		/// 'Login' button: Label for the form submit button.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("loginButton")]
		public string LoginButton => this.Value<string>("loginButton");

		///<summary>
		/// Login required: Displays above the form when a page requires the member to be logged in.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("loginRequired")]
		public global::System.Web.IHtmlString LoginRequired => this.Value<global::System.Web.IHtmlString>("loginRequired");

		///<summary>
		/// Migrated member accounts: Advice for members whose accounts have been migrated from the old website.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("migratedMemberAccounts")]
		public global::System.Web.IHtmlString MigratedMemberAccounts => this.Value<global::System.Web.IHtmlString>("migratedMemberAccounts");

		///<summary>
		/// Reset password: Displays below the Login button and prompts the member to reset their password if they are unable to login.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("resetPassword")]
		public global::System.Web.IHtmlString ResetPassword => this.Value<global::System.Web.IHtmlString>("resetPassword");

		///<summary>
		/// URL segment: Sets the URL for this page. Defaults to the page title.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("umbracoUrlName")]
		public string UmbracoUrlName => global::Umbraco.Web.PublishedModels.Metadata.GetUmbracoUrlName(this);
	}
}
