#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    
    #line 3 "..\..\Views\ClubActions.cshtml"
    using Stoolball.Security;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\ClubActions.cshtml"
    using Stoolball.Web.Clubs;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ClubActions.cshtml")]
    public partial class _Views_ClubActions_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<ClubViewModel>
    {
        public _Views_ClubActions_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("head", () => {

WriteLiteral("\r\n    <meta");

WriteLiteral(" name=\"robots\"");

WriteLiteral(" content=\"noindex,follow\"");

WriteLiteral(" />\r\n");

});

WriteLiteral("<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>Edit ");

            
            #line 8 "..\..\Views\ClubActions.cshtml"
        Write(Model.Club.ClubName);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");

            
            #line 10 "..\..\Views\ClubActions.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\ClubActions.cshtml"
     if (Model.IsAuthorized[AuthorizedAction.EditClub] || Model.IsAuthorized[AuthorizedAction.DeleteClub])
    {

            
            #line default
            #line hidden
WriteLiteral("        <dl>\r\n");

            
            #line 13 "..\..\Views\ClubActions.cshtml"
            
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\ClubActions.cshtml"
             if (Model.IsAuthorized[AuthorizedAction.EditClub])
            {

            
            #line default
            #line hidden
WriteLiteral("                <dt><a");

WriteAttribute("href", Tuple.Create(" href=\"", 487), Tuple.Create("\"", 525)
            
            #line 15 "..\..\Views\ClubActions.cshtml"
, Tuple.Create(Tuple.Create("", 494), Tuple.Create<System.Object, System.Int32>(Model.Club.ClubRoute
            
            #line default
            #line hidden
, 494), false)
, Tuple.Create(Tuple.Create("", 515), Tuple.Create("/edit/club", 515), true)
);

WriteLiteral(">Edit ");

            
            #line 15 "..\..\Views\ClubActions.cshtml"
                                                              Write(Model.Club.ClubName);

            
            #line default
            #line hidden
WriteLiteral("</a></dt>\r\n");

WriteLiteral("                <dd>Add or remove teams in the club.</dd>\r\n");

            
            #line 17 "..\..\Views\ClubActions.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 18 "..\..\Views\ClubActions.cshtml"
             if (Model.IsAuthorized[AuthorizedAction.DeleteClub])
            {

            
            #line default
            #line hidden
WriteLiteral("                <dt><a");

WriteAttribute("href", Tuple.Create(" href=\"", 741), Tuple.Create("\"", 776)
            
            #line 20 "..\..\Views\ClubActions.cshtml"
, Tuple.Create(Tuple.Create("", 748), Tuple.Create<System.Object, System.Int32>(Model.Club.ClubRoute
            
            #line default
            #line hidden
, 748), false)
, Tuple.Create(Tuple.Create("", 769), Tuple.Create("/delete", 769), true)
);

WriteLiteral(">Delete ");

            
            #line 20 "..\..\Views\ClubActions.cshtml"
                                                             Write(Model.Club.ClubName);

            
            #line default
            #line hidden
WriteLiteral("</a> ");

            
            #line 20 "..\..\Views\ClubActions.cshtml"
                                                                                      Write(Html.Partial("_AdminOnly"));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n");

WriteLiteral("                <dd>Teams in the club will no longer be connected. Combined match" +
" lists and statistics will not be available.</dd>\r\n");

            
            #line 22 "..\..\Views\ClubActions.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </dl>\r\n");

            
            #line 24 "..\..\Views\ClubActions.cshtml"
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\ClubActions.cshtml"
   Write(Html.Partial("_Login"));

            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\ClubActions.cshtml"
                               
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
