#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\EditTournament.cshtml"
    using ClientDependency.Core.Mvc;
    
    #line default
    #line hidden
    using Examine;
    
    #line 4 "..\..\Views\EditTournament.cshtml"
    using Stoolball.Security;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\EditTournament.cshtml"
    using Stoolball.Web.Matches;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EditTournament.cshtml")]
    public partial class _Views_EditTournament_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<EditTournamentViewModel>
    {
        public _Views_EditTournament_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("head", () => {

WriteLiteral("\r\n    <meta");

WriteLiteral(" name=\"robots\"");

WriteLiteral(" content=\"noindex,follow\"");

WriteLiteral(" />\r\n");

});

            
            #line 8 "..\..\Views\EditTournament.cshtml"
  
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("~/scripts/jquery.validate.min.js");
    Html.RequiresJs("~/scripts/jquery.validate.unobtrusive.min.js");

    Html.RequiresJs("~/js/libs/jquery.autocomplete.min.js", 50);
    Html.RequiresCss("~/css/autocomplete.min.css");

    Html.RequiresCss("~/css/related-items.min.css");
    Html.RequiresJs("~/js/related-item.js");

    Html.RequiresJs("/umbraco/lib/tinymce/tinymce.min.js", 90);
    Html.RequiresJs("/js/tinymce.js");

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>Edit ");

            
            #line 24 "..\..\Views\EditTournament.cshtml"
        Write(Html.TournamentFullNameAndPlayerType(Model.Tournament, x => Model.DateFormatter.FormatDate(x.LocalDateTime, false, false, false)));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");

            
            #line 26 "..\..\Views\EditTournament.cshtml"
    
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\EditTournament.cshtml"
     if (Model.IsAuthorized[AuthorizedAction.EditTournament])
    {
        using (Html.BeginUmbracoForm<EditTournamentSurfaceController>
            ("UpdateTournament"))
        {

            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Save tournament</button>\r\n");

            
            #line 32 "..\..\Views\EditTournament.cshtml"
            
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\EditTournament.cshtml"
       Write(Html.Partial("_CreateOrEditTournament"));

            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\EditTournament.cshtml"
                                                    

            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Save tournament</button>\r\n");

            
            #line 34 "..\..\Views\EditTournament.cshtml"
        }
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\EditTournament.cshtml"
   Write(Html.Partial("_Login"));

            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\EditTournament.cshtml"
                               
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
