#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 4 "..\..\Views\EmailAddress.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\EmailAddress.cshtml"
    using ClientDependency.Core.Mvc;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\EmailAddress.cshtml"
    using ContentModels = Umbraco.Web.PublishedModels;
    
    #line default
    #line hidden
    using Examine;
    
    #line 6 "..\..\Views\EmailAddress.cshtml"
    using Stoolball.Web.Account;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\EmailAddress.cshtml"
    using Stoolball.Web.Email;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    
    #line 5 "..\..\Views\EmailAddress.cshtml"
    using Umbraco.Web;
    
    #line default
    #line hidden
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EmailAddress.cshtml")]
    public partial class _Views_EmailAddress_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.EmailAddress>
    {
        public _Views_EmailAddress_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 8 "..\..\Views\EmailAddress.cshtml"
  
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("~/scripts/jquery.validate.min.js");
    Html.RequiresJs("~/scripts/jquery.validate.unobtrusive.min.js");

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 15 "..\..\Views\EmailAddress.cshtml"
   Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");

            
            #line 17 "..\..\Views\EmailAddress.cshtml"
    
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\EmailAddress.cshtml"
     if (User.Identity.IsAuthenticated)
    {
        if (TempData["Success"] == null)
        {
            
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\EmailAddress.cshtml"
       Write(Html.Partial("_ConfirmEmailAddress", Members.GetCurrentMember()));

            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\EmailAddress.cshtml"
                                                                             

            using (Html.BeginUmbracoForm<EmailAddressSurfaceController>("UpdateEmailAddress"))
            {
                
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\EmailAddress.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\EmailAddress.cshtml"
                                        
                var formData = new EmailAddressFormData();
                formData.RequestedEmail = Members.CurrentUserName;


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 30 "..\..\Views\EmailAddress.cshtml"
               Write(Html.LabelFor(m => formData.RequestedEmail));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 31 "..\..\Views\EmailAddress.cshtml"
               Write(Html.TextBoxFor(m => formData.RequestedEmail, new { @class = "form-control", required = "required", aria_describedby = "form-email", autocorrect = "off", autocapitalize = "off", autocomplete = "email", type = "email" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 32 "..\..\Views\EmailAddress.cshtml"
               Write(Html.ValidationMessageFor(m => formData.RequestedEmail, null, new { id = "form-email" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 34 "..\..\Views\EmailAddress.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 36 "..\..\Views\EmailAddress.cshtml"
               Write(Html.LabelFor(m => formData.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 37 "..\..\Views\EmailAddress.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\EmailAddress.cshtml"
                       var describedBy = "form-password"; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 38 "..\..\Views\EmailAddress.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\EmailAddress.cshtml"
                     if (!string.IsNullOrEmpty(Model.PasswordHelp))
                    {
                        describedBy = "form-password form-password-help";

            
            #line default
            #line hidden
WriteLiteral("                        <p");

WriteLiteral(" class=\"form-text\"");

WriteLiteral(" id=\"form-password-help\"");

WriteLiteral("><small>");

            
            #line 41 "..\..\Views\EmailAddress.cshtml"
                                                                       Write(Model.PasswordHelp);

            
            #line default
            #line hidden
WriteLiteral("</small></p>\r\n");

            
            #line 42 "..\..\Views\EmailAddress.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 43 "..\..\Views\EmailAddress.cshtml"
               Write(Html.TextBoxFor(m => formData.Password, new { @class = "form-control", required = "required", aria_describedby = describedBy, type = "password", autocorrect = "off", autocapitalize = "off", autocomplete = "current-password" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 44 "..\..\Views\EmailAddress.cshtml"
               Write(Html.ValidationMessageFor(m => formData.Password, null, new { id = "form-password" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 46 "..\..\Views\EmailAddress.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <button");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 47 "..\..\Views\EmailAddress.cshtml"
                                           Write(Model.Value("saveButton"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 48 "..\..\Views\EmailAddress.cshtml"
            }
        }
        else
        {
            
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\EmailAddress.cshtml"
       Write(Html.ProtectEmailAddresses(Model.Value<IHtmlString>("requested")));

            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\EmailAddress.cshtml"
                                                                              
        }
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\EmailAddress.cshtml"
   Write(Html.Partial("_Login"));

            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\EmailAddress.cshtml"
                               
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
