#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Master.cshtml"
    using ClientDependency.Core.Mvc;
    
    #line default
    #line hidden
    using Examine;
    
    #line 3 "..\..\Views\Master.cshtml"
    using Stoolball.Navigation;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Master.cshtml")]
    public partial class _Views_Master_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<Stoolball.Web.Metadata.IHasViewMetadata>
    {
        public _Views_Master_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Master.cshtml"
  
    Layout = null;
    Html.RequiresCss("~/css/base.css", 1);
    Html.RequiresJs("~/js/libs/purify.min.js", 1);
    Html.RequiresJs("~/js/trusted-types-policy.js", 2);
    Html.RequiresJs("~/js/register-service-worker.js", 2);
    Html.RequiresJs("~/scripts/jquery-3.5.1.min.js", 3); // full jQuery rather than slim is required for jQuery autocomplete
    Html.RequiresJs("~/scripts/bootstrap.bundle.min.js", 4);
    Html.RequiresJs("~/js/consent.js", 20);
    if (!string.IsNullOrEmpty(Model.Stylesheet))
    {
        Html.RequiresCss($"~/css/{Model.Stylesheet}.min.css");
    }

    if (Model.Breadcrumbs.Count() == 0)
    {
        var breadcrumb = Umbraco.AssignedContentItem.Parent;
        while (breadcrumb != null)
        {
            Model.Breadcrumbs.Insert(0, new Breadcrumb
            {
                Name = breadcrumb.Name,
                Url = new Uri(breadcrumb.Url(), UriKind.Relative)
            });
            breadcrumb = breadcrumb.Parent;
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" dir=\"ltr\"");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 38 "..\..\Views\Master.cshtml"
      Write(Model.Metadata.PageTitle);

            
            #line default
            #line hidden
WriteLiteral(" – Stoolball England</title>\r\n");

            
            #line 39 "..\..\Views\Master.cshtml"
    
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Master.cshtml"
     if (!string.IsNullOrWhiteSpace(Model.Metadata.Description))
    {

            
            #line default
            #line hidden
WriteLiteral("        <meta");

WriteLiteral(" name=\"description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1500), Tuple.Create("\"", 1537)
            
            #line 41 "..\..\Views\Master.cshtml"
, Tuple.Create(Tuple.Create("", 1510), Tuple.Create<System.Object, System.Int32>(Model.Metadata.Description
            
            #line default
            #line hidden
, 1510), false)
);

WriteLiteral(" />\r\n");

            
            #line 42 "..\..\Views\Master.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <link");

WriteLiteral(" rel=\"manifest\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1574), Tuple.Create("\"", 1602)
, Tuple.Create(Tuple.Create("", 1581), Tuple.Create<System.Object, System.Int32>(Href("~/Status/offline.json")
, 1581), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/svg+xml\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1649), Tuple.Create("\"", 1697)
, Tuple.Create(Tuple.Create("", 1656), Tuple.Create<System.Object, System.Int32>(Href("~/images/logos/stoolball-england-icon.svg")
, 1656), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"alternate icon\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1733), Tuple.Create("\"", 1753)
, Tuple.Create(Tuple.Create("", 1740), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 1740), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"preload\"");

WriteLiteral(" href=\"/fonts/mada-v9-latin-regular.woff2\"");

WriteLiteral(" as=\"font\"");

WriteLiteral(" type=\"font/woff2\"");

WriteLiteral(" crossorigin=\"\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"preload\"");

WriteLiteral(" href=\"/fonts/mada-v9-latin-700.woff2\"");

WriteLiteral(" as=\"font\"");

WriteLiteral(" type=\"font/woff2\"");

WriteLiteral(" crossorigin=\"\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"preload\"");

WriteLiteral(" href=\"/fonts/assistant-v6-latin-600.woff2\"");

WriteLiteral(" as=\"font\"");

WriteLiteral(" type=\"font/woff2\"");

WriteLiteral(" crossorigin=\"\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"preload\"");

WriteLiteral(" href=\"/fonts/assistant-v6-latin-700.woff2\"");

WriteLiteral(" as=\"font\"");

WriteLiteral(" type=\"font/woff2\"");

WriteLiteral(" crossorigin=\"\"");

WriteLiteral(" />\r\n");

WriteLiteral("    ");

            
            #line 50 "..\..\Views\Master.cshtml"
Write(RenderSection("canonical", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 51 "..\..\Views\Master.cshtml"
    
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Master.cshtml"
     if (!IsSectionDefined("canonical")) {
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Master.cshtml"
                                     Write(Html.Partial("_CanonicalUrl", Array.Empty<string>()));

            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Master.cshtml"
                                                                                               }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 52 "..\..\Views\Master.cshtml"
Write(RenderSection("head", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 53 "..\..\Views\Master.cshtml"
Write(Html.RenderCssHere());

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    <a");

WriteLiteral(" href=\"#main\"");

WriteLiteral(" class=\"skip-to-content sr-only sr-only-focusable\"");

WriteLiteral("><span>Skip to content</span></a>\r\n");

WriteLiteral("    ");

            
            #line 57 "..\..\Views\Master.cshtml"
Write(Html.Partial("_Header"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 58 "..\..\Views\Master.cshtml"
Write(Html.Partial("_Breadcrumb", Model.Breadcrumbs));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <main");

WriteLiteral(" id=\"main\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 60 "..\..\Views\Master.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </main>\r\n");

WriteLiteral("    ");

            
            #line 62 "..\..\Views\Master.cshtml"
Write(Html.Partial("_Footer"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 63 "..\..\Views\Master.cshtml"
Write(Html.RenderJsHere());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 64 "..\..\Views\Master.cshtml"
Write(RenderSection("umbracoforms", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 65 "..\..\Views\Master.cshtml"
    
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Master.cshtml"
     if (Request.Url.Host != "localhost")
    {

            
            #line default
            #line hidden
WriteLiteral("        <script defer");

WriteLiteral(" src=\'https://static.cloudflareinsights.com/beacon.min.js\'");

WriteLiteral("\r\n            data-cf-beacon=\'{\"token\": \"4b73271c7ec547e2a9ccec95f25bed28\"}\'");

WriteLiteral("></script>\r\n");

            
            #line 69 "..\..\Views\Master.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</body>\r\n\r\n</html>");

        }
    }
}
#pragma warning restore 1591
