#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    
    #line 2 "..\..\Views\MatchActions.cshtml"
    using Stoolball.Matches;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\MatchActions.cshtml"
    using Stoolball.Security;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\MatchActions.cshtml"
    using Stoolball.Web.Matches;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MatchActions.cshtml")]
    public partial class _Views_MatchActions_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<MatchViewModel>
    {
        public _Views_MatchActions_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("head", () => {

WriteLiteral("\r\n    <meta");

WriteLiteral(" name=\"robots\"");

WriteLiteral(" content=\"noindex,follow\"");

WriteLiteral(" />\r\n");

});

WriteLiteral("<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>Edit ");

            
            #line 9 "..\..\Views\MatchActions.cshtml"
        Write(Html.MatchFullName(Model.Match, x => Model.DateTimeFormatter.FormatDate(x.LocalDateTime, false)));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");

            
            #line 11 "..\..\Views\MatchActions.cshtml"
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\MatchActions.cshtml"
     if (Model.IsAuthorized[AuthorizedAction.EditMatch] || Model.IsAuthorized[AuthorizedAction.EditMatchResult] || Model.IsAuthorized[AuthorizedAction.DeleteMatch])
    {

            
            #line default
            #line hidden
WriteLiteral("        <dl>\r\n");

            
            #line 14 "..\..\Views\MatchActions.cshtml"
            
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\MatchActions.cshtml"
             if (Model.IsAuthorized[AuthorizedAction.EditMatch] && Model.Match.StartTime > DateTime.UtcNow)
            {
                switch (Model.Match.MatchType)
                {
                    case MatchType.FriendlyMatch:

            
            #line default
            #line hidden
WriteLiteral("                        <dt><a");

WriteAttribute("href", Tuple.Create(" href=\"", 821), Tuple.Create("\"", 865)
            
            #line 19 "..\..\Views\MatchActions.cshtml"
, Tuple.Create(Tuple.Create("", 828), Tuple.Create<System.Object, System.Int32>(Model.Match.MatchRoute
            
            #line default
            #line hidden
, 828), false)
, Tuple.Create(Tuple.Create("", 851), Tuple.Create("/edit/friendly", 851), true)
);

WriteLiteral(">Edit ");

            
            #line 19 "..\..\Views\MatchActions.cshtml"
                                                                            Write(Html.MatchFullName(Model.Match, x => Model.DateTimeFormatter.FormatDate(x.LocalDateTime, false)));

            
            #line default
            #line hidden
WriteLiteral("</a></dt>\r\n");

WriteLiteral("                        <dd>Set the date and time, teams, location and notes.</dd" +
">\r\n");

            
            #line 21 "..\..\Views\MatchActions.cshtml"
                        break;
                    case MatchType.LeagueMatch:

            
            #line default
            #line hidden
WriteLiteral("                        <dt><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1175), Tuple.Create("\"", 1217)
            
            #line 23 "..\..\Views\MatchActions.cshtml"
, Tuple.Create(Tuple.Create("", 1182), Tuple.Create<System.Object, System.Int32>(Model.Match.MatchRoute
            
            #line default
            #line hidden
, 1182), false)
, Tuple.Create(Tuple.Create("", 1205), Tuple.Create("/edit/league", 1205), true)
);

WriteLiteral(">Edit ");

            
            #line 23 "..\..\Views\MatchActions.cshtml"
                                                                          Write(Html.MatchFullName(Model.Match, x => Model.DateTimeFormatter.FormatDate(x.LocalDateTime, false)));

            
            #line default
            #line hidden
WriteLiteral("</a></dt>\r\n");

WriteLiteral("                        <dd>Set the date and time, teams, location and notes.</dd" +
">\r\n");

            
            #line 25 "..\..\Views\MatchActions.cshtml"
                        break;
                    case MatchType.KnockoutMatch:

            
            #line default
            #line hidden
WriteLiteral("                        <dt><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1529), Tuple.Create("\"", 1573)
            
            #line 27 "..\..\Views\MatchActions.cshtml"
, Tuple.Create(Tuple.Create("", 1536), Tuple.Create<System.Object, System.Int32>(Model.Match.MatchRoute
            
            #line default
            #line hidden
, 1536), false)
, Tuple.Create(Tuple.Create("", 1559), Tuple.Create("/edit/knockout", 1559), true)
);

WriteLiteral(">Edit ");

            
            #line 27 "..\..\Views\MatchActions.cshtml"
                                                                            Write(Html.MatchFullName(Model.Match, x => Model.DateTimeFormatter.FormatDate(x.LocalDateTime, false)));

            
            #line default
            #line hidden
WriteLiteral("</a></dt>\r\n");

WriteLiteral("                        <dd>Set the date and time, teams, location and notes.</dd" +
">\r\n");

            
            #line 29 "..\..\Views\MatchActions.cshtml"
                        break;
                }
            }
            else if (Model.IsAuthorized[AuthorizedAction.EditMatchResult] && Model.Match.StartTime <= DateTime.UtcNow)
            {
                if (Model.Match.MatchType == MatchType.LeagueMatch || Model.Match.MatchType == MatchType.KnockoutMatch || Model.Match.MatchType == MatchType.FriendlyMatch)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <dt><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2191), Tuple.Create("\"", 2240)
            
            #line 36 "..\..\Views\MatchActions.cshtml"
, Tuple.Create(Tuple.Create("", 2198), Tuple.Create<System.Object, System.Int32>(Model.Match.MatchRoute
            
            #line default
            #line hidden
, 2198), false)
, Tuple.Create(Tuple.Create("", 2221), Tuple.Create("/edit/start-of-play", 2221), true)
);

WriteLiteral(">Edit the result of ");

            
            #line 36 "..\..\Views\MatchActions.cshtml"
                                                                                           Write(Html.MatchFullName(Model.Match, x => Model.DateTimeFormatter.FormatDate(x.LocalDateTime, false)));

            
            #line default
            #line hidden
WriteLiteral("</a></dt>\r\n");

WriteLiteral("                    <dd>Enter scorecards, set who won the toss and their decision" +
", or say why the match didn\'t happen.</dd>\r\n");

            
            #line 38 "..\..\Views\MatchActions.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 40 "..\..\Views\MatchActions.cshtml"
             if (Model.IsAuthorized[AuthorizedAction.DeleteMatch])
            {

            
            #line default
            #line hidden
WriteLiteral("                <dt><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2633), Tuple.Create("\"", 2670)
            
            #line 42 "..\..\Views\MatchActions.cshtml"
, Tuple.Create(Tuple.Create("", 2640), Tuple.Create<System.Object, System.Int32>(Model.Match.MatchRoute
            
            #line default
            #line hidden
, 2640), false)
, Tuple.Create(Tuple.Create("", 2663), Tuple.Create("/delete", 2663), true)
);

WriteLiteral(">Delete ");

            
            #line 42 "..\..\Views\MatchActions.cshtml"
                                                               Write(Html.MatchFullName(Model.Match, x => Model.DateTimeFormatter.FormatDate(x.LocalDateTime, false)));

            
            #line default
            #line hidden
WriteLiteral("</a></dt>\r\n");

WriteLiteral("                <dd>Match statistics will be lost. Competition results may be cha" +
"nged. Players that only feature in this match will be deleted.</dd>\r\n");

            
            #line 44 "..\..\Views\MatchActions.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </dl>\r\n");

            
            #line 46 "..\..\Views\MatchActions.cshtml"
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\MatchActions.cshtml"
   Write(Html.Partial("_Login"));

            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\MatchActions.cshtml"
                               
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
