#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\MostRuns.cshtml"
    using ClientDependency.Core.Mvc;
    
    #line default
    #line hidden
    using Examine;
    
    #line 2 "..\..\Views\MostRuns.cshtml"
    using Stoolball.Statistics;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\MostRuns.cshtml"
    using Stoolball.Web.Statistics;
    
    #line default
    #line hidden
    using Umbraco.Core;
    
    #line 5 "..\..\Views\MostRuns.cshtml"
    using Umbraco.Core.Composing;
    
    #line default
    #line hidden
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MostRuns.cshtml")]
    public partial class _Views_MostRuns_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<StatisticsViewModel<BestStatistic>>
    {
        public _Views_MostRuns_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\MostRuns.cshtml"
  
    var humanizer = Current.Factory.GetInstance<IStatisticsFilterHumanizer>();
    Html.RequiresCss("/statistics/statistics.min.css");

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("canonical", () => {

            
            #line 10 "..\..\Views\MostRuns.cshtml"
               Write(Html.Partial("_CanonicalUrl", new[] { "page" }));

            
            #line default
            #line hidden
});

DefineSection("head", () => {

WriteLiteral("\r\n");

            
            #line 12 "..\..\Views\MostRuns.cshtml"
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\MostRuns.cshtml"
     if (Model.AppliedFilter.Paging.PageNumber == 1)
    {

            
            #line default
            #line hidden
WriteLiteral("        <meta");

WriteLiteral(" name=\"robots\"");

WriteLiteral(" content=\"index, nofollow\"");

WriteLiteral(">\r\n");

            
            #line 15 "..\..\Views\MostRuns.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <meta");

WriteLiteral(" name=\"robots\"");

WriteLiteral(" content=\"noindex, nofollow\"");

WriteLiteral(">\r\n");

            
            #line 19 "..\..\Views\MostRuns.cshtml"
    }

            
            #line default
            #line hidden
});

WriteLiteral("<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>Most runs");

            
            #line 22 "..\..\Views\MostRuns.cshtml"
             Write(humanizer.MatchingFixedFilter(Model.AppliedFilter));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");

WriteLiteral("    ");

            
            #line 24 "..\..\Views\MostRuns.cshtml"
Write(Html.Partial("_StatisticsBasis"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 25 "..\..\Views\MostRuns.cshtml"
Write(Html.Partial("_MostRuns"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
