#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\MyAccount.cshtml"
    using ClientDependency.Core.Mvc;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\MyAccount.cshtml"
    using ContentModels = Umbraco.Web.PublishedModels;
    
    #line default
    #line hidden
    using Examine;
    
    #line 4 "..\..\Views\MyAccount.cshtml"
    using Stoolball.Web.Account;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\MyAccount.cshtml"
    using Stoolball.Web.Email;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MyAccount.cshtml")]
    public partial class _Views_MyAccount_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.MyAccount>
    {
        public _Views_MyAccount_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\MyAccount.cshtml"
   
    Html.RequiresCss("~/account/account.min.css");

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 10 "..\..\Views\MyAccount.cshtml"
   Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");

            
            #line 12 "..\..\Views\MyAccount.cshtml"
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\MyAccount.cshtml"
     if (User.Identity.IsAuthenticated)
    {
        var gravatar = new Gravatar(User.Identity.Name);
        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\MyAccount.cshtml"
   Write(Html.GetBlockListHtml(Model, "blockList"));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\MyAccount.cshtml"
                                                  


            
            #line default
            #line hidden
WriteLiteral("        <h2>Account picture</h2>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"gravatar\"");

WriteLiteral(">\r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 571), Tuple.Create("\"", 590)
            
            #line 19 "..\..\Views\MyAccount.cshtml"
, Tuple.Create(Tuple.Create("", 577), Tuple.Create<System.Object, System.Int32>(gravatar.Url
            
            #line default
            #line hidden
, 577), false)
);

WriteLiteral(" alt=\"Your account picture from gravatar.com\"");

WriteAttribute("width", Tuple.Create(" width=\"", 636), Tuple.Create("\"", 658)
            
            #line 19 "..\..\Views\MyAccount.cshtml"
          , Tuple.Create(Tuple.Create("", 644), Tuple.Create<System.Object, System.Int32>(gravatar.Size
            
            #line default
            #line hidden
, 644), false)
);

WriteAttribute("height", Tuple.Create(" height=\"", 659), Tuple.Create("\"", 682)
            
            #line 19 "..\..\Views\MyAccount.cshtml"
                                  , Tuple.Create(Tuple.Create("", 668), Tuple.Create<System.Object, System.Int32>(gravatar.Size
            
            #line default
            #line hidden
, 668), false)
);

WriteLiteral(" />\r\n            <div>");

            
            #line 20 "..\..\Views\MyAccount.cshtml"
            Write(Html.ProtectEmailAddresses(Model.Value<IHtmlString>("gravatar")));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </div>\r\n");

            
            #line 22 "..\..\Views\MyAccount.cshtml"
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\MyAccount.cshtml"
   Write(Html.Partial("_Login"));

            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\MyAccount.cshtml"
                               
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
