#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\NewsStory.cshtml"
    using ClientDependency.Core.Mvc;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\NewsStory.cshtml"
    using ContentModels = Umbraco.Web.PublishedModels;
    
    #line default
    #line hidden
    using Examine;
    
    #line 6 "..\..\Views\NewsStory.cshtml"
    using Humanizer;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\NewsStory.cshtml"
    using Stoolball.Dates;
    
    #line default
    #line hidden
    using Umbraco.Core;
    
    #line 4 "..\..\Views\NewsStory.cshtml"
    using Umbraco.Core.Composing;
    
    #line default
    #line hidden
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/NewsStory.cshtml")]
    public partial class _Views_NewsStory_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.NewsStory>
    {
        public _Views_NewsStory_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\Views\NewsStory.cshtml"
  
    Html.RequiresCss("~/css/news.min.css");
    if (Model.BlockList.Any(x => x.Content is FormElementType))
    {
        Html.RequiresJs("~/scripts/jquery.validate.min.js");
        Html.RequiresJs("~/scripts/jquery.validate.unobtrusive.min.js");

        Html.RequiresJs("/umbraco/lib/tinymce/tinymce.min.js", 90);
        Html.RequiresJs("/js/tinymce.js");
    }
    var formatter = Current.Factory.GetInstance<IDateTimeFormatter>();

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 20 "..\..\Views\NewsStory.cshtml"
   Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n    <p");

WriteLiteral(" class=\"news__date\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\NewsStory.cshtml"
                      Write(formatter.FormatDate(Model.DisplayDate == DateTime.MinValue ? Model.CreateDate : Model.DisplayDate).Humanize(LetterCasing.Title));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

WriteLiteral("    ");

            
            #line 22 "..\..\Views\NewsStory.cshtml"
Write(Html.GetBlockListHtml(Model, "blockList"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
