#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\PlayerFielding.cshtml"
    using ClientDependency.Core.Mvc;
    
    #line default
    #line hidden
    using Examine;
    
    #line 6 "..\..\Views\PlayerFielding.cshtml"
    using Stoolball.Matches;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\PlayerFielding.cshtml"
    using Stoolball.Statistics;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\PlayerFielding.cshtml"
    using Stoolball.Web.Filtering;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\PlayerFielding.cshtml"
    using Stoolball.Web.Statistics;
    
    #line default
    #line hidden
    using Umbraco.Core;
    
    #line 3 "..\..\Views\PlayerFielding.cshtml"
    using Umbraco.Core.Composing;
    
    #line default
    #line hidden
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PlayerFielding.cshtml")]
    public partial class _Views_PlayerFielding_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<PlayerFieldingViewModel>
    {
        public _Views_PlayerFielding_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 8 "..\..\Views\PlayerFielding.cshtml"
  
    Html.RequiresCss("/statistics/statistics.min.css");
    Html.RequiresJs("/js/filter.js");
    Html.RequiresCss("/css/filter.min.css");

    var catches = new StatisticsViewModel<PlayerInnings>(Model, Services.UserService) { ShowCaption = true, AppliedFilter = Model.AppliedFilter };
    catches.Results.AddRange(Model.Catches);
    var runOuts = new StatisticsViewModel<PlayerInnings>(Model, Services.UserService) { ShowCaption = true, AppliedFilter = Model.AppliedFilter };
    runOuts.Results.AddRange(Model.RunOuts);

    var serialiser = Current.Factory.GetInstance<IStatisticsFilterQueryStringSerializer>();
    var queryString = serialiser.Serialize(Model.AppliedFilter, Model.DefaultFilter);

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 22 "..\..\Views\PlayerFielding.cshtml"
Write(Html.Partial("_PlayerHeader"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"nav-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1133), Tuple.Create("\"", 1179)
            
            #line 26 "..\..\Views\PlayerFielding.cshtml"
, Tuple.Create(Tuple.Create("", 1140), Tuple.Create<System.Object, System.Int32>(Model.Player.PlayerRoute
            
            #line default
            #line hidden
, 1140), false)
            
            #line 26 "..\..\Views\PlayerFielding.cshtml"
, Tuple.Create(Tuple.Create("", 1165), Tuple.Create<System.Object, System.Int32>(queryString
            
            #line default
            #line hidden
, 1165), false)
);

WriteLiteral(">Batting</a>\r\n        </li>\r\n        <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"nav-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1271), Tuple.Create("\"", 1325)
            
            #line 29 "..\..\Views\PlayerFielding.cshtml"
, Tuple.Create(Tuple.Create("", 1278), Tuple.Create<System.Object, System.Int32>(Model.Player.PlayerRoute
            
            #line default
            #line hidden
, 1278), false)
, Tuple.Create(Tuple.Create("", 1303), Tuple.Create("/bowling", 1303), true)
            
            #line 29 "..\..\Views\PlayerFielding.cshtml"
, Tuple.Create(Tuple.Create("", 1311), Tuple.Create<System.Object, System.Int32>(queryString
            
            #line default
            #line hidden
, 1311), false)
);

WriteLiteral(">Bowling</a>\r\n        </li>\r\n        <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(">\r\n            <em");

WriteLiteral(" class=\"nav-link active\"");

WriteLiteral(">Fielding</em>\r\n        </li>\r\n        <li");

WriteLiteral(" class=\"nav-item nav-item-admin\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"nav-link nav-link-filter\"");

WriteLiteral(">Edit filter</button>\r\n        </li>\r\n    </ul>\r\n");

WriteLiteral("    ");

            
            #line 38 "..\..\Views\PlayerFielding.cshtml"
Write(Html.Partial("_Filters", new FilterViewModel
{
    FilteredItemTypeSingular = "Statistics",
    FilteredItemTypePlural = "Statistics",
    FilterDescription = Model.FilterDescription,
    from = Model.AppliedFilter.FromDate,
    to = Model.AppliedFilter.UntilDate
}));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 47 "..\..\Views\PlayerFielding.cshtml"
    
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\PlayerFielding.cshtml"
     if (Model.FieldingStatistics.TotalCatches == 0 && Model.FieldingStatistics.TotalRunOuts == 0)
    {
        
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\PlayerFielding.cshtml"
   Write(Html.Partial("_NoData"));

            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\PlayerFielding.cshtml"
                                
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <table");

WriteLiteral(" class=\"table-as-cards table-as-cards-reset-sm\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Catches</th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Most catches</th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Run-outs</th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Most run-outs</th>\r\n                </tr>\r\n            </thead>\r\n            <tb" +
"ody>\r\n                <tr>\r\n                    <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Catches</span>");

            
            #line 64 "..\..\Views\PlayerFielding.cshtml"
                                                                                                              Write(Model.FieldingStatistics.TotalCatches);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Most catches</span>");

            
            #line 65 "..\..\Views\PlayerFielding.cshtml"
                                                                                                                   Write(Model.FieldingStatistics.MostCatches);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Run-outs</span>");

            
            #line 66 "..\..\Views\PlayerFielding.cshtml"
                                                                                                               Write(Model.FieldingStatistics.TotalRunOuts);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Most run-outs</span>");

            
            #line 67 "..\..\Views\PlayerFielding.cshtml"
                                                                                                                    Write(Model.FieldingStatistics.MostRunOuts);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n            </tbody>\r\n        </table>\r\n");

            
            #line 71 "..\..\Views\PlayerFielding.cshtml"

        
            
            #line default
            #line hidden
            
            #line 72 "..\..\Views\PlayerFielding.cshtml"
   Write(Html.Partial("_Catches", catches));

            
            #line default
            #line hidden
            
            #line 72 "..\..\Views\PlayerFielding.cshtml"
                                          
        if (Model.FieldingStatistics.TotalCatches > catches.Results.Count)
        {

            
            #line default
            #line hidden
WriteLiteral("            <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3334), Tuple.Create("\"", 3409)
            
            #line 75 "..\..\Views\PlayerFielding.cshtml"
, Tuple.Create(Tuple.Create("", 3341), Tuple.Create<System.Object, System.Int32>(Request.Url.AbsolutePath.TrimEnd("/fielding")
            
            #line default
            #line hidden
, 3341), false)
, Tuple.Create(Tuple.Create("", 3387), Tuple.Create("/catches", 3387), true)
            
            #line 75 "..\..\Views\PlayerFielding.cshtml"
, Tuple.Create(Tuple.Create("", 3395), Tuple.Create<System.Object, System.Int32>(queryString
            
            #line default
            #line hidden
, 3395), false)
);

WriteLiteral(">Catches – view all and filter</a></p>\r\n");

            
            #line 76 "..\..\Views\PlayerFielding.cshtml"
        }
        
            
            #line default
            #line hidden
            
            #line 77 "..\..\Views\PlayerFielding.cshtml"
   Write(Html.Partial("_RunOuts", runOuts));

            
            #line default
            #line hidden
            
            #line 77 "..\..\Views\PlayerFielding.cshtml"
                                          
        if (Model.FieldingStatistics.TotalRunOuts > catches.Results.Count)
        {

            
            #line default
            #line hidden
WriteLiteral("            <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3609), Tuple.Create("\"", 3671)
            
            #line 80 "..\..\Views\PlayerFielding.cshtml"
, Tuple.Create(Tuple.Create("", 3616), Tuple.Create<System.Object, System.Int32>(Request.Url.AbsolutePath.TrimEnd("/fielding")
            
            #line default
            #line hidden
, 3616), false)
, Tuple.Create(Tuple.Create("", 3662), Tuple.Create("/run-outs", 3662), true)
);

WriteLiteral(">Run-outs – view all</a></p>\r\n");

            
            #line 81 "..\..\Views\PlayerFielding.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
