#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\ProductList.cshtml"
    using ClientDependency.Core.Mvc;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\ProductList.cshtml"
    using ContentModels = Umbraco.Web.PublishedModels;
    
    #line default
    #line hidden
    using Examine;
    
    #line 5 "..\..\Views\ProductList.cshtml"
    using Stoolball.Email;
    
    #line default
    #line hidden
    using Umbraco.Core;
    
    #line 4 "..\..\Views\ProductList.cshtml"
    using Umbraco.Core.Composing;
    
    #line default
    #line hidden
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ProductList.cshtml")]
    public partial class _Views_ProductList_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ProductList>
    {
        public _Views_ProductList_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\ProductList.cshtml"
  
    Html.RequiresJs("~/scripts/jquery.validate.min.js");
    Html.RequiresJs("~/scripts/jquery.validate.unobtrusive.min.js");

    Html.RequiresJs("/umbraco/lib/tinymce/tinymce.min.js", 90);
    Html.RequiresJs("/js/tinymce.js");

    var emailProtector = (IEmailProtector)Current.Factory.GetInstance(typeof(IEmailProtector));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 16 "..\..\Views\ProductList.cshtml"
   Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n    \r\n    <div");

WriteLiteral(" class=\"product-list__intro\"");

WriteLiteral(">\r\n        <div>");

            
            #line 20 "..\..\Views\ProductList.cshtml"
        Write(Html.Raw(emailProtector.ProtectEmailAddresses(Model.Introduction.ToHtmlString(), User.Identity.IsAuthenticated)));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        <a");

WriteLiteral(" href=\"https://shop.spreadshirt.co.uk/stoolball\"");

WriteLiteral(">            \r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 880), Tuple.Create("\"", 915)
, Tuple.Create(Tuple.Create("", 886), Tuple.Create<System.Object, System.Int32>(Href("~/images/shop/spreadshirt.png")
, 886), false)
);

WriteLiteral(" alt=\"Products from our gift shop\"");

WriteLiteral(" width=\"600\"");

WriteLiteral(" />\r\n            <p");

WriteLiteral(" class=\"btn btn-primary btn-lg\"");

WriteLiteral(">Visit our gift shop</p>\r\n        </a>\r\n    </div>\r\n\r\n");

            
            #line 27 "..\..\Views\ProductList.cshtml"
    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\ProductList.cshtml"
     if (Model.Products.Any())
    {

            
            #line default
            #line hidden
WriteLiteral("        <ul");

WriteLiteral(" class=\"tiles product-list\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Views\ProductList.cshtml"
       Write(Html.GetBlockListHtml(Model, "products", "BlockList"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n");

            
            #line 32 "..\..\Views\ProductList.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 33 "..\..\Views\ProductList.cshtml"
Write(Html.Raw(emailProtector.ProtectEmailAddresses(Model.FurtherDetails.ToHtmlString(), User.Identity.IsAuthenticated)));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 34 "..\..\Views\ProductList.cshtml"
    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\ProductList.cshtml"
     if (Model.EnquiryForm != null)
    {
        
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\ProductList.cshtml"
   Write(Umbraco.RenderMacro("renderUmbracoForm", new { FormGuid = Model.EnquiryForm, FormTheme = "stoolball", ExcludeScripts = "1" }));

            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\ProductList.cshtml"
                                                                                                                                      
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
