#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 7 "..\..\Views\Team.cshtml"
    using ClientDependency.Core.Mvc;
    
    #line default
    #line hidden
    using Examine;
    
    #line 6 "..\..\Views\Team.cshtml"
    using Humanizer;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Team.cshtml"
    using Stoolball.Security;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Team.cshtml"
    using Stoolball.SocialMedia;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Team.cshtml"
    using Stoolball.Teams;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Team.cshtml"
    using Stoolball.Web.Competitions;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Team.cshtml")]
    public partial class _Views_Team_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<Stoolball.Web.Teams.TeamViewModel>
    {
        public _Views_Team_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 8 "..\..\Views\Team.cshtml"
  
    var authorizedToEdit = Model.IsAuthorized[AuthorizedAction.EditTeam] || Model.IsAuthorized[AuthorizedAction.DeleteTeam];
    Html.RequiresJs("/teams/team.js");

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 13 "..\..\Views\Team.cshtml"
   Write(Model.Team.TeamNameLocationAndPlayerType());

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");

            
            #line 15 "..\..\Views\Team.cshtml"
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Team.cshtml"
     if (Model.Team.UntilYear.HasValue)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(">\r\n            <p><strong>This team is no longer active.</strong></p>\r\n        </" +
"div>\r\n");

            
            #line 20 "..\..\Views\Team.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <ul");

WriteAttribute("class", Tuple.Create(" class=\"", 695), Tuple.Create("\"", 772)
, Tuple.Create(Tuple.Create("", 703), Tuple.Create("nav", 703), true)
, Tuple.Create(Tuple.Create(" ", 706), Tuple.Create("nav-tabs", 707), true)
            
            #line 22 "..\..\Views\Team.cshtml"
, Tuple.Create(Tuple.Create("", 715), Tuple.Create<System.Object, System.Int32>(authorizedToEdit ? " nav-tabs-has-edit" : string.Empty
            
            #line default
            #line hidden
, 715), false)
);

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(">\r\n            <em");

WriteLiteral(" class=\"nav-link active\"");

WriteLiteral(">Summary</em>\r\n        </li>\r\n        <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"nav-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 938), Tuple.Create("\"", 974)
            
            #line 27 "..\..\Views\Team.cshtml"
, Tuple.Create(Tuple.Create("", 945), Tuple.Create<System.Object, System.Int32>(Model.Team.TeamRoute
            
            #line default
            #line hidden
, 945), false)
, Tuple.Create(Tuple.Create("", 966), Tuple.Create("/matches", 966), true)
);

WriteLiteral(">Matches</a>\r\n        </li>\r\n        <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"nav-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1066), Tuple.Create("\"", 1105)
            
            #line 30 "..\..\Views\Team.cshtml"
, Tuple.Create(Tuple.Create("", 1073), Tuple.Create<System.Object, System.Int32>(Model.Team.TeamRoute
            
            #line default
            #line hidden
, 1073), false)
, Tuple.Create(Tuple.Create("", 1094), Tuple.Create("/statistics", 1094), true)
);

WriteLiteral(">Statistics</a>\r\n        </li>\r\n");

            
            #line 32 "..\..\Views\Team.cshtml"
        
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Team.cshtml"
         if (authorizedToEdit)
        {

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" class=\"nav-item nav-item-admin\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"nav-link nav-link-edit\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1280), Tuple.Create("\"", 1313)
            
            #line 35 "..\..\Views\Team.cshtml"
, Tuple.Create(Tuple.Create("", 1287), Tuple.Create<System.Object, System.Int32>(Model.Team.TeamRoute
            
            #line default
            #line hidden
, 1287), false)
, Tuple.Create(Tuple.Create("", 1308), Tuple.Create("/edit", 1308), true)
);

WriteLiteral(">Edit team</a>\r\n            </li>\r\n");

            
            #line 37 "..\..\Views\Team.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n\r\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Views\Team.cshtml"
Write(Html.Raw(Model.Team.Introduction));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 42 "..\..\Views\Team.cshtml"
    
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Team.cshtml"
     if (Model.Team.MatchLocations.Count > 0 || !string.IsNullOrWhiteSpace(Model.Team.PlayingTimes))
    {

            
            #line default
            #line hidden
WriteLiteral("        <h2>When and where</h2>\r\n");

            
            #line 45 "..\..\Views\Team.cshtml"
        if (Model.Team.MatchLocations.Count > 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>This team plays at ");

            
            #line 47 "..\..\Views\Team.cshtml"
                             Write(Html.Raw(Model.Team.MatchLocations.Humanize(x => $"<a href=\"{Html.Encode(x.MatchLocationRoute)}\">{Html.Encode(x.NameAndLocalityOrTownIfDifferent())}</a>")));

            
            #line default
            #line hidden
WriteLiteral(".</p>\r\n");

            
            #line 48 "..\..\Views\Team.cshtml"
        }
        if (!string.IsNullOrWhiteSpace(Model.Team.PlayingTimes))
        {
            
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Team.cshtml"
       Write(Html.Raw(Model.Team.PlayingTimes));

            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Team.cshtml"
                                              
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 55 "..\..\Views\Team.cshtml"
    
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Team.cshtml"
      
        var seasonListModel = new SeasonListViewModel
        {
            ShowCompetitionHeading = true
        };
        seasonListModel.Competitions.AddRange(Model.Team.Seasons
            .GroupBy(x => x.Season.Competition.CompetitionId)
            .Select(seasonsInACompetition =>
            {
                var competition = seasonsInACompetition.First().Season.Competition;
                competition.Seasons.AddRange(seasonsInACompetition.Select(season => season.Season));
                return competition;
            })
            .OrderByDescending(x => x.Seasons.First().FromYear).ThenByDescending(x => x.Seasons.First().UntilYear).ThenBy(x => x.ComparableName()));

        
            
            #line default
            #line hidden
            
            #line 70 "..\..\Views\Team.cshtml"
   Write(Html.Partial("_SeasonListExpandable", seasonListModel));

            
            #line default
            #line hidden
            
            #line 70 "..\..\Views\Team.cshtml"
                                                               ;
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 73 "..\..\Views\Team.cshtml"
    
            
            #line default
            #line hidden
            
            #line 73 "..\..\Views\Team.cshtml"
     if (!string.IsNullOrWhiteSpace(Model.Team.Cost))
    {

            
            #line default
            #line hidden
WriteLiteral("        <h2>How much does it cost?</h2>\r\n");

            
            #line 76 "..\..\Views\Team.cshtml"
        
            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\Team.cshtml"
   Write(Html.Raw(Model.Team.Cost));

            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\Team.cshtml"
                                  
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <h2>Contact details</h2>\r\n");

            
            #line 80 "..\..\Views\Team.cshtml"
    
            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\Team.cshtml"
      
        var socialMedia = new SocialMedia
        {
            DisplayName = Model.Team.TeamName,
            Facebook = Model.Team.Facebook,
            Twitter = Model.Team.Twitter,
            Instagram = Model.Team.Instagram,
            YouTube = Model.Team.YouTube
        };
        if (!string.IsNullOrWhiteSpace(Model.Team.PublicContactDetails) || !string.IsNullOrWhiteSpace(Model.Team.Website) || socialMedia.HasSocialMedia())
        {
            
            
            #line default
            #line hidden
            
            #line 91 "..\..\Views\Team.cshtml"
       Write(Html.Raw(Model.Team.PublicContactDetails));

            
            #line default
            #line hidden
            
            #line 91 "..\..\Views\Team.cshtml"
                                                      

            if (!string.IsNullOrWhiteSpace(Model.Team.Website))
            {

            
            #line default
            #line hidden
WriteLiteral("                <p>Visit <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3568), Tuple.Create("\"", 3594)
            
            #line 95 "..\..\Views\Team.cshtml"
, Tuple.Create(Tuple.Create("", 3575), Tuple.Create<System.Object, System.Int32>(Model.Team.Website
            
            #line default
            #line hidden
, 3575), false)
);

WriteLiteral(">");

            
            #line 95 "..\..\Views\Team.cshtml"
                                                  Write(Model.Team.TeamName);

            
            #line default
            #line hidden
WriteLiteral("\'s website</a>.</p>\r\n");

            
            #line 96 "..\..\Views\Team.cshtml"
            }

            
            
            #line default
            #line hidden
            
            #line 98 "..\..\Views\Team.cshtml"
       Write(Html.Partial("_SocialMedia", socialMedia));

            
            #line default
            #line hidden
            
            #line 98 "..\..\Views\Team.cshtml"
                                                      
        }
        else if (Model.Team.TeamType != TeamType.Representative)
        {
            // Prompt for more contact information, unless it's a representative team when we don't expect it
            
            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\Team.cshtml"
       Write(Html.Partial("_ContactDetailsMissing", "team"));

            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\Team.cshtml"
                                                           
        }
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 107 "..\..\Views\Team.cshtml"
    
            
            #line default
            #line hidden
            
            #line 107 "..\..\Views\Team.cshtml"
     if (Model.Team.ClubMark)
    {
        
            
            #line default
            #line hidden
            
            #line 109 "..\..\Views\Team.cshtml"
   Write(Html.Partial("_ClubMark"));

            
            #line default
            #line hidden
            
            #line 109 "..\..\Views\Team.cshtml"
                                  
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
