#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Tournaments.cshtml"
    using ClientDependency.Core.Mvc;
    
    #line default
    #line hidden
    using Examine;
    
    #line 3 "..\..\Views\Tournaments.cshtml"
    using Stoolball.Web.Matches;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tournaments.cshtml")]
    public partial class _Views_Tournaments_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<MatchListingViewModel>
    {
        public _Views_Tournaments_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("canonical", () => {

            
            #line 4 "..\..\Views\Tournaments.cshtml"
               Write(Html.Partial("_CanonicalUrl", new[] { "page", "q" }));

            
            #line default
            #line hidden
});

            
            #line 5 "..\..\Views\Tournaments.cshtml"
  
    Html.RequiresJs("/js/filter.js");
    Html.RequiresCss("/css/filter.min.css");

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 10 "..\..\Views\Tournaments.cshtml"
   Write(Stoolball.Constants.Pages.Tournaments);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n    <ul");

WriteLiteral(" class=\"nav nav-tabs nav-tabs-has-add\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"/matches\"");

WriteLiteral(" class=\"nav-link\"");

WriteLiteral(">Matches</a>\r\n        </li>\r\n        <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(">\r\n            <em");

WriteLiteral(" class=\"nav-link active\"");

WriteLiteral(">Tournaments</em>\r\n        </li>\r\n        <li");

WriteLiteral(" class=\"nav-item nav-item-admin\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"nav-link nav-link-filter\"");

WriteLiteral(">Edit filter</button>\r\n        </li>\r\n    </ul>\r\n");

WriteLiteral("    ");

            
            #line 23 "..\..\Views\Tournaments.cshtml"
Write(Html.Partial("_MatchFilter", new MatchFilterViewModel
    {
        FilterDescription = Model.FilterDescription,
        from = Model.MatchFilter.FromDate,
        to = Model.MatchFilter.UntilDate
    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 30 "..\..\Views\Tournaments.cshtml"
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Tournaments.cshtml"
     if (Model.Matches.Count > 0)
    {
        
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Tournaments.cshtml"
   Write(Html.Partial("_MatchList", Model));

            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Tournaments.cshtml"
                                          
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>There are no tournaments matching this filter.</p>\r\n");

WriteLiteral("        <p>Find out how to <a");

WriteLiteral(" href=\"/organise/website/\"");

WriteLiteral(">add matches and results to our website</a>.</p>\r\n");

            
            #line 38 "..\..\Views\Tournaments.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Views\Tournaments.cshtml"
Write(Html.Partial("_Paging", Model.MatchFilter.Paging));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 41 "..\..\Views\Tournaments.cshtml"
Write(Html.Partial("_MatchListSubscriptions", new MatchListSubscriptionsViewModel { FilenameWithoutExtension = "tournaments" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
