#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    
    #line 2 "..\..\Views\TransientTeam.cshtml"
    using Stoolball.Security;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/TransientTeam.cshtml")]
    public partial class _Views_TransientTeam_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<Stoolball.Web.Teams.TeamViewModel>
    {
        public _Views_TransientTeam_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\TransientTeam.cshtml"
   
    var firstAndOnlyMatch = Model.Matches.Matches.FirstOrDefault();
    var authorizedToEdit = Model.IsAuthorized[AuthorizedAction.EditTeam] || Model.IsAuthorized[AuthorizedAction.DeleteTeam];

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("head", () => {

WriteLiteral("\r\n    <meta");

WriteLiteral(" name=\"robots\"");

WriteLiteral(" content=\"noindex,follow\"");

WriteLiteral(" />\r\n");

});

WriteLiteral("<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 11 "..\..\Views\TransientTeam.cshtml"
   Write(Model.Team.TeamNameAndPlayerType());

            
            #line default
            #line hidden
WriteLiteral(", ");

            
            #line 11 "..\..\Views\TransientTeam.cshtml"
                                        Write(Model.Matches.DateTimeFormatter.FormatDate(firstAndOnlyMatch.StartTime, false, false));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");

            
            #line 13 "..\..\Views\TransientTeam.cshtml"
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\TransientTeam.cshtml"
     if (firstAndOnlyMatch.StartTime < DateTime.UtcNow)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(">\r\n            <p><strong>This team is no longer active.</strong></p>\r\n        </" +
"div>\r\n");

            
            #line 18 "..\..\Views\TransientTeam.cshtml"
    }

    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\TransientTeam.cshtml"
                                                                                                                                           

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 21 "..\..\Views\TransientTeam.cshtml"
     if (authorizedToEdit)
    {

            
            #line default
            #line hidden
WriteLiteral("        <ul");

WriteAttribute("class", Tuple.Create(" class=\"", 933), Tuple.Create("\"", 1010)
, Tuple.Create(Tuple.Create("", 941), Tuple.Create("nav", 941), true)
, Tuple.Create(Tuple.Create(" ", 944), Tuple.Create("nav-tabs", 945), true)
            
            #line 23 "..\..\Views\TransientTeam.cshtml"
, Tuple.Create(Tuple.Create("", 953), Tuple.Create<System.Object, System.Int32>(authorizedToEdit ? " nav-tabs-has-edit" : string.Empty
            
            #line default
            #line hidden
, 953), false)
);

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(">\r\n                <em");

WriteLiteral(" class=\"nav-link active\"");

WriteLiteral(">Summary</em>\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"nav-item nav-item-admin\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"nav-link nav-link-edit\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1225), Tuple.Create("\"", 1258)
            
            #line 28 "..\..\Views\TransientTeam.cshtml"
, Tuple.Create(Tuple.Create("", 1232), Tuple.Create<System.Object, System.Int32>(Model.Team.TeamRoute
            
            #line default
            #line hidden
, 1232), false)
, Tuple.Create(Tuple.Create("", 1253), Tuple.Create("/edit", 1253), true)
);

WriteLiteral(">Edit team</a>\r\n            </li>\r\n        </ul>\r\n");

            
            #line 31 "..\..\Views\TransientTeam.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 33 "..\..\Views\TransientTeam.cshtml"
Write(Html.Raw(Model.Team.Introduction));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <h2>When and where</h2>\r\n");

            
            #line 36 "..\..\Views\TransientTeam.cshtml"
    
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\TransientTeam.cshtml"
      
        IHtmlString atLocation = null;
        if (Model.Team.MatchLocations.Count > 0)
        {
            atLocation = new HtmlString(" at <a href=\"" + Model.Team.MatchLocations.First().MatchLocationRoute + "\">" + Model.Team.MatchLocations.First().NameAndLocalityOrTownIfDifferent() + "</a>");
        }
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 44 "..\..\Views\TransientTeam.cshtml"
    
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\TransientTeam.cshtml"
       var verb = (firstAndOnlyMatch.StartTime < DateTime.UtcNow) ? "came" : "will come"; 
            
            #line default
            #line hidden
WriteLiteral("\r\n    <p>This team ");

            
            #line 45 "..\..\Views\TransientTeam.cshtml"
            Write(verb);

            
            #line default
            #line hidden
WriteLiteral(" together once to play in a tournament");

            
            #line 45 "..\..\Views\TransientTeam.cshtml"
                                                        Write(atLocation);

            
            #line default
            #line hidden
WriteLiteral(":</p>\r\n");

WriteLiteral("    ");

            
            #line 46 "..\..\Views\TransientTeam.cshtml"
Write(Html.Partial("_MatchList", Model.Matches));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 48 "..\..\Views\TransientTeam.cshtml"
    
            
            #line default
            #line hidden
            
            #line 48 "..\..\Views\TransientTeam.cshtml"
     if (!string.IsNullOrWhiteSpace(Model.Team.Cost))
    {

            
            #line default
            #line hidden
WriteLiteral("        <h2>How much does it cost?</h2>\r\n");

            
            #line 51 "..\..\Views\TransientTeam.cshtml"
        
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\TransientTeam.cshtml"
   Write(Html.Raw(Model.Team.Cost));

            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\TransientTeam.cshtml"
                                  
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 54 "..\..\Views\TransientTeam.cshtml"
    
            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\TransientTeam.cshtml"
     if (!string.IsNullOrWhiteSpace(Model.Team.PublicContactDetails) || !string.IsNullOrWhiteSpace(Model.Team.Website))
    {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Contact details</h2>\r\n");

            
            #line 57 "..\..\Views\TransientTeam.cshtml"
        
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\TransientTeam.cshtml"
   Write(Html.Raw(Model.Team.PublicContactDetails));

            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\TransientTeam.cshtml"
                                                  

        if (!string.IsNullOrWhiteSpace(Model.Team.Website))
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>Visit <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2403), Tuple.Create("\"", 2429)
            
            #line 61 "..\..\Views\TransientTeam.cshtml"
, Tuple.Create(Tuple.Create("", 2410), Tuple.Create<System.Object, System.Int32>(Model.Team.Website
            
            #line default
            #line hidden
, 2410), false)
);

WriteLiteral(">");

            
            #line 61 "..\..\Views\TransientTeam.cshtml"
                                              Write(Model.Team.TeamName);

            
            #line default
            #line hidden
WriteLiteral("\'s website</a>.</p>\r\n");

            
            #line 62 "..\..\Views\TransientTeam.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 65 "..\..\Views\TransientTeam.cshtml"
    
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\TransientTeam.cshtml"
     if (Model.Team.ClubMark)
    {
        
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\TransientTeam.cshtml"
   Write(Html.Partial("_ClubMark"));

            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\TransientTeam.cshtml"
                                  
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
