#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/Forms/Emails/Stoolball-England-Email.cshtml")]
    public partial class _Views_Partials_Forms_Emails_Stoolball_England_Email_cshtml : UmbracoViewPage<Umbraco.Forms.Core.Models.FormsHtmlModel>
    {
        public _Views_Partials_Forms_Emails_Stoolball_England_Email_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
   
    var form = global::Umbraco.Web.Composing.Current.Factory.GetInstance<Umbraco.Forms.Core.Services.IFormService>().Get(Model.FormId);
    var htmlSanitiser = global::Umbraco.Web.Composing.Current.Factory.GetInstance<Ganss.XSS.IHtmlSanitizer>();
    htmlSanitiser.AllowedTags.Clear();
    htmlSanitiser.AllowedTags.Add("p");
    htmlSanitiser.AllowedTags.Add("h2");
    htmlSanitiser.AllowedTags.Add("strong");
    htmlSanitiser.AllowedTags.Add("em");
    htmlSanitiser.AllowedTags.Add("ul");
    htmlSanitiser.AllowedTags.Add("ol");
    htmlSanitiser.AllowedTags.Add("li");
    htmlSanitiser.AllowedTags.Add("a");
    htmlSanitiser.AllowedTags.Add("br");
    htmlSanitiser.AllowedAttributes.Clear();
    htmlSanitiser.AllowedAttributes.Add("href");
    htmlSanitiser.AllowedCssProperties.Clear();
    htmlSanitiser.AllowedAtRules.Clear();

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title></title>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"https://fonts.googleapis.com/css?family=Lato:400,700,900\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">

    /* CLIENT-SPECIFIC STYLES */
    body, table, td, a { -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
    table, td { mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
    img { -ms-interpolation-mode: bicubic; }

    /* RESET STYLES */
    img { border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; }
    table { border-collapse: collapse !important; }
    body { height: 100% !important; margin: 0 !important; padding: 0 !important; width: 100% !important; }

    /* iOS BLUE LINKS */
    a[x-apple-data-detectors] {
        color: inherit !important;
        text-decoration: none !important;
        font-size: inherit !important;
        font-family: inherit !important;
        font-weight: inherit !important;
        line-height: inherit !important;
    }

	/* MOBILE STYLES */
	");

WriteLiteral("@media screen and (max-width:600px){\r\n\t\th1 {\r\n\t\t\tfont-size: 32px !important;\r\n\t\t\t" +
"line-height: 32px !important;\r\n\t\t}\r\n\t}\r\n\r\n    /* ANDROID CENTER FIX */\r\n    div[" +
"style*=\"margin: 16px 0;\"] { margin: 0 !important; }\r\n    </style>\r\n</head>\r\n<bod" +
"y");

WriteLiteral(" style=\"background-color: #f4f4f4; margin: 0 !important; padding: 0 !important;\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" border=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" style=\"margin-bottom: 40px;\"");

WriteLiteral(">\r\n        <!-- HEADER -->\r\n        <tr>\r\n            <td");

WriteLiteral(" bgcolor=\"#008000\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(@">
                <!--[if (gte mso 9)|(IE)]>
                    <table align=""center"" border=""0"" cellspacing=""0"" cellpadding=""0"" width=""600"">
                    <tr>
                    <td align=""center"" valign=""top"" width=""600"">
                <![endif]-->
                <table");

WriteLiteral(" border=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" style=\"max-width: 600px;\"");

WriteLiteral(">\r\n                    <tr>\r\n                        <td");

WriteLiteral(" align=\"center\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" style=\"padding: 20px 10px 20px 10px;\"");

WriteLiteral(@">
                        </td>
                    </tr>
                </table>
                <!--[if (gte mso 9)|(IE)]>
                    </td>
                    </tr>
                    </table>
                <![endif]-->
            </td>
        </tr>

        <!-- HERO -->
        <tr>
            <td");

WriteLiteral(" bgcolor=\"#008000\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" style=\"padding: 0px 10px 0px 10px;\"");

WriteLiteral(@">
                <!--[if (gte mso 9)|(IE)]>
                    <table align=""center"" border=""0"" cellspacing=""0"" cellpadding=""0"" width=""600"">
                    <tr>
                    <td align=""center"" valign=""top"" width=""600"">
                <![endif]-->
                <table");

WriteLiteral(" border=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" style=\"max-width: 600px;\"");

WriteLiteral(">\r\n                    <tr>\r\n                        <td");

WriteLiteral(" bgcolor=\"#ffffff\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" style=\"padding: 40px 20px 20px 20px; color: #000000; font-family: \'Lato\', Helvet" +
"ica, Arial, sans-serif; font-size: 36px; font-weight: 900; line-height: 48px;\"");

WriteLiteral(">\r\n                            <h1");

WriteLiteral(" style=\"font-size: 36px; font-weight: 900; margin: 0;\"");

WriteLiteral(">");

            
            #line 97 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                                                                 Write(form.Name);

            
            #line default
            #line hidden
WriteLiteral(@"</h1>
                        </td>
                    </tr>
                </table>
                <!--[if (gte mso 9)|(IE)]>
                    </td>
                    </tr>
                    </table>
                <![endif]-->
            </td>
        </tr>

        <!-- COPY BLOCK -->
        <tr>
            <td");

WriteLiteral(" bgcolor=\"#F3F3F5\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" style=\"padding: 0px 10px 0px 10px;\"");

WriteLiteral(@">
                <!--[if (gte mso 9)|(IE)]>
                    <table align=""center"" border=""0"" cellspacing=""0"" cellpadding=""0"" width=""600"">
                    <tr>
                    <td align=""center"" valign=""top"" width=""600"">
                <![endif]-->
                <table");

WriteLiteral(" border=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" style=\"max-width: 600px;\"");

WriteLiteral(">\r\n\r\n                    <!-- COPY -->\r\n                    <tr>\r\n               " +
"         <td");

WriteLiteral(" bgcolor=\"#ffffff\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" style=\"padding: 20px 30px 20px 30px; color: #303033; font-family: \'Lato\', Helvet" +
"ica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;\"");

WriteLiteral(">\r\n\r\n");

            
            #line 123 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                             foreach (var field in Model.Fields)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <h4");

WriteLiteral(" style=\"font-weight: 700; margin: 20px 0 0; color: #000000;\"");

WriteLiteral(">");

            
            #line 125 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                                                                           Write(field.Name);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n");

            
            #line 126 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"

                                switch (field.FieldType)
                                {
                                    case "FieldType.FileUpload.cshtml":

            
            #line default
            #line hidden
WriteLiteral("                                        <p");

WriteLiteral(" style=\"margin-top: 0;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5831), Tuple.Create("\"", 5922)
            
            #line 130 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
, Tuple.Create(Tuple.Create("", 5838), Tuple.Create<System.Object, System.Int32>(HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority)
            
            #line default
            #line hidden
, 5838), false)
, Tuple.Create(Tuple.Create("", 5904), Tuple.Create("/", 5904), true)
            
            #line 130 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                                              , Tuple.Create(Tuple.Create("", 5905), Tuple.Create<System.Object, System.Int32>(field.GetValue()
            
            #line default
            #line hidden
, 5905), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" style=\"color: #00AEA2;\"");

WriteLiteral(">");

            
            #line 130 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                                                                                                                                                                                    Write(field.GetValue());

            
            #line default
            #line hidden
WriteLiteral("</a></p>\r\n");

            
            #line 131 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                        break;

                                    case "FieldType.DatePicker.cshtml":
                                        DateTime dt;
                                        var fieldValue = field.GetValue();
                                        var dateValid = DateTime.TryParse(fieldValue != null ? fieldValue.ToString() : string.Empty, out dt);
                                        var dateStr = dateValid ? dt.ToString("f") : "";

            
            #line default
            #line hidden
WriteLiteral("                                        <p");

WriteLiteral(" style=\"margin-top: 0;\"");

WriteLiteral(">");

            
            #line 138 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                                             Write(dateStr);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 139 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                        break;

                                    case "FieldType.CheckboxList.cshtml":

            
            #line default
            #line hidden
WriteLiteral("                                        <p");

WriteLiteral(" style=\"margin-top: 0;\"");

WriteLiteral(">\r\n");

            
            #line 143 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 143 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                             foreach (var value in field.GetValues())
                                            {
                                                
            
            #line default
            #line hidden
            
            #line 145 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                           Write(value);

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n");

            
            #line 146 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </p>\r\n");

            
            #line 148 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                        break;
                                    default:
                                        if (field.FieldType == "FieldType.Textarea.cshtml")
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <div");

WriteLiteral(" style=\"margin-top: -20px\"");

WriteLiteral(">");

            
            #line 152 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                                                      Write(Html.Raw(htmlSanitiser.Sanitize(field.GetValue().ToString())));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 153 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <p");

WriteLiteral(" style=\"margin-top: 0;\"");

WriteLiteral(">");

            
            #line 156 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                                                 Write(field.GetValue());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 157 "..\..\Views\Partials\Forms\Emails\Stoolball-England-Email.cshtml"
                                        }
                                        break;
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <p");

WriteLiteral(" style=\"margin-top: 40px; margin-bottom: 0;\"");

WriteLiteral(">Stoolball England</p>\r\n                            <p");

WriteLiteral(" style=\"margin-top: 0; font-size: 14px;\"");

WriteLiteral(">www.stoolball.org.uk</p>\r\n                            <p");

WriteLiteral(" style=\"margin-top: 40px; font-size: 14px;\"");

WriteLiteral(@">Please do not reply to this email. It is sent from an account that is not monitored.</p>
                        </td>
                    </tr>
                </table>
                <!--[if (gte mso 9)|(IE)]>
                    </td>
                    </tr>
                    </table>
                <![endif]-->
            </td>
        </tr>

    </table>
</body>
</html>
");

        }
    }
}
#pragma warning restore 1591
