using System;
using Stoolball.Web.Routing;
using Xunit;

namespace Stoolball.Web.Tests.Routing
{
    public class StoolballRouteContentFinderTests
    {
        [Theory]
        [InlineData("https://example.org/teams", StoolballRouteType.Teams)]
        [InlineData("https://example.org/teams/", StoolballRouteType.Teams)]
        [InlineData("https://example.org/teams/add", StoolballRouteType.CreateTeam)]
        [InlineData("https://example.org/teams/Add/", StoolballRouteType.CreateTeam)]
        [InlineData("https://example.org/teams/map", StoolballRouteType.TeamsMap)]
        [InlineData("https://example.org/teams/MAP/", StoolballRouteType.TeamsMap)]
        [InlineData("https://example.org/teams/example123", StoolballRouteType.Team)]
        [InlineData("https://example.org/teams/example123/", StoolballRouteType.Team)]
        [InlineData("https://example.org/teams/example123/EDiT", StoolballRouteType.TeamActions)]
        [InlineData("https://example.org/teams/example123/edit/", StoolballRouteType.TeamActions)]
        [InlineData("https://example.org/teams/example123/EDiT/team", StoolballRouteType.EditTeam)]
        [InlineData("https://example.org/teams/Example123/EDiT/TEAM/", StoolballRouteType.EditTeam)]
        [InlineData("https://example.org/teams/EXAMPLE123/delete", StoolballRouteType.DeleteTeam)]
        [InlineData("https://example.org/teams/example123/DElete/", StoolballRouteType.DeleteTeam)]
        [InlineData("https://example.org/teams/example123/PLAYers", StoolballRouteType.PlayersForTeam)]
        [InlineData("https://example.org/teams/example123/players/", StoolballRouteType.PlayersForTeam)]
        [InlineData("https://example.org/teams/example123/matches", StoolballRouteType.MatchesForTeam)]
        [InlineData("https://example.org/teams/example123/MATCHES/", StoolballRouteType.MatchesForTeam)]
        [InlineData("https://example.org/teams/example123/matches/rss", StoolballRouteType.MatchesRss)]
        [InlineData("https://example.org/teams/example123/matches/ics", StoolballRouteType.MatchesCalendar)]
        [InlineData("https://example.org/teams/example123/StatisticS", StoolballRouteType.TeamStatistics)]
        [InlineData("https://example.org/teams/example123/STATISTICS/", StoolballRouteType.TeamStatistics)]
        [InlineData("https://example.org/teams/example123/StatisticS/Individual-Scores", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/teams/example123/STATISTICS/individual-scores/", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/teams/example123/StatisticS/Most-RUNS", StoolballRouteType.MostRuns)]
        [InlineData("https://example.org/teams/example123/STATISTICS/most-runs/", StoolballRouteType.MostRuns)]
        [InlineData("https://example.org/teams/example123/StatisticS/Most-WICKETS", StoolballRouteType.MostWickets)]
        [InlineData("https://example.org/teams/example123/STATISTICS/most-wickets/", StoolballRouteType.MostWickets)]
        [InlineData("https://example.org/teams/example123/StatisticS/Most-Catches", StoolballRouteType.MostCatches)]
        [InlineData("https://example.org/teams/example123/STATISTICS/most-catches/", StoolballRouteType.MostCatches)]
        [InlineData("https://example.org/teams/example123/StatisticS/Most-RUN-OUts", StoolballRouteType.MostRunOuts)]
        [InlineData("https://example.org/teams/example123/STATISTICS/most-run-OUTS/", StoolballRouteType.MostRunOuts)]
        [InlineData("https://example.org/teams/example123/StatisticS/Batting-Average", StoolballRouteType.BattingAverage)]
        [InlineData("https://example.org/teams/example123/STATISTICS/BaTTING-AVERAGE/", StoolballRouteType.BattingAverage)]
        [InlineData("https://example.org/teams/example123/StatisticS/Batting-Strike-Rate", StoolballRouteType.BattingStrikeRate)]
        [InlineData("https://example.org/teams/example123/STATISTICS/BaTTING-Strike-RATE/", StoolballRouteType.BattingStrikeRate)]
        [InlineData("https://example.org/teams/example123/StatisticS/Bowling-Strike-Rate", StoolballRouteType.BowlingStrikeRate)]
        [InlineData("https://example.org/teams/example123/STATISTICS/BowlING-Strike-RATE/", StoolballRouteType.BowlingStrikeRate)]
        [InlineData("https://example.org/teams/example123/StatisticS/Bowling-Average", StoolballRouteType.BowlingAverage)]
        [InlineData("https://example.org/teams/example123/STATISTICS/BowLiNG-AVERAGE/", StoolballRouteType.BowlingAverage)]
        [InlineData("https://example.org/teams/example123/StatisticS/Economy-Rate", StoolballRouteType.EconomyRate)]
        [InlineData("https://example.org/teams/example123/STATISTICS/ECONOMY-rate/", StoolballRouteType.EconomyRate)]
        [InlineData("https://example.org/teams/example123/StatisticS/Bowling-Figures", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/teams/example123/STATISTICS/bowling-figures/", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/teams/example123/matches/add/training", StoolballRouteType.CreateTrainingSession)]
        [InlineData("https://example.org/teams/example123/MATCHES/Add/Training/", StoolballRouteType.CreateTrainingSession)]
        [InlineData("https://example.org/teams/example123/matches/add/friendly", StoolballRouteType.CreateFriendlyMatch)]
        [InlineData("https://example.org/teams/example123/MATCHES/Add/Friendly/", StoolballRouteType.CreateFriendlyMatch)]
        [InlineData("https://example.org/teams/example123/matches/add/knockout", StoolballRouteType.CreateKnockoutMatch)]
        [InlineData("https://example.org/teams/example123/MATCHES/Add/KnockOut/", StoolballRouteType.CreateKnockoutMatch)]
        [InlineData("https://example.org/teams/example123/matches/add/league", StoolballRouteType.CreateLeagueMatch)]
        [InlineData("https://example.org/teams/example123/MATCHES/Add/League/", StoolballRouteType.CreateLeagueMatch)]
        [InlineData("https://example.org/teams/example123/matches/add/Tournament", StoolballRouteType.CreateTournament)]
        [InlineData("https://example.org/teams/example123/MATCHES/Add/tournament/", StoolballRouteType.CreateTournament)]
        [InlineData("https://example.org/tournaments/example123/teams/example-team", StoolballRouteType.TransientTeam)]
        [InlineData("https://example.org/tournaments/example123/teams/example-team/", StoolballRouteType.TransientTeam)]
        [InlineData("https://example.org/tournaments/example123/teams/example-team/EDIT", StoolballRouteType.EditTransientTeam)]
        [InlineData("https://example.org/tournaments/example123/teams/example-TEAM/edit/", StoolballRouteType.EditTransientTeam)]
        [InlineData("https://example.org/locations", StoolballRouteType.MatchLocations)]
        [InlineData("https://example.org/locations/", StoolballRouteType.MatchLocations)]
        [InlineData("https://example.org/locations/add", StoolballRouteType.CreateMatchLocation)]
        [InlineData("https://example.org/locations/ADD/", StoolballRouteType.CreateMatchLocation)]
        [InlineData("https://example.org/locations/example", StoolballRouteType.MatchLocation)]
        [InlineData("https://example.org/locations/EXAMPLE-location/", StoolballRouteType.MatchLocation)]
        [InlineData("https://example.org/locations/EXAMPLE-location/edit", StoolballRouteType.MatchLocationActions)]
        [InlineData("https://example.org/locations/EXAMPLE-location/edit/location", StoolballRouteType.EditMatchLocation)]
        [InlineData("https://example.org/locations/EXAMPLE-location/EDIT/location/", StoolballRouteType.EditMatchLocation)]
        [InlineData("https://example.org/locations/EXAMPLE-location/delete", StoolballRouteType.DeleteMatchLocation)]
        [InlineData("https://example.org/locations/EXAMPLE-location/matches", StoolballRouteType.MatchesForMatchLocation)]
        [InlineData("https://example.org/locations/EXAMPLE-location/MATCHES/", StoolballRouteType.MatchesForMatchLocation)]
        [InlineData("https://example.org/locations/EXAMPLE-location/matches/rss", StoolballRouteType.MatchesRss)]
        [InlineData("https://example.org/locations/EXAMPLE-location/matches/ICS", StoolballRouteType.MatchesCalendar)]
        [InlineData("https://example.org/locations/EXAMPLE-location/statistics", StoolballRouteType.MatchLocationStatistics)]
        [InlineData("https://example.org/locations/EXAMPLE-location/STATISTICS/", StoolballRouteType.MatchLocationStatistics)]
        [InlineData("https://example.org/locations/EXAMPLE-location/StatisticS/Individual-Scores", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/locations/EXAMPLE-location/STATISTICS/individual-scores/", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/locations/EXAMPLE-location/StatisticS/MOST-RUNS", StoolballRouteType.MostRuns)]
        [InlineData("https://example.org/locations/EXAMPLE-location/STATISTICS/most-runs/", StoolballRouteType.MostRuns)]
        [InlineData("https://example.org/locations/EXAMPLE-location/StatisticS/MOST-WICKETS", StoolballRouteType.MostWickets)]
        [InlineData("https://example.org/locations/EXAMPLE-location/STATISTICS/most-wickets/", StoolballRouteType.MostWickets)]
        [InlineData("https://example.org/locations/EXAMPLE-location/StatisticS/MOST-CATCHES", StoolballRouteType.MostCatches)]
        [InlineData("https://example.org/locations/EXAMPLE-location/STATISTICS/most-catches/", StoolballRouteType.MostCatches)]
        [InlineData("https://example.org/locations/EXAMPLE-location/StatisticS/MOST-RUN-outs", StoolballRouteType.MostRunOuts)]
        [InlineData("https://example.org/locations/EXAMPLE-location/STATISTICS/most-run-OUTs/", StoolballRouteType.MostRunOuts)]
        [InlineData("https://example.org/locations/EXAMPLE-location/StatisticS/batting-average", StoolballRouteType.BattingAverage)]
        [InlineData("https://example.org/locations/EXAMPLE-location/STATISTICS/BATTING-Average/", StoolballRouteType.BattingAverage)]
        [InlineData("https://example.org/locations/EXAMPLE-location/StatisticS/batting-strike-rate", StoolballRouteType.BattingStrikeRate)]
        [InlineData("https://example.org/locations/EXAMPLE-location/STATISTICS/BATTING-STRIKE-RATE/", StoolballRouteType.BattingStrikeRate)]
        [InlineData("https://example.org/locations/EXAMPLE-location/StatisticS/bowling-strike-rate", StoolballRouteType.BowlingStrikeRate)]
        [InlineData("https://example.org/locations/EXAMPLE-location/STATISTICS/BOWLING-STRIKE-RATE/", StoolballRouteType.BowlingStrikeRate)]
        [InlineData("https://example.org/locations/EXAMPLE-location/StatisticS/bowling-average", StoolballRouteType.BowlingAverage)]
        [InlineData("https://example.org/locations/EXAMPLE-location/STATISTICS/BOWLING-Average/", StoolballRouteType.BowlingAverage)]
        [InlineData("https://example.org/locations/EXAMPLE-location/StatisticS/economy-rate", StoolballRouteType.EconomyRate)]
        [InlineData("https://example.org/locations/EXAMPLE-location/STATISTICS/ECONOMY-Rate/", StoolballRouteType.EconomyRate)]
        [InlineData("https://example.org/locations/EXAMPLE-location/StatisticS/Bowling-Figures", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/locations/EXAMPLE-location/STATISTICS/bowling-figures/", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/clubs/example-name/", StoolballRouteType.Club)]
        [InlineData("https://example.org/clubs/example-name/edit", StoolballRouteType.ClubActions)]
        [InlineData("https://example.org/clubs/example-name/EDit/", StoolballRouteType.ClubActions)]
        [InlineData("https://example.org/clubs/example-name/edit/club", StoolballRouteType.EditClub)]
        [InlineData("https://example.org/clubs/example-name/EDit/CLUB/", StoolballRouteType.EditClub)]
        [InlineData("https://example.org/clubs/example-name/delete", StoolballRouteType.DeleteClub)]
        [InlineData("https://example.org/clubs/example-naME/DELete/", StoolballRouteType.DeleteClub)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/matches", StoolballRouteType.MatchesForClub)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/matches/ics", StoolballRouteType.MatchesCalendar)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/MATCHES/", StoolballRouteType.MatchesForClub)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/MATCHES/rss", StoolballRouteType.MatchesRss)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/statistics", StoolballRouteType.ClubStatistics)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/STATISTICS/", StoolballRouteType.ClubStatistics)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/StatisticS/Individual-Scores", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/STATISTICS/individual-scores/", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/StatisticS/most-runs", StoolballRouteType.MostRuns)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/STATISTICS/Most-Runs/", StoolballRouteType.MostRuns)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/StatisticS/most-Wickets", StoolballRouteType.MostWickets)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/STATISTICS/Most-WICKetS/", StoolballRouteType.MostWickets)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/StatisticS/most-catches", StoolballRouteType.MostCatches)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/STATISTICS/Most-Catches/", StoolballRouteType.MostCatches)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/StatisticS/most-run-outs", StoolballRouteType.MostRunOuts)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/STATISTICS/Most-Run-OUTs/", StoolballRouteType.MostRunOuts)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/StatisticS/Batting-Average", StoolballRouteType.BattingAverage)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/STATISTICS/BATTING-AVERAGE/", StoolballRouteType.BattingAverage)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/StatisticS/Batting-Strike-Rate", StoolballRouteType.BattingStrikeRate)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/STATISTICS/BATTING-STRIKE-RATE/", StoolballRouteType.BattingStrikeRate)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/StatisticS/Bowling-Strike-Rate", StoolballRouteType.BowlingStrikeRate)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/STATISTICS/BOWLING-STRIKE-RATE/", StoolballRouteType.BowlingStrikeRate)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/StatisticS/Bowling-Average", StoolballRouteType.BowlingAverage)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/STATISTICS/BowlING-AVERAGE/", StoolballRouteType.BowlingAverage)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/StatisticS/economY-Rate", StoolballRouteType.EconomyRate)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/STATISTICS/economy-RATE/", StoolballRouteType.EconomyRate)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/StatisticS/Bowling-Figures", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/clubs/EXAMPLE-club/STATISTICS/bowling-figures/", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/clubs/ADD", StoolballRouteType.CreateClub)]
        [InlineData("https://example.org/clubs/add/", StoolballRouteType.CreateClub)]
        [InlineData("https://example.org/CLUBS/EXAMPLE", StoolballRouteType.Club)]
        [InlineData("https://example.org/competitions", StoolballRouteType.Competitions)]
        [InlineData("https://example.org/COMPETITIONS/", StoolballRouteType.Competitions)]
        [InlineData("https://example.org/competitions/add", StoolballRouteType.CreateCompetition)]
        [InlineData("https://example.org/COMPETITIONS/add/", StoolballRouteType.CreateCompetition)]
        [InlineData("https://example.org/competitions/example", StoolballRouteType.Competition)]
        [InlineData("https://example.org/competitions/example/", StoolballRouteType.Competition)]
        [InlineData("https://example.org/competitions/example/matches/ICS", StoolballRouteType.MatchesCalendar)]
        [InlineData("https://example.org/competitions/example/Statistics", StoolballRouteType.CompetitionStatistics)]
        [InlineData("https://example.org/competitions/example/STATISTICS", StoolballRouteType.CompetitionStatistics)]
        [InlineData("https://example.org/competitions/example/Statistics/Individual-Scores", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/competitions/example/STATISTICS/INDIVIDUAL-SCores/", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/competitions/example/Statistics/Most-Runs", StoolballRouteType.MostRuns)]
        [InlineData("https://example.org/competitions/example/STATISTICS/MOst-RUNS/", StoolballRouteType.MostRuns)]
        [InlineData("https://example.org/competitions/example/Statistics/Most-Wickets", StoolballRouteType.MostWickets)]
        [InlineData("https://example.org/competitions/example/STATISTICS/MOst-WICKETS/", StoolballRouteType.MostWickets)]
        [InlineData("https://example.org/competitions/example/Statistics/Most-Catches", StoolballRouteType.MostCatches)]
        [InlineData("https://example.org/competitions/example/STATISTICS/MOst-CATCHES/", StoolballRouteType.MostCatches)]
        [InlineData("https://example.org/competitions/example/Statistics/Most-Run-outs", StoolballRouteType.MostRunOuts)]
        [InlineData("https://example.org/competitions/example/STATISTICS/MOst-RUN-OUTs/", StoolballRouteType.MostRunOuts)]
        [InlineData("https://example.org/competitions/example/Statistics/Batting-Average", StoolballRouteType.BattingAverage)]
        [InlineData("https://example.org/competitions/example/STATISTICS/BaTtIng-Average/", StoolballRouteType.BattingAverage)]
        [InlineData("https://example.org/competitions/example/Statistics/Batting-StriKE-RATE", StoolballRouteType.BattingStrikeRate)]
        [InlineData("https://example.org/competitions/example/STATISTICS/BaTtIng-STRIKE-rate/", StoolballRouteType.BattingStrikeRate)]
        [InlineData("https://example.org/competitions/example/Statistics/BoWlInG-StriKE-RATE", StoolballRouteType.BowlingStrikeRate)]
        [InlineData("https://example.org/competitions/example/STATISTICS/BowlIng-STRIKE-rate/", StoolballRouteType.BowlingStrikeRate)]
        [InlineData("https://example.org/competitions/example/Statistics/Bowling-Average", StoolballRouteType.BowlingAverage)]
        [InlineData("https://example.org/competitions/example/STATISTICS/BoWlInG-Average/", StoolballRouteType.BowlingAverage)]
        [InlineData("https://example.org/competitions/example/Statistics/eConOmy-Rate", StoolballRouteType.EconomyRate)]
        [InlineData("https://example.org/competitions/example/STATISTICS/ECONOMY-RATE/", StoolballRouteType.EconomyRate)]
        [InlineData("https://example.org/competitions/example/Statistics/BOWLING-FIGURES", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/competitions/example/STATISTICS/bowling-figures/", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/competitions/example/Add", StoolballRouteType.CreateSeason)]
        [InlineData("https://example.org/competitions/example/ADD/", StoolballRouteType.CreateSeason)]
        [InlineData("https://example.org/competitions/example/EDIT", StoolballRouteType.CompetitionActions)]
        [InlineData("https://example.org/competitions/example/edit/", StoolballRouteType.CompetitionActions)]
        [InlineData("https://example.org/competitions/example/EDIT/competition", StoolballRouteType.EditCompetition)]
        [InlineData("https://example.org/competitions/example/edit/COMPETITION", StoolballRouteType.EditCompetition)]
        [InlineData("https://example.org/competitions/EXAMPLE/DELETE", StoolballRouteType.DeleteCompetition)]
        [InlineData("https://example.org/competitions/example/delete/", StoolballRouteType.DeleteCompetition)]
        [InlineData("https://example.org/competitions/example/mAtChEs/rss", StoolballRouteType.MatchesRss)]
        [InlineData("https://example.org/competitions/example/2020", StoolballRouteType.Season)]
        [InlineData("https://example.org/competitions/example/2020/", StoolballRouteType.Season)]
        [InlineData("https://example.org/competitions/example/2020/statistics", StoolballRouteType.SeasonStatistics)]
        [InlineData("https://example.org/competitions/example/2020/Statistics/", StoolballRouteType.SeasonStatistics)]
        [InlineData("https://example.org/competitions/example/2020-21/STATISTICS", StoolballRouteType.SeasonStatistics)]
        [InlineData("https://example.org/competitions/example/2020-21/StAtIsTiCs/", StoolballRouteType.SeasonStatistics)]
        [InlineData("https://example.org/competitions/example/2020/statistics/Individual-scores", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/competitions/example/2020/Statistics/InDividUAL-SCORES/", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/competitions/example/2020-21/STATISTICS/individual-scores", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/competitions/example/2020-21/StAtIsTiCs/INDIVIDUAL-SCORES/", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/competitions/example/2020/statistics/most-runs", StoolballRouteType.MostRuns)]
        [InlineData("https://example.org/competitions/example/2020/Statistics/Most-Runs/", StoolballRouteType.MostRuns)]
        [InlineData("https://example.org/competitions/example/2020/statistics/most-wickets", StoolballRouteType.MostWickets)]
        [InlineData("https://example.org/competitions/example/2020/Statistics/Most-Wickets/", StoolballRouteType.MostWickets)]
        [InlineData("https://example.org/competitions/example/2020/statistics/most-catches", StoolballRouteType.MostCatches)]
        [InlineData("https://example.org/competitions/example/2020/Statistics/Most-catches/", StoolballRouteType.MostCatches)]
        [InlineData("https://example.org/competitions/example/2020/statistics/most-run-OUTs", StoolballRouteType.MostRunOuts)]
        [InlineData("https://example.org/competitions/example/2020/Statistics/Most-Run-OUTS/", StoolballRouteType.MostRunOuts)]
        [InlineData("https://example.org/competitions/example/2020/statistics/batting-average", StoolballRouteType.BattingAverage)]
        [InlineData("https://example.org/competitions/example/2020/Statistics/Batting-AVERAGE/", StoolballRouteType.BattingAverage)]
        [InlineData("https://example.org/competitions/example/2020/statistics/batting-strike-rate", StoolballRouteType.BattingStrikeRate)]
        [InlineData("https://example.org/competitions/example/2020/Statistics/Batting-STRIKE-RATE/", StoolballRouteType.BattingStrikeRate)]
        [InlineData("https://example.org/competitions/example/2020/statistics/bowling-strike-rate", StoolballRouteType.BowlingStrikeRate)]
        [InlineData("https://example.org/competitions/example/2020/Statistics/Bowling-STRIKE-RATE/", StoolballRouteType.BowlingStrikeRate)]
        [InlineData("https://example.org/competitions/example/2020/statistics/bowling-average", StoolballRouteType.BowlingAverage)]
        [InlineData("https://example.org/competitions/example/2020/Statistics/Bowling-AVERAGE/", StoolballRouteType.BowlingAverage)]
        [InlineData("https://example.org/competitions/example/2020/statistics/economy-rate", StoolballRouteType.EconomyRate)]
        [InlineData("https://example.org/competitions/example/2020/Statistics/economy-Rate/", StoolballRouteType.EconomyRate)]
        [InlineData("https://example.org/competitions/example/2020/statistics/Bowling-Figures", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/competitions/example/2020/Statistics/BowLING-figureS/", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/competitions/example/2020-21/STATISTICS/most-runs", StoolballRouteType.MostRuns)]
        [InlineData("https://example.org/competitions/example/2020-21/StAtIsTiCs/Most-RUNS/", StoolballRouteType.MostRuns)]
        [InlineData("https://example.org/competitions/example/2020-21/STATISTICS/most-wickets", StoolballRouteType.MostWickets)]
        [InlineData("https://example.org/competitions/example/2020-21/StAtIsTiCs/Most-WICKETS/", StoolballRouteType.MostWickets)]
        [InlineData("https://example.org/competitions/example/2020-21/STATISTICS/most-catches", StoolballRouteType.MostCatches)]
        [InlineData("https://example.org/competitions/example/2020-21/StAtIsTiCs/Most-CATCHES/", StoolballRouteType.MostCatches)]
        [InlineData("https://example.org/competitions/example/2020-21/STATISTICS/most-run-outs", StoolballRouteType.MostRunOuts)]
        [InlineData("https://example.org/competitions/example/2020-21/StAtIsTiCs/Most-RUN-OUTS/", StoolballRouteType.MostRunOuts)]
        [InlineData("https://example.org/competitions/example/2020-21/STATISTICS/batting-average", StoolballRouteType.BattingAverage)]
        [InlineData("https://example.org/competitions/example/2020-21/StAtIsTiCs/BATTING-AVERAGE/", StoolballRouteType.BattingAverage)]
        [InlineData("https://example.org/competitions/example/2020-21/STATISTICS/batting-STRIKE-RATE", StoolballRouteType.BattingStrikeRate)]
        [InlineData("https://example.org/competitions/example/2020-21/StAtIsTiCs/BATTING-strike-rate/", StoolballRouteType.BattingStrikeRate)]
        [InlineData("https://example.org/competitions/example/2020-21/STATISTICS/bowling-STRIKE-RATE", StoolballRouteType.BowlingStrikeRate)]
        [InlineData("https://example.org/competitions/example/2020-21/StAtIsTiCs/BOWLING-strike-rate/", StoolballRouteType.BowlingStrikeRate)]
        [InlineData("https://example.org/competitions/example/2020-21/STATISTICS/bowling-average", StoolballRouteType.BowlingAverage)]
        [InlineData("https://example.org/competitions/example/2020-21/StAtIsTiCs/BOWLING-AVERAGE/", StoolballRouteType.BowlingAverage)]
        [InlineData("https://example.org/competitions/example/2020-21/STATISTICS/Economy-Rate", StoolballRouteType.EconomyRate)]
        [InlineData("https://example.org/competitions/example/2020-21/StAtIsTiCs/economy-rate/", StoolballRouteType.EconomyRate)]
        [InlineData("https://example.org/competitions/example/2020-21/STATISTICS/Bowling-figures", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/competitions/example/2020-21/StAtIsTiCs/Bowling-FIGURES/", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/competitions/example/2020/matches", StoolballRouteType.MatchesForSeason)]
        [InlineData("https://example.org/competitions/example/2020/MATCHES/", StoolballRouteType.MatchesForSeason)]
        [InlineData("https://example.org/competitions/example/2020-21/MATCHES", StoolballRouteType.MatchesForSeason)]
        [InlineData("https://example.org/competitions/example/2020-21/mAtChEs/", StoolballRouteType.MatchesForSeason)]
        [InlineData("https://example.org/competitions/example/2020/matches/ADD/training", StoolballRouteType.CreateTrainingSession)]
        [InlineData("https://example.org/competitions/example/2020/MATCHES/add/Training/", StoolballRouteType.CreateTrainingSession)]
        [InlineData("https://example.org/competitions/example/2020/matches/ADD/friendly", StoolballRouteType.CreateFriendlyMatch)]
        [InlineData("https://example.org/competitions/example/2020/MATCHES/add/Friendly/", StoolballRouteType.CreateFriendlyMatch)]
        [InlineData("https://example.org/competitions/example/2020/matches/ADD/league", StoolballRouteType.CreateLeagueMatch)]
        [InlineData("https://example.org/competitions/example/2020/MATCHES/add/League/", StoolballRouteType.CreateLeagueMatch)]
        [InlineData("https://example.org/competitions/example/2020-21/MATCHES/add/TRAINING", StoolballRouteType.CreateTrainingSession)]
        [InlineData("https://example.org/competitions/example/2020-21/mAtChEs/Add/trainING/", StoolballRouteType.CreateTrainingSession)]
        [InlineData("https://example.org/competitions/example/2020-21/MATCHES/add/friendly", StoolballRouteType.CreateFriendlyMatch)]
        [InlineData("https://example.org/competitions/example/2020-21/mAtChEs/Add/Friendly/", StoolballRouteType.CreateFriendlyMatch)]
        [InlineData("https://example.org/competitions/example/2020-21/MATCHES/add/league", StoolballRouteType.CreateLeagueMatch)]
        [InlineData("https://example.org/competitions/example/2020-21/mAtChEs/Add/League/", StoolballRouteType.CreateLeagueMatch)]
        [InlineData("https://example.org/competitions/example/2020/matches/ADD/knockout", StoolballRouteType.CreateKnockoutMatch)]
        [InlineData("https://example.org/competitions/example/2020/MATCHES/add/KnockOut/", StoolballRouteType.CreateKnockoutMatch)]
        [InlineData("https://example.org/competitions/example/2020-21/MATCHES/add/knockout", StoolballRouteType.CreateKnockoutMatch)]
        [InlineData("https://example.org/competitions/example/2020-21/mAtChEs/Add/Knockout/", StoolballRouteType.CreateKnockoutMatch)]
        [InlineData("https://example.org/competitions/example/2020/map", StoolballRouteType.SeasonMap)]
        [InlineData("https://example.org/competitions/example/2020/Map/", StoolballRouteType.SeasonMap)]
        [InlineData("https://example.org/competitions/example/2020-21/MAP", StoolballRouteType.SeasonMap)]
        [InlineData("https://example.org/competitions/EXAMPLE/2020-21/maP/", StoolballRouteType.SeasonMap)]
        [InlineData("https://example.org/competitions/example/2020/table", StoolballRouteType.SeasonResultsTable)]
        [InlineData("https://example.org/competitions/example/2020/Table/", StoolballRouteType.SeasonResultsTable)]
        [InlineData("https://example.org/competitions/example/2020-21/table", StoolballRouteType.SeasonResultsTable)]
        [InlineData("https://example.org/competitions/EXAMPLE/2020-21/Table/", StoolballRouteType.SeasonResultsTable)]
        [InlineData("https://example.org/competitions/example/2020/edit", StoolballRouteType.SeasonActions)]
        [InlineData("https://example.org/competitions/EXAMPLE/2020/EDIT/", StoolballRouteType.SeasonActions)]
        [InlineData("https://example.org/competitions/example/2020-21/edit", StoolballRouteType.SeasonActions)]
        [InlineData("https://example.org/competitions/EXAMPLE/2020-21/EDIT/", StoolballRouteType.SeasonActions)]
        [InlineData("https://example.org/competitions/example/2020/edit/season", StoolballRouteType.EditSeason)]
        [InlineData("https://example.org/competitions/EXAMPLE/2020/EDIT/SEASON/", StoolballRouteType.EditSeason)]
        [InlineData("https://example.org/competitions/example/2020-21/edit/season", StoolballRouteType.EditSeason)]
        [InlineData("https://example.org/competitions/EXAMPLE/2020-21/EDIT/Season/", StoolballRouteType.EditSeason)]
        [InlineData("https://example.org/competitions/example/2020/edit/table", StoolballRouteType.EditSeasonResultsTable)]
        [InlineData("https://example.org/competitions/EXAMPLE/2020/EDIT/Table/", StoolballRouteType.EditSeasonResultsTable)]
        [InlineData("https://example.org/competitions/example/2020-21/edit/table", StoolballRouteType.EditSeasonResultsTable)]
        [InlineData("https://example.org/competitions/EXAMPLE/2020-21/EDIT/Table/", StoolballRouteType.EditSeasonResultsTable)]
        [InlineData("https://example.org/competitions/example/2020/edit/teams", StoolballRouteType.EditSeasonTeams)]
        [InlineData("https://example.org/competitions/EXAMPLE/2020/EDIT/Teams/", StoolballRouteType.EditSeasonTeams)]
        [InlineData("https://example.org/competitions/example/2020-21/edit/TEAMS", StoolballRouteType.EditSeasonTeams)]
        [InlineData("https://example.org/competitions/EXAMPLE/2020-21/EDIT/teams/", StoolballRouteType.EditSeasonTeams)]
        [InlineData("https://example.org/competitions/example/2020/delete", StoolballRouteType.DeleteSeason)]
        [InlineData("https://example.org/competitions/EXAMPLE/2020/Delete/", StoolballRouteType.DeleteSeason)]
        [InlineData("https://example.org/competitions/example/2020-21/Delete", StoolballRouteType.DeleteSeason)]
        [InlineData("https://example.org/competitions/EXAMPLE/2020-21/DELETE/", StoolballRouteType.DeleteSeason)]
        [InlineData("https://example.org/matches", StoolballRouteType.Matches)]
        [InlineData("https://example.org/matches/", StoolballRouteType.Matches)]
        [InlineData("https://example.org/matches/example-match", StoolballRouteType.Match)]
        [InlineData("https://example.org/matches/example-MaTcH/", StoolballRouteType.Match)]
        [InlineData("https://example.org/matches/example-MaTcH/ICS", StoolballRouteType.MatchesCalendar)]
        [InlineData("https://example.org/matches/example-match/edit", StoolballRouteType.MatchActions)]
        [InlineData("https://example.org/matches/example-MaTcH/Edit/", StoolballRouteType.MatchActions)]
        [InlineData("https://example.org/matches/example-match/edit/friendly", StoolballRouteType.EditFriendlyMatch)]
        [InlineData("https://example.org/matches/example-MaTcH/Edit/Friendly/", StoolballRouteType.EditFriendlyMatch)]
        [InlineData("https://example.org/matches/example-match/edit/League", StoolballRouteType.EditLeagueMatch)]
        [InlineData("https://example.org/matches/example-MaTcH/Edit/league/", StoolballRouteType.EditLeagueMatch)]
        [InlineData("https://example.org/matches/example-match/edit/knockout", StoolballRouteType.EditKnockoutMatch)]
        [InlineData("https://example.org/matches/example-MaTcH/Edit/KnockOut/", StoolballRouteType.EditKnockoutMatch)]
        [InlineData("https://example.org/matches/example-match/edit/Format", StoolballRouteType.EditMatchFormat)]
        [InlineData("https://example.org/matches/example-MaTcH/Edit/format/", StoolballRouteType.EditMatchFormat)]
        [InlineData("https://example.org/matches/example-match/edit/Training", StoolballRouteType.EditTrainingSession)]
        [InlineData("https://example.org/matches/example-MaTcH/Edit/training/", StoolballRouteType.EditTrainingSession)]
        [InlineData("https://example.org/matches/example-match/edit/start-of-play", StoolballRouteType.EditStartOfPlay)]
        [InlineData("https://example.org/matches/example-MaTcH/Edit/Start-Of-Play/", StoolballRouteType.EditStartOfPlay)]
        [InlineData("https://example.org/matches/example-match/edit/innings/1/BATTING", StoolballRouteType.EditBattingScorecard)]
        [InlineData("https://example.org/matches/example-MaTcH/Edit/Innings/18/batting/", StoolballRouteType.EditBattingScorecard)]
        [InlineData("https://example.org/matches/example-match/edit/innings/1/bowling", StoolballRouteType.EditBowlingScorecard)]
        [InlineData("https://example.org/matches/example-MaTcH/Edit/Innings/18/Bowling/", StoolballRouteType.EditBowlingScorecard)]
        [InlineData("https://example.org/matches/example-match/edit/close-of-play", StoolballRouteType.EditCloseOfPlay)]
        [InlineData("https://example.org/matches/example-MaTcH/Edit/close-Of-Play/", StoolballRouteType.EditCloseOfPlay)]
        [InlineData("https://example.org/matches/example-match/delete", StoolballRouteType.DeleteMatch)]
        [InlineData("https://example.org/matches/example-MaTcH/DELETE/", StoolballRouteType.DeleteMatch)]
        [InlineData("https://example.org/matches/rss", StoolballRouteType.MatchesRss)]
        [InlineData("https://example.org/matches/ics", StoolballRouteType.MatchesCalendar)]
        [InlineData("https://example.org/tournaments/ics", StoolballRouteType.MatchesCalendar)]
        [InlineData("https://example.org/tournaments/junior/calendar/ics", StoolballRouteType.MatchesCalendar)]
        [InlineData("https://example.org/tournaments", StoolballRouteType.Tournaments)]
        [InlineData("https://example.org/tournaments/", StoolballRouteType.Tournaments)]
        [InlineData("https://example.org/tournaments/rss", StoolballRouteType.TournamentsRss)]
        [InlineData("https://example.org/tournaments/all/rss", StoolballRouteType.TournamentsRss)]
        [InlineData("https://example.org/tournaments/example-tournament/", StoolballRouteType.Tournament)]
        [InlineData("https://example.org/tournaments/123-TOURNAMENT/", StoolballRouteType.Tournament)]
        [InlineData("https://example.org/tournaments/123-TOURNAMENT/ics", StoolballRouteType.MatchesCalendar)]
        [InlineData("https://example.org/tournaments/example-tournament/Edit", StoolballRouteType.TournamentActions)]
        [InlineData("https://example.org/tournaments/123-TOURNAMENT/edit/", StoolballRouteType.TournamentActions)]
        [InlineData("https://example.org/tournaments/example-tournament/Edit/Tournament", StoolballRouteType.EditTournament)]
        [InlineData("https://example.org/tournaments/123-TOURNAMENT/edit/tournament/", StoolballRouteType.EditTournament)]
        [InlineData("https://example.org/tournaments/example-tournament/Edit/Matches", StoolballRouteType.EditTournamentMatches)]
        [InlineData("https://example.org/tournaments/123-TOURNAMENT/edit/MATCHES/", StoolballRouteType.EditTournamentMatches)]
        [InlineData("https://example.org/tournaments/example-tournament/Edit/Teams", StoolballRouteType.EditTournamentTeams)]
        [InlineData("https://example.org/tournaments/123-TOURNAMENT/edit/teams/", StoolballRouteType.EditTournamentTeams)]
        [InlineData("https://example.org/tournaments/example-tournament/Edit/Seasons", StoolballRouteType.EditTournamentSeasons)]
        [InlineData("https://example.org/tournaments/123-TOURNAMENT/edit/seasons/", StoolballRouteType.EditTournamentSeasons)]
        [InlineData("https://example.org/tournaments/example-tournament/delete", StoolballRouteType.DeleteTournament)]
        [InlineData("https://example.org/tournaments/123-TOURNAMENT/delete/", StoolballRouteType.DeleteTournament)]
        [InlineData("https://example.org/play/statistics", StoolballRouteType.Statistics)]
        [InlineData("https://example.org/PLAY/Statistics/", StoolballRouteType.Statistics)]
        [InlineData("https://example.org/play/statistics/edit", StoolballRouteType.EditStatistics)]
        [InlineData("https://example.org/play/statistics/EDIT/", StoolballRouteType.EditStatistics)]
        [InlineData("https://example.org/play/statistics/individual-scores", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/play/statistics/Individual-Scores/", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/play/statistics/bowling-figures", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/play/statistics/Bowling-FIgures/", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/play/statistics/most-runs", StoolballRouteType.MostRuns)]
        [InlineData("https://example.org/play/statistics/Most-Runs/", StoolballRouteType.MostRuns)]
        [InlineData("https://example.org/play/statistics/most-WickeTs", StoolballRouteType.MostWickets)]
        [InlineData("https://example.org/play/statistics/Most-WICKEts/", StoolballRouteType.MostWickets)]
        [InlineData("https://example.org/play/statistics/most-catches", StoolballRouteType.MostCatches)]
        [InlineData("https://example.org/play/statistics/Most-Catches/", StoolballRouteType.MostCatches)]
        [InlineData("https://example.org/play/statistics/most-run-outs", StoolballRouteType.MostRunOuts)]
        [InlineData("https://example.org/play/statistics/Most-Run-OUTs/", StoolballRouteType.MostRunOuts)]
        [InlineData("https://example.org/play/statistics/batting-AVERAGE", StoolballRouteType.BattingAverage)]
        [InlineData("https://example.org/play/statistics/Batting-Average/", StoolballRouteType.BattingAverage)]
        [InlineData("https://example.org/play/statistics/batting-Strike-Rate", StoolballRouteType.BattingStrikeRate)]
        [InlineData("https://example.org/play/statistics/Batting-Strike-rate/", StoolballRouteType.BattingStrikeRate)]
        [InlineData("https://example.org/play/statistics/bowling-Strike-Rate", StoolballRouteType.BowlingStrikeRate)]
        [InlineData("https://example.org/play/statistics/Bowling-Strike-rate/", StoolballRouteType.BowlingStrikeRate)]
        [InlineData("https://example.org/play/statistics/bowling-AVERAGE", StoolballRouteType.BowlingAverage)]
        [InlineData("https://example.org/play/statistics/Bowling-Average/", StoolballRouteType.BowlingAverage)]
        [InlineData("https://example.org/play/statistics/economy-Rate", StoolballRouteType.EconomyRate)]
        [InlineData("https://example.org/play/statistics/Economy-Rate/", StoolballRouteType.EconomyRate)]
        [InlineData("https://example.org/players/example-name/individual-scores", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/players/example-NAME/Individual-Scores/", StoolballRouteType.IndividualScores)]
        [InlineData("https://example.org/players/example-name/bowling-figures", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/players/example-NAME/Bowling-Figures/", StoolballRouteType.BowlingFigures)]
        [InlineData("https://example.org/players/example-name/bowling", StoolballRouteType.PlayerBowling)]
        [InlineData("https://example.org/players/example-NAME/Bowling/", StoolballRouteType.PlayerBowling)]
        [InlineData("https://example.org/players/example-name/fielding", StoolballRouteType.PlayerFielding)]
        [InlineData("https://example.org/players/example-NAME/FIEldIng/", StoolballRouteType.PlayerFielding)]
        [InlineData("https://example.org/players/example-name/CATCHES", StoolballRouteType.Catches)]
        [InlineData("https://example.org/players/example-NAME/catches/", StoolballRouteType.Catches)]
        [InlineData("https://example.org/players/example-name/run-outs", StoolballRouteType.RunOuts)]
        [InlineData("https://example.org/players/example-NAME/RUN-OUts/", StoolballRouteType.RunOuts)]
        [InlineData("https://example.org/players/example-name/", StoolballRouteType.Player)]
        [InlineData("https://example.org/players/example-NAME", StoolballRouteType.Player)]
        public void Correct_route_should_match(string route, StoolballRouteType expectedType)
        {
            var requestUrl = new Uri(route);

            var result = StoolballRouteContentFinder.MatchStoolballRouteType(requestUrl);

            Assert.Equal(expectedType, result);
        }

        [Theory]
        [InlineData("https://example.org/clubs")]
        [InlineData("https://example.org/clubs/")]
        [InlineData("https://example.org/clubs/example/invalid")]
        [InlineData("https://example.org/teams/example/invalid")]
        [InlineData("https://example.org/teams/example123/teams/example-team/")]
        [InlineData("https://example.org/teams/example123/individualscores/")]
        [InlineData("https://example.org/teams/example123/individual-scores/")]
        [InlineData("https://example.org/tournaments/example123/invalid/example-team/")]
        [InlineData("https://example.org/competitions/example/2020-")]
        [InlineData("https://example.org/competitions/example/2020/invalid")]
        [InlineData("https://example.org/competitions/example/2020-21/invalid/")]
        [InlineData("https://example.org/matches/example-match/edit/innings/one/bowling")]
        [InlineData("https://example.org/matches/example-match/edit/innings/1a/bowling")]
        [InlineData("https://example.org/matches/example-match/edit/innings/1/invalid/")]
        [InlineData("https://example.org/tournaments/invalid/rss")]
        [InlineData("https://example.org/tournaments/invalid/calendar/ics")]
        [InlineData("https://example.org/other")]
        [InlineData("https://example.org/other/")]
        public void Other_route_should_not_match(string route)
        {
            var requestUrl = new Uri(route);

            var result = StoolballRouteContentFinder.MatchStoolballRouteType(requestUrl);

            Assert.Null(result);
        }
    }
}
