#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    
    #line 2 "..\..\Views\Partials\_Breadcrumb.cshtml"
    using Stoolball.Navigation;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/_Breadcrumb.cshtml")]
    public partial class _Views_Partials__Breadcrumb_cshtml : System.Web.Mvc.WebViewPage<List<Breadcrumb>>
    {
        public _Views_Partials__Breadcrumb_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Partials\_Breadcrumb.cshtml"
 if (Model != null && Model.Count > 1)
{

            
            #line default
            #line hidden
WriteLiteral("    <nav");

WriteLiteral(" aria-label=\"Breadcrumb\"");

WriteLiteral(" class=\"container-xl print__no-urls\"");

WriteLiteral(">\r\n        <ol");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n");

            
            #line 7 "..\..\Views\Partials\_Breadcrumb.cshtml"
            
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\Partials\_Breadcrumb.cshtml"
             for (var i = 0; i < Model.Count; i++)
            {
                if (i < Model.Count - 1)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li");

WriteLiteral(" class=\"breadcrumb-item\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 380), Tuple.Create("\"", 400)
            
            #line 11 "..\..\Views\Partials\_Breadcrumb.cshtml"
, Tuple.Create(Tuple.Create("", 387), Tuple.Create<System.Object, System.Int32>(Model[i].Url
            
            #line default
            #line hidden
, 387), false)
);

WriteLiteral(">");

            
            #line 11 "..\..\Views\Partials\_Breadcrumb.cshtml"
                                                                   Write(Model[i].Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 12 "..\..\Views\Partials\_Breadcrumb.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li");

WriteLiteral(" class=\"breadcrumb-item\"");

WriteLiteral(" aria-current=\"location\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 561), Tuple.Create("\"", 581)
            
            #line 15 "..\..\Views\Partials\_Breadcrumb.cshtml"
  , Tuple.Create(Tuple.Create("", 568), Tuple.Create<System.Object, System.Int32>(Model[i].Url
            
            #line default
            #line hidden
, 568), false)
);

WriteLiteral(">");

            
            #line 15 "..\..\Views\Partials\_Breadcrumb.cshtml"
                                                                                           Write(Model[i].Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 16 "..\..\Views\Partials\_Breadcrumb.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </ol>\r\n    </nav>\r\n");

            
            #line 20 "..\..\Views\Partials\_Breadcrumb.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
