#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 3 "..\..\Views\Partials\_Filters.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    
    #line 2 "..\..\Views\Partials\_Filters.cshtml"
    using Stoolball.Web.Filtering;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/_Filters.cshtml")]
    public partial class _Views_Partials__Filters_cshtml : System.Web.Mvc.WebViewPage<FilterViewModel>
    {
        public _Views_Partials__Filters_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"filter\"");

WriteLiteral(">\r\n");

            
            #line 5 "..\..\Views\Partials\_Filters.cshtml"
    
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\Partials\_Filters.cshtml"
     if (!string.IsNullOrWhiteSpace(Model.FilterDescription))
    {

            
            #line default
            #line hidden
WriteLiteral("        <p");

WriteLiteral(" class=\"filter__applied\"");

WriteLiteral(">Showing ");

            
            #line 7 "..\..\Views\Partials\_Filters.cshtml"
                                      Write(Model.FilterDescription.ToFirstLower(CultureInfo.CurrentCulture));

            
            #line default
            #line hidden
WriteLiteral(".</p>\r\n");

            
            #line 8 "..\..\Views\Partials\_Filters.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <form");

WriteLiteral(" method=\"get\"");

WriteAttribute("action", Tuple.Create(" action=\"", 321), Tuple.Create("\"", 355)
            
            #line 9 "..\..\Views\Partials\_Filters.cshtml"
, Tuple.Create(Tuple.Create("", 330), Tuple.Create<System.Object, System.Int32>(Request.Url.AbsolutePath
            
            #line default
            #line hidden
, 330), false)
);

WriteLiteral(" class=\"filter__edit d-none\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 11 "..\..\Views\Partials\_Filters.cshtml"
       Write(Html.LabelFor(m => Model.from, Model.FilteredItemTypePlural + " from", new { aria_label = Model.FilteredItemTypeSingular + " date is on or after" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 12 "..\..\Views\Partials\_Filters.cshtml"
       Write(Html.TextBox(nameof(Model.from), Model.from.HasValue ? Model.from.Value.ToString("yyyy-MM-dd") : string.Empty, new { @type = "date", @class = "form-control", aria_describedby = "from-date", data_val_date = "Enter a date in YYYY-MM-DD format." }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 13 "..\..\Views\Partials\_Filters.cshtml"
       Write(Html.ValidationMessageFor(m => Model.from, null, new { id = "from-date" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 14 "..\..\Views\Partials\_Filters.cshtml"
       Write(Html.LabelFor(m => Model.to, "until", new { aria_label = Model.FilteredItemTypeSingular + " date is on or before" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Views\Partials\_Filters.cshtml"
       Write(Html.TextBox(nameof(Model.to), Model.to.HasValue ? Model.to.Value.ToString("yyyy-MM-dd") : string.Empty, new { @type = "date", @class = "form-control", aria_describedby = "to-date", data_val_date = "Enter a date in YYYY-MM-DD format." }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Partials\_Filters.cshtml"
       Write(Html.ValidationMessageFor(m => Model.to, null, new { id = "to-date" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral("><button");

WriteLiteral(" class=\"btn btn-secondary btn-apply-filter\"");

WriteLiteral(">Apply filter</button></div>\r\n    </form>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
