#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    
    #line 2 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
    using Umbraco.Forms.Core.Enums;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
    using Umbraco.Forms.Mvc;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
    using Umbraco.Forms.Mvc.BusinessLogic;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
    using Umbraco.Forms.Mvc.Models;
    
    #line default
    #line hidden
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/Forms/Themes/stoolball/Form.cshtml")]
    public partial class _Views_Partials_Forms_Themes_stoolball_Form_cshtml : WebViewPage<Umbraco.Forms.Web.Models.FormViewModel>
    {
        public _Views_Partials_Forms_Themes_stoolball_Form_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"umbraco-forms-page\"");

WriteLiteral(">\r\n\r\n");

            
            #line 10 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
     if (string.IsNullOrEmpty(Model.CurrentPage.Caption) == false)
    {

            
            #line default
            #line hidden
WriteLiteral("        <h4");

WriteLiteral(" class=\"umbraco-forms-caption\"");

WriteLiteral(">");

            
            #line 12 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                     Write(Model.CurrentPage.Caption);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n");

            
            #line 13 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 15 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
     if (Model.ShowValidationSummary)
    {
        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
   Write(Html.ValidationSummary(false));

            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                      
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 21 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
    
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
     foreach (FieldsetViewModel fs in Model.CurrentPage.Fieldsets)
    {

            
            #line default
            #line hidden
WriteLiteral("        <fieldset");

WriteLiteral(" class=\"umbraco-forms-fieldset\"");

WriteAttribute("id", Tuple.Create(" id=\"", 614), Tuple.Create("\"", 625)
            
            #line 23 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
, Tuple.Create(Tuple.Create("", 619), Tuple.Create<System.Object, System.Int32>(fs.Id
            
            #line default
            #line hidden
, 619), false)
);

WriteLiteral(">\r\n\r\n");

            
            #line 25 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
            
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
             if (string.IsNullOrEmpty(fs.Caption) == false)
            {

            
            #line default
            #line hidden
WriteLiteral("                <legend>");

            
            #line 27 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                   Write(fs.Caption);

            
            #line default
            #line hidden
WriteLiteral("</legend>\r\n");

            
            #line 28 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"row-fluid\"");

WriteLiteral(">\r\n\r\n");

            
            #line 32 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                 foreach (var c in fs.Containers)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 903), Tuple.Create("\"", 957)
, Tuple.Create(Tuple.Create("", 911), Tuple.Create("umbraco-forms-container", 911), true)
            
            #line 34 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
, Tuple.Create(Tuple.Create(" ", 934), Tuple.Create<System.Object, System.Int32>("col-md-" + c.Width
            
            #line default
            #line hidden
, 935), false)
);

WriteLiteral(">\r\n\r\n");

            
            #line 36 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                         foreach (FieldViewModel f in c.Fields)
                        {
                            bool hidden = f.HasCondition && f.ConditionActionType == FieldConditionActionType.Show;


            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 1206), Tuple.Create("\"", 1284)
, Tuple.Create(Tuple.Create("", 1214), Tuple.Create("form-group", 1214), true)
            
            #line 40 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
, Tuple.Create(Tuple.Create(" ", 1224), Tuple.Create<System.Object, System.Int32>(Html.GetFormFieldWrapperClass(f.FieldTypeName)
            
            #line default
            #line hidden
, 1225), false)
            
            #line 40 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                  , Tuple.Create(Tuple.Create(" ", 1272), Tuple.Create<System.Object, System.Int32>(f.CssClass
            
            #line default
            #line hidden
, 1273), false)
);

WriteLiteral(" ");

            
            #line 40 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                                                                                                   if (hidden) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" style=\"display: none\" ");

WriteLiteral("   ");

            
            #line 40 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                                                                                                                                                        } 
            
            #line default
            #line hidden
WriteLiteral(">\r\n\r\n");

            
            #line 42 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                 if (!f.HideLabel)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <label");

WriteAttribute("for", Tuple.Create(" for=\"", 1479), Tuple.Create("\"", 1490)
            
            #line 44 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
, Tuple.Create(Tuple.Create("", 1485), Tuple.Create<System.Object, System.Int32>(f.Id
            
            #line default
            #line hidden
, 1485), false)
);

WriteLiteral(" class=\"umbraco-forms-label\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 45 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                   Write(f.Caption);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 45 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                                    if (f.ShowIndicator)
                                                   {

            
            #line default
            #line hidden
WriteLiteral("                                                       <span");

WriteLiteral(" class=\"umbraco-forms-indicator\"");

WriteLiteral(">");

            
            #line 47 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                                                                        Write(Model.Indicator);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 48 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                                   }

            
            #line default
            #line hidden
WriteLiteral("                                    </label>\r\n");

            
            #line 50 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 52 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                 if (!string.IsNullOrEmpty(f.ToolTip))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <p");

WriteLiteral(" class=\"form-text\"");

WriteLiteral("><small>");

            
            #line 54 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                                           Write(f.ToolTip);

            
            #line default
            #line hidden
WriteLiteral("</small></p>\r\n");

            
            #line 55 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"umbraco-forms-field-wrapper\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                                    ");

            
            #line 59 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                               Write(Html.Partial(FormThemeResolver.GetFieldView(Model, f), f));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 61 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 61 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                     if (Model.ShowFieldValidaton)
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                   Write(Html.ValidationMessage(f.Id));

            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                                                     
                                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n\r\n                            </div>\r\n");

            
            #line 69 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

            
            #line 72 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n\r\n        </fieldset>\r\n");

            
            #line 76 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <input");

WriteLiteral(" type=\"text\"");

WriteAttribute("name", Tuple.Create(" name=\"", 2759), Tuple.Create("\"", 2807)
            
            #line 78 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
, Tuple.Create(Tuple.Create("", 2766), Tuple.Create<System.Object, System.Int32>(Model.FormId.ToString().Replace("-", "")
            
            #line default
            #line hidden
, 2766), false)
);

WriteLiteral(" class=\"umbraco-forms-formid\"");

WriteLiteral(" />\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"umbraco-forms-navigation row-fluid\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

            
            #line 84 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
            
            
            #line default
            #line hidden
            
            #line 84 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
             if (Model.IsMultiPage)
            {
                if (!Model.IsFirstPage)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <input");

WriteLiteral(" class=\"btn \"");

WriteLiteral("\r\n                           type=\"submit\"");

WriteAttribute("value", Tuple.Create("\r\n                           value=\"", 3128), Tuple.Create("\"", 3186)
            
            #line 90 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
, Tuple.Create(Tuple.Create("", 3164), Tuple.Create<System.Object, System.Int32>(Model.PreviousCaption
            
            #line default
            #line hidden
, 3164), false)
);

WriteLiteral("\r\n                           name=\"__prev\"");

WriteLiteral(" />\r\n");

            
            #line 92 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                }

                if (!Model.IsLastPage)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteLiteral(" class=\"btn btn-secondary next\"");

WriteLiteral(" name=\"__next\"");

WriteLiteral(">");

            
            #line 96 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                                                    Write(Model.NextCaption);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 97 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                }

                if (Model.IsLastPage)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" name=\"__next\"");

WriteLiteral(">");

            
            #line 101 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                                             Write(Model.SubmitCaption);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 102 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                }
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <button");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" name=\"__next\"");

WriteLiteral(">");

            
            #line 106 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
                                                         Write(Model.SubmitCaption);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 107 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n\r\n");

            
            #line 112 "..\..\Views\Partials\Forms\Themes\stoolball\Form.cshtml"
Write(Html.Partial("Forms/Themes/default/ScrollToFormScript"));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
