#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
    using ClientDependency.Core.Mvc;
    
    #line default
    #line hidden
    using Examine;
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    
    #line 4 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
    using Umbraco.Forms.Mvc;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
    using Umbraco.Forms.Mvc.BusinessLogic;
    
    #line default
    #line hidden
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/Forms/Themes/stoolball/Render.cshtml")]
    public partial class _Views_Partials_Forms_Themes_stoolball_Render_cshtml : WebViewPage<Umbraco.Forms.Web.Models.FormViewModel>
    {
        public _Views_Partials_Forms_Themes_stoolball_Render_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n\r\n");

            
            #line 13 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
  
    Html.EnableClientValidation(true);
    Html.EnableUnobtrusiveJavaScript(true);

    //Get the actual view to render the form html
    var formThemedView = FormThemeResolver.GetFormView(Model);

    //get the script.cshtml view to render client-side assets
    var formScriptView = FormThemeResolver.GetScriptView(Model);


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 28 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
 if (Model.SubmitHandled)
{
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
Write(Html.Partial(formThemedView));

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
                                 ;

} else {

    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
                                  

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteAttribute("id", Tuple.Create(" id=\"", 1189), Tuple.Create("\"", 1226)
, Tuple.Create(Tuple.Create("", 1194), Tuple.Create("umbraco_form_", 1194), true)
            
            #line 35 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
, Tuple.Create(Tuple.Create("", 1207), Tuple.Create<System.Object, System.Int32>(Model.FormClientId
            
            #line default
            #line hidden
, 1207), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 1227), Tuple.Create("\"", 1296)
, Tuple.Create(Tuple.Create("", 1235), Tuple.Create("umbraco-forms-form", 1235), true)
            
            #line 35 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
, Tuple.Create(Tuple.Create(" ", 1253), Tuple.Create<System.Object, System.Int32>(Model.CssClass
            
            #line default
            #line hidden
, 1254), false)
, Tuple.Create(Tuple.Create(" ", 1269), Tuple.Create("umbraco-forms-", 1270), true)
            
            #line 35 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
                       , Tuple.Create(Tuple.Create("", 1284), Tuple.Create<System.Object, System.Int32>(Model.Theme
            
            #line default
            #line hidden
, 1284), false)
);

WriteLiteral(">\r\n\r\n");

            
            #line 37 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
        
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
         using (Html.BeginUmbracoForm<Umbraco.Forms.Web.Controllers.UmbracoFormsController>("HandleForm"))
        {
            
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
                                         

            
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
                                    

            
            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
       Write(Html.HiddenFor(x => Model.FormId, new {id = (string)null}));

            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
                                                                       
            
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
       Write(Html.HiddenFor(x => Model.FormName, new {id = (string)null}));

            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
                                                                         
            
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
       Write(Html.HiddenFor(x => Model.RecordId, new {id = (string)null}));

            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
                                                                         
            
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
       Write(Html.HiddenFor(x => Model.PreviousClicked, new {id = (string)null}));

            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
                                                                                
            
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
       Write(Html.HiddenFor(x => Model.Theme, new {id = (string)null}));

            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
                                                                      

            
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
                                                   

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"FormStep\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1986), Tuple.Create("\"", 2009)
            
            #line 50 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
, Tuple.Create(Tuple.Create("", 1994), Tuple.Create<System.Object, System.Int32>(Model.FormStep
            
            #line default
            #line hidden
, 1994), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"RecordState\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2066), Tuple.Create("\"", 2092)
            
            #line 51 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
, Tuple.Create(Tuple.Create("", 2074), Tuple.Create<System.Object, System.Int32>(Model.RecordState
            
            #line default
            #line hidden
, 2074), false)
);

WriteLiteral(" />\r\n");

            
            #line 52 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
            
            
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
                                      
            
            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
       Write(Html.Partial(formThemedView));

            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
                                         
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        ");

WriteLiteral("\r\n");

            
            #line 59 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
        
            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
         if (Model.RenderScriptFiles)
        {
            
            
            #line default
            #line hidden
            
            #line 61 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
                                                                                                       
            Html.RenderPartial(formScriptView);
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 65 "..\..\Views\Partials\Forms\Themes\stoolball\Render.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
