#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/Forms/Themes/stoolball/Submitted.cshtml")]
    public partial class _Views_Partials_Forms_Themes_stoolball_Submitted_cshtml : System.Web.Mvc.WebViewPage<Umbraco.Forms.Web.Models.FormViewModel>
    {
        public _Views_Partials_Forms_Themes_stoolball_Submitted_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<p");

WriteLiteral(" class=\"umbraco-forms-submitmessage\"");

WriteLiteral(">");

            
            #line 3 "..\..\Views\Partials\Forms\Themes\stoolball\Submitted.cshtml"
                                  Write(Model.MessageOnSubmit);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n");

            
            #line 5 "..\..\Views\Partials\Forms\Themes\stoolball\Submitted.cshtml"
Write(Html.Partial("Forms/Themes/default/ScrollToFormScript"));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
