#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    
    #line 2 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
    using Umbraco.Forms.Mvc;
    
    #line default
    #line hidden
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/Forms/Themes/stoolball/Fieldtypes/FieldType.Email.cshtml")]
    public partial class _Views_Partials_Forms_Themes_stoolball_Fieldtypes_FieldType_Email_cshtml : System.Web.Mvc.WebViewPage<Umbraco.Forms.Mvc.Models.FieldViewModel>
    {
        public _Views_Partials_Forms_Themes_stoolball_Fieldtypes_FieldType_Email_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<input");

WriteLiteral(" type=\"email\"");

WriteAttribute("name", Tuple.Create(" \n       name=\"", 91), Tuple.Create("\"", 117)
            
            #line 4 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
, Tuple.Create(Tuple.Create("", 106), Tuple.Create<System.Object, System.Int32>(Model.Name
            
            #line default
            #line hidden
, 106), false)
);

WriteAttribute("id", Tuple.Create(" \n       id=\"", 118), Tuple.Create("\"", 140)
            
            #line 5 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
, Tuple.Create(Tuple.Create("", 131), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 131), false)
);

WriteAttribute("class", Tuple.Create(" \n       class=\"", 141), Tuple.Create("\"", 241)
            
            #line 6 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
, Tuple.Create(Tuple.Create("", 157), Tuple.Create<System.Object, System.Int32>(Html.GetFormFieldClass(Model.FieldTypeName)
            
            #line default
            #line hidden
, 157), false)
, Tuple.Create(Tuple.Create(" ", 201), Tuple.Create("umbraco-forms-field__email", 202), true)
, Tuple.Create(Tuple.Create(" ", 228), Tuple.Create("form-control", 229), true)
);

WriteAttribute("value", Tuple.Create(" \n       value=\"", 242), Tuple.Create("\"", 282)
            
            #line 7 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
, Tuple.Create(Tuple.Create("", 258), Tuple.Create<System.Object, System.Int32>(Model.ValueAsHtmlString
            
            #line default
            #line hidden
, 258), false)
);

WriteLiteral(" \n       ");

            
            #line 8 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
         if(string.IsNullOrEmpty(Model.PlaceholderText) == false){
            
            #line default
            #line hidden
WriteLiteral("placeholder=\"");

            
            #line 8 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
                                                                                Write(Model.PlaceholderText);

            
            #line default
            #line hidden
WriteLiteral("\"");

            
            #line 8 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
                                                                                                                   }
            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 9 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
       
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
         if(Model.Mandatory || Model.Validate){
            
            #line default
            #line hidden
WriteLiteral("data-val=\"true\"");

            
            #line 9 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
                                                                           }
            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 10 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
       
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
         if (Model.Mandatory) {
            
            #line default
            #line hidden
WriteLiteral(" data-val-required=\"");

            
            #line 10 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
                                                    Write(Model.RequiredErrorMessage);

            
            #line default
            #line hidden
WriteLiteral("\"");

            
            #line 10 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
                                                                                            }
            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 11 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
       
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
         if (Model.Validate) {
            
            #line default
            #line hidden
WriteLiteral(" data-val-regex=\"");

            
            #line 11 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
                                                Write(Model.InvalidErrorMessage);

            
            #line default
            #line hidden
WriteLiteral("\" data-regex=\"");

            
            #line 11 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
                                                                                        Write(Html.Raw(Model.Regex));

            
            #line default
            #line hidden
WriteLiteral("\"");

            
            #line 11 "..\..\Views\Partials\Forms\Themes\stoolball\Fieldtypes\FieldType.Email.cshtml"
                                                                                                                           }
            
            #line default
            #line hidden
WriteLiteral("\n/>\n\n");

        }
    }
}
#pragma warning restore 1591
