#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 4 "..\..\Views\Partials\_BattingScorecard.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    
    #line 5 "..\..\Views\Partials\_BattingScorecard.cshtml"
    using Humanizer;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Partials\_BattingScorecard.cshtml"
    using Stoolball.Matches;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Partials\_BattingScorecard.cshtml"
    using Stoolball.Web.Matches;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/_BattingScorecard.cshtml")]
    public partial class _Views_Partials__BattingScorecard_cshtml : System.Web.Mvc.WebViewPage<MatchInnings>
    {
        public _Views_Partials__BattingScorecard_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Partials\_BattingScorecard.cshtml"
  
    // If no player innings, only show a minimal scorecard
    var minimalScorecard = !Model.PlayerInnings.Any();

    // If no total, wickets, or batters, don't show anything
    var nothingToDisplay = (minimalScorecard && !Model.Runs.HasValue && !Model.Wickets.HasValue);
    if (!nothingToDisplay)
    {

            
            #line default
            #line hidden
WriteLiteral("        <table");

WriteLiteral(" class=\"batting-scorecard table-hover table-as-cards table-as-cards-reset-sm\"");

WriteLiteral(">\r\n            <caption>");

            
            #line 15 "..\..\Views\Partials\_BattingScorecard.cshtml"
                Write(Model.BattingTeam.Team.TeamName);

            
            #line default
            #line hidden
WriteLiteral("\'s batting</caption>\r\n\r\n");

            
            #line 17 "..\..\Views\Partials\_BattingScorecard.cshtml"
            
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Partials\_BattingScorecard.cshtml"
             if (!minimalScorecard)
            {

            
            #line default
            #line hidden
WriteLiteral("                <thead>\r\n                    <tr><th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Batter</th><th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">How out</th><th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Bowler</th><th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"numeric\"");

WriteLiteral(">Runs</th><th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"numeric balls-faced-header\"");

WriteLiteral(">Balls</th></tr>\r\n                </thead>\r\n");

            
            #line 22 "..\..\Views\Partials\_BattingScorecard.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 23 "..\..\Views\Partials\_BattingScorecard.cshtml"
             if (Model.PlayerInnings.Count > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tbody>\r\n");

            
            #line 26 "..\..\Views\Partials\_BattingScorecard.cshtml"
                
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Partials\_BattingScorecard.cshtml"
                 foreach (var playerInnings in Model.PlayerInnings)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <th");

WriteLiteral(" class=\"player-name\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1199), Tuple.Create("\"", 1246)
            
            #line 29 "..\..\Views\Partials\_BattingScorecard.cshtml"
, Tuple.Create(Tuple.Create("", 1206), Tuple.Create<System.Object, System.Int32>(playerInnings.Batter.Player.PlayerRoute
            
            #line default
            #line hidden
, 1206), false)
);

WriteLiteral(">");

            
            #line 29 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                                                                              Write(playerInnings.Batter.PlayerIdentityName);

            
            #line default
            #line hidden
WriteLiteral("</a></th>\r\n                        <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">How out</span>\r\n");

            
            #line 32 "..\..\Views\Partials\_BattingScorecard.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Partials\_BattingScorecard.cshtml"
                             if (playerInnings.DismissalType == DismissalType.NotOut)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <strong>");

            
            #line 34 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                    Write(playerInnings.DismissalType?.Humanize(LetterCasing.LowerCase));

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n");

            
            #line 35 "..\..\Views\Partials\_BattingScorecard.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div>\r\n                                    ");

WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 40 "..\..\Views\Partials\_BattingScorecard.cshtml"
                            Write(playerInnings.DismissalType?.Humanize(LetterCasing.LowerCase).Replace("run out", "run-out") ?? "not known");

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 41 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                 if ((playerInnings.DismissalType == DismissalType.Caught || playerInnings.DismissalType == DismissalType.RunOut) && playerInnings.DismissedBy != null)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <span");

WriteLiteral(" class=\"player-name dismissed-by\"");

WriteLiteral(">(<a");

WriteAttribute("href", Tuple.Create(" href=\"", 2398), Tuple.Create("\"", 2450)
            
            #line 43 "..\..\Views\Partials\_BattingScorecard.cshtml"
     , Tuple.Create(Tuple.Create("", 2405), Tuple.Create<System.Object, System.Int32>(playerInnings.DismissedBy.Player.PlayerRoute
            
            #line default
            #line hidden
, 2405), false)
);

WriteLiteral(">");

            
            #line 43 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                                                                                                               Write(playerInnings.DismissedBy.PlayerIdentityName);

            
            #line default
            #line hidden
WriteLiteral("</a>)</span>\r\n");

            
            #line 44 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </div>\r\n");

            
            #line 46 "..\..\Views\Partials\_BattingScorecard.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        </td>\r\n");

            
            #line 48 "..\..\Views\Partials\_BattingScorecard.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 48 "..\..\Views\Partials\_BattingScorecard.cshtml"
                         if (playerInnings.Bowler != null)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <td");

WriteLiteral(" class=\"player-name\"");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Bowler</span><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2871), Tuple.Create("\"", 2918)
            
            #line 50 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                                                       , Tuple.Create(Tuple.Create("", 2878), Tuple.Create<System.Object, System.Int32>(playerInnings.Bowler.Player.PlayerRoute
            
            #line default
            #line hidden
, 2878), false)
);

WriteLiteral(">");

            
            #line 50 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                                                                                                                                                                            Write(playerInnings.Bowler.PlayerIdentityName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n");

            
            #line 51 "..\..\Views\Partials\_BattingScorecard.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <td");

WriteLiteral(" class=\"player-name d-none d-sm-table-cell\"");

WriteLiteral("></td>\r\n");

            
            #line 55 "..\..\Views\Partials\_BattingScorecard.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 56 "..\..\Views\Partials\_BattingScorecard.cshtml"
                         if (playerInnings.RunsScored.HasValue)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <td");

WriteLiteral(" class=\"numeric-sm runs\"");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Runs</span>");

            
            #line 58 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                                                                                                                           Write(playerInnings.RunsScored);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 59 "..\..\Views\Partials\_BattingScorecard.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <td");

WriteLiteral(" class=\"numeric-sm runs d-none d-sm-table-cell\"");

WriteLiteral("></td>\r\n");

            
            #line 63 "..\..\Views\Partials\_BattingScorecard.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 64 "..\..\Views\Partials\_BattingScorecard.cshtml"
                         if (playerInnings.BallsFaced.HasValue)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <td");

WriteLiteral(" class=\"numeric-sm\"");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Balls</span>\r\n                                <span");

WriteLiteral(" class=\"balls-faced\"");

WriteLiteral(">");

            
            #line 68 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                                     Write(playerInnings.BallsFaced);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                            </td>\r\n");

            
            #line 70 "..\..\Views\Partials\_BattingScorecard.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <td");

WriteLiteral(" class=\"numeric d-none d-sm-table-cell\"");

WriteLiteral("></td>\r\n");

            
            #line 74 "..\..\Views\Partials\_BattingScorecard.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tr>\r\n");

            
            #line 76 "..\..\Views\Partials\_BattingScorecard.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n");

            
            #line 78 "..\..\Views\Partials\_BattingScorecard.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <tbody>\r\n");

            
            #line 80 "..\..\Views\Partials\_BattingScorecard.cshtml"
                
            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\Partials\_BattingScorecard.cshtml"
                  
                    if (Model.Byes.HasValue || !minimalScorecard)
                    {
                        
            
            #line default
            #line hidden
            
            #line 83 "..\..\Views\Partials\_BattingScorecard.cshtml"
                   Write(Html.Partial("_BattingScorecardExtrasRow", new ExtrasRowViewModel { RowLabel = "Byes", CssClass = "scorecard__extras", RowValue = Model.Byes?.ToString(CultureInfo.CurrentCulture), IsMinimalScorecard = minimalScorecard }));

            
            #line default
            #line hidden
            
            #line 83 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                                                                                                                                                                                                                                     ;
                    }
                    if (Model.Wides.HasValue || !minimalScorecard)
                    {
                        
            
            #line default
            #line hidden
            
            #line 87 "..\..\Views\Partials\_BattingScorecard.cshtml"
                   Write(Html.Partial("_BattingScorecardExtrasRow", new ExtrasRowViewModel { RowLabel = "Wides", CssClass = "scorecard__extras", RowValue = Model.Wides?.ToString(CultureInfo.CurrentCulture), IsMinimalScorecard = minimalScorecard }));

            
            #line default
            #line hidden
            
            #line 87 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                                                                                                                                                                                                                                       ;
                    }
                    if (Model.NoBalls.HasValue || !minimalScorecard)
                    {
                        
            
            #line default
            #line hidden
            
            #line 91 "..\..\Views\Partials\_BattingScorecard.cshtml"
                   Write(Html.Partial("_BattingScorecardExtrasRow", new ExtrasRowViewModel { RowLabel = "No balls", CssClass = "scorecard__extras", RowValue = Model.NoBalls?.ToString(CultureInfo.CurrentCulture), IsMinimalScorecard = minimalScorecard }));

            
            #line default
            #line hidden
            
            #line 91 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                                                                                                                                                                                                                                            ;
                    }
                    // don't show a 0 here, only if actual runs awarded or taken away
                    if (Model.BonusOrPenaltyRuns.HasValue && Model.BonusOrPenaltyRuns < 0)
                    {
                        
            
            #line default
            #line hidden
            
            #line 96 "..\..\Views\Partials\_BattingScorecard.cshtml"
                   Write(Html.Partial("_BattingScorecardExtrasRow", new ExtrasRowViewModel { RowLabel = "Penalty runs", CssClass = "scorecard__extras", RowValue = Model.BonusOrPenaltyRuns.Value.ToString(CultureInfo.CurrentCulture), IsMinimalScorecard = minimalScorecard }));

            
            #line default
            #line hidden
            
            #line 96 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                                                                                                                                                                                                                                                                ;
                    }
                    else if (Model.BonusOrPenaltyRuns.HasValue && Model.BonusOrPenaltyRuns > 0)
                    {
                        
            
            #line default
            #line hidden
            
            #line 100 "..\..\Views\Partials\_BattingScorecard.cshtml"
                   Write(Html.Partial("_BattingScorecardExtrasRow", new ExtrasRowViewModel { RowLabel = "Bonus runs", CssClass = "scorecard__extras", RowValue = Model.BonusOrPenaltyRuns.Value.ToString(CultureInfo.CurrentCulture), IsMinimalScorecard = minimalScorecard }));

            
            #line default
            #line hidden
            
            #line 100 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                                                                                                                                                                                                                                                              ;
                    }
                    
            
            #line default
            #line hidden
            
            #line 102 "..\..\Views\Partials\_BattingScorecard.cshtml"
               Write(Html.Partial("_BattingScorecardExtrasRow", new ExtrasRowViewModel { RowLabel = "Total", CssClass = "scorecard__totals" + (Model.Runs.HasValue ? string.Empty : " d-none d-sm-table-row"), RowValue = Model.Runs?.ToString(CultureInfo.CurrentCulture), IsMinimalScorecard = minimalScorecard }));

            
            #line default
            #line hidden
            
            #line 102 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                                                                                                                                                                                                                                                                                                    ;
                    
            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\Partials\_BattingScorecard.cshtml"
               Write(Html.Partial("_BattingScorecardExtrasRow", new ExtrasRowViewModel { RowLabel = "Wickets", CssClass = "scorecard__totals" + (Model.Wickets.HasValue ? string.Empty : " d-none d-sm-table-row"), RowValue = (Model.Wickets == -1) ? "all out" : Model.Wickets?.ToString(CultureInfo.CurrentCulture), IsMinimalScorecard = minimalScorecard }));

            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\Partials\_BattingScorecard.cshtml"
                                                                                                                                                                                                                                                                                                                                                                ;
                
            
            #line default
            #line hidden
WriteLiteral("\r\n            </tbody>\r\n        </table>\r\n");

            
            #line 107 "..\..\Views\Partials\_BattingScorecard.cshtml"
    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
