#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    
    #line 4 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
    using Stoolball.Teams;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
    using Stoolball.Web.HtmlHelpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
    using Stoolball.Web.Matches;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/_CreateOrEditFriendlyMatch.cshtml")]
    public partial class _Views_Partials__CreateOrEditFriendlyMatch_cshtml : System.Web.Mvc.WebViewPage<EditFriendlyMatchViewModel>
    {
        public _Views_Partials__CreateOrEditFriendlyMatch_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
 if (Model.Season != null)
{
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.HiddenFor(m => Model.Match.Season.SeasonId));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
                                                     
}
else if (Model.PossibleSeasons.Count > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
   Write(Html.LabelFor(m => Model.Match.Season.SeasonId, RequiredFieldStatus.Optional, new { @class = "has-form-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 16 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
   Write(Html.DropDownListFor(m => Model.Match.Season.SeasonId, Model.PossibleSeasons, "None", new { @class = "form-control", aria_describedby = "match-season" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
   Write(Html.ValidationMessageFor(m => Model.Match.Season.SeasonId, null, new { id = "match-season" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 19 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group related-item\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 23 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
   Write(Html.LabelFor(m => Model.Match.Season.SeasonId, RequiredFieldStatus.Optional, new { @class = "has-form-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 24 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
        
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
         if (Model.Match.Season != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"single-related-item__selected\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"related-item__selected__section\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 28 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
               Write(Html.TextBoxFor(m => Model.SeasonFullName, new { @class = "form-control", @readonly = "readonly" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"related-item__delete related-item__selected__section\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 31 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
               Write(Html.HiddenFor(m => Model.Match.Season.SeasonId, new { @class = "related-item__data related-item__id" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-delete-icon\"");

WriteLiteral(">");

            
            #line 32 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
                                                             Write(Html.Partial("_DeleteIcon", $"Remove this match from {Model.SeasonFullName}"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                </div>\r\n            </div>\r\n");

            
            #line 35 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
            Model.SeasonFullName = string.Empty;
            
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
       Write(Html.TextBoxFor(m => Model.SeasonFullName, new
            {
                @class = "form-control related-item__search",
                placeholder = "Type the season name",
                autocomplete = "off",
                type = "search",
                data_url = "/api/seasons/autocomplete?matchType=FriendlyMatch",
                data_template = "season-template",
                aria_label = "Type a season name and press down arrow to select from the matching choices",
                disabled = "disabled"
            }));

            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
              
        }
        else
        {
            
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
       Write(Html.TextBoxFor(m => Model.SeasonFullName, new
            {
                @class = "form-control related-item__search",
                placeholder = "Type the season name",
                autocomplete = "off",
                type = "search",
                data_url = "/api/seasons/autocomplete?matchType=FriendlyMatch",
                data_template = "season-template",
                aria_label = "Type a season name and press down arrow to select from the matching choices"
            }));

            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
              
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

WriteLiteral("    <script");

WriteLiteral(" type=\"text/x-template\"");

WriteLiteral(" id=\"season-template\"");

WriteLiteral(@">
        <div class=""single-related-item__selected"">
            <div class=""related-item__selected__section"">
                <input type=""text"" readonly=""readonly"" value=""{{value}}"" class=""form-control"" id=""SeasonFullName"" name=""SeasonFullName"" />
            </div>
            <div class=""related-item__delete related-item__selected__section"">
                <input name=""Match.Season.SeasonId"" class=""related-item__data related-item__id"" type=""hidden"" value=""{{data}}"" />
                <button type=""button"" class=""btn-delete-icon"">");

            
            #line 69 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
                                                         Write(Html.Partial("_DeleteIcon", "Remove this match from {{value}}"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            </div>\r\n        </div>\r\n    </script>\r\n");

            
            #line 73 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 76 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.LabelFor(m => Model.MatchDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 77 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.TextBox(nameof(Model.MatchDate), Model.MatchDate.HasValue ? Model.MatchDate.Value.LocalDateTime.ToString("yyyy-MM-dd") : string.Empty, new { @type = "date", @class = "form-control", required = "required", aria_describedby = "match-date", data_val_date= "Enter a date in YYYY-MM-DD format." }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 78 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.ValidationMessageFor(m => Model.MatchDate, null, new { id = "match-date" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 82 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.LabelFor(m => Model.StartTime, RequiredFieldStatus.Optional, new { @class = "has-form-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 83 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.TextBoxFor(m => Model.StartTime, "{0:HH:mm}", new { @type = "time", @class = "form-control", aria_describedby = "start-time" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 84 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.ValidationMessageFor(m => Model.StartTime, null, new { id = "start-time" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"form-group related-item\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 88 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.LabelFor(m => Model.HomeTeamId, RequiredFieldStatus.Optional, new { @class = "has-form-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <p");

WriteLiteral(" class=\"form-text\"");

WriteLiteral(" id=\"home-team-or\"");

WriteLiteral("><small>If you\'re still arranging the match you can fill in one team and leave th" +
"e other blank.</small></p>\r\n");

            
            #line 90 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
    
            
            #line default
            #line hidden
            
            #line 90 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
     if (Model.HomeTeamId.HasValue)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"single-related-item__selected\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"related-item__selected__section\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 94 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
           Write(Html.TextBoxFor(m => Model.HomeTeamName, new { @class = "form-control", @readonly = "readonly", aria_describedby = "home-team-or home-team" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"related-item__delete related-item__selected__section\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 97 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
           Write(Html.HiddenFor(m => Model.HomeTeamId, new { @class = "related-item__data related-item__id" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <button");

WriteLiteral(" class=\"btn-delete-icon\"");

WriteLiteral(">");

            
            #line 98 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
                                           Write(Html.Partial("_DeleteIcon", $"Remove {Model.HomeTeamName} from this match"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            </div>\r\n        </div>\r\n");

            
            #line 101 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
        Model.HomeTeamName = string.Empty;
        
            
            #line default
            #line hidden
            
            #line 102 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
   Write(Html.TextBoxFor(m => Model.HomeTeamName, new
        {
            @class = "form-control related-item__search",
            placeholder = "Type the home team name",
            autocomplete = "off",
            type = "search",
            data_url = $"/api/teams/autocomplete?teamType={TeamType.LimitedMembership.ToString()}&teamType={TeamType.Occasional.ToString()}&teamType={TeamType.Regular.ToString()}&teamType={TeamType.Representative.ToString()}&teamType={TeamType.SchoolAgeGroup.ToString()}&teamType={TeamType.SchoolClub.ToString()}&teamType={TeamType.SchoolOther.ToString()}",
            data_template = "home-team-template",
            aria_label = "Type a team name and press down arrow to select from the matching choices",
            disabled = "disabled"
        }));

            
            #line default
            #line hidden
            
            #line 112 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
          
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 116 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
   Write(Html.TextBoxFor(m => Model.HomeTeamName, new
        {
            @class = "form-control related-item__search",
            placeholder = "Type the home team name",
            autocomplete = "off",
            type = "search",
            data_url = $"/api/teams/autocomplete?teamType={TeamType.LimitedMembership.ToString()}&teamType={TeamType.Occasional.ToString()}&teamType={TeamType.Regular.ToString()}&teamType={TeamType.Representative.ToString()}&teamType={TeamType.SchoolAgeGroup.ToString()}&teamType={TeamType.SchoolClub.ToString()}&teamType={TeamType.SchoolOther.ToString()}",
            data_template = "home-team-template",
            aria_label = "Type a team name and press down arrow to select from the matching choices"
        }));

            
            #line default
            #line hidden
            
            #line 125 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
          
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 127 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.ValidationMessageFor(m => Model.HomeTeamId, null, new { id = "home-team" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<script");

WriteLiteral(" type=\"text/x-template\"");

WriteLiteral(" id=\"home-team-template\"");

WriteLiteral(@">
    <div class=""single-related-item__selected"">
        <div class=""related-item__selected__section"">
            <input type=""text"" readonly=""readonly"" value=""{{value}}"" class=""form-control"" id=""HomeTeamName"" name=""HomeTeamName"" aria-describedby=""home-team-or home-team"" />
        </div>
        <div class=""related-item__delete related-item__selected__section"">
            <input name=""HomeTeamId"" class=""related-item__data related-item__id"" type=""hidden"" value=""{{data}}"" />
            <button class=""btn-delete-icon"">");

            
            #line 136 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
                                       Write(Html.Partial("_DeleteIcon", "Remove {{value}} from this match"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n        </div>\r\n    </div>\r\n</script>\r\n\r\n<div");

WriteLiteral(" class=\"form-group related-item\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 142 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.LabelFor(m => Model.AwayTeamId, RequiredFieldStatus.Optional, new { @class = "has-form-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <p");

WriteLiteral(" class=\"form-text\"");

WriteLiteral(" id=\"away-team-or\"");

WriteLiteral("><small>If you\'re still arranging the match you can fill in one team and leave th" +
"e other blank.</small></p>\r\n");

            
            #line 144 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
    
            
            #line default
            #line hidden
            
            #line 144 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
     if (Model.AwayTeamId.HasValue)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"single-related-item__selected\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"related-item__selected__section\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 148 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
           Write(Html.TextBoxFor(m => Model.AwayTeamName, new { @class = "form-control", @readonly = "readonly", aria_describedby = "away-team-or" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"related-item__delete related-item__selected__section\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 151 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
           Write(Html.HiddenFor(m => Model.AwayTeamId, new { @class = "related-item__data related-item__id" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <button");

WriteLiteral(" class=\"btn-delete-icon\"");

WriteLiteral(">");

            
            #line 152 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
                                           Write(Html.Partial("_DeleteIcon", $"Remove {Model.AwayTeamName} from this match"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            </div>\r\n        </div>\r\n");

            
            #line 155 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
        Model.AwayTeamName = string.Empty;
        
            
            #line default
            #line hidden
            
            #line 156 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
   Write(Html.TextBoxFor(m => Model.AwayTeamName, new
        {
            @class = "form-control related-item__search",
            placeholder = "Type the away team name",
            autocomplete = "off",
            type = "search",
            data_url = $"/api/teams/autocomplete?teamType={TeamType.LimitedMembership.ToString()}&teamType={TeamType.Occasional.ToString()}&teamType={TeamType.Regular.ToString()}&teamType={TeamType.Representative.ToString()}&teamType={TeamType.SchoolAgeGroup.ToString()}&teamType={TeamType.SchoolClub.ToString()}&teamType={TeamType.SchoolOther.ToString()}",
            data_template = "away-team-template",
            aria_label = "Type a team name and press down arrow to select from the matching choices",
            disabled = "disabled"
        }));

            
            #line default
            #line hidden
            
            #line 166 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
          
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 170 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
   Write(Html.TextBoxFor(m => Model.AwayTeamName, new
        {
            @class = "form-control related-item__search",
            placeholder = "Type the away team name",
            autocomplete = "off",
            type = "search",
            data_url = $"/api/teams/autocomplete?teamType={TeamType.LimitedMembership.ToString()}&teamType={TeamType.Occasional.ToString()}&teamType={TeamType.Regular.ToString()}&teamType={TeamType.Representative.ToString()}&teamType={TeamType.SchoolAgeGroup.ToString()}&teamType={TeamType.SchoolClub.ToString()}&teamType={TeamType.SchoolOther.ToString()}",
            data_template = "away-team-template",
            aria_label = "Type a team name and press down arrow to select from the matching choices"
        }));

            
            #line default
            #line hidden
            
            #line 179 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
          
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 181 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.ValidationMessageFor(m => Model.AwayTeamId, null, new { id = "away-team" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<script");

WriteLiteral(" type=\"text/x-template\"");

WriteLiteral(" id=\"away-team-template\"");

WriteLiteral(@">
    <div class=""single-related-item__selected"">
        <div class=""related-item__selected__section"">
            <input type=""text"" readonly=""readonly"" value=""{{value}}"" class=""form-control"" id=""AwayTeamName"" name=""AwayTeamName"" aria-describedby=""away-team-or away-team"" />
        </div>
        <div class=""related-item__delete related-item__selected__section"">
            <input name=""AwayTeamId"" class=""related-item__data related-item__id"" type=""hidden"" value=""{{data}}"" />
            <button class=""btn-delete-icon"">");

            
            #line 190 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
                                       Write(Html.Partial("_DeleteIcon", "Remove {{value}} from this match"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n        </div>\r\n    </div>\r\n</script>\r\n\r\n<div");

WriteLiteral(" class=\"form-group related-item\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 196 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.LabelFor(m => Model.MatchLocationName, RequiredFieldStatus.Optional, new { @class = "has-form-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 197 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
    
            
            #line default
            #line hidden
            
            #line 197 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
     if (Model.MatchLocationId.HasValue)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"single-related-item__selected\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"related-item__selected__section\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 201 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
           Write(Html.TextBoxFor(m => Model.MatchLocationName, new { @class = "form-control", @readonly = "readonly" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"related-item__delete related-item__selected__section\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 204 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
           Write(Html.HiddenFor(m => Model.MatchLocationId, new { @class = "related-item__data related-item__id" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <button");

WriteLiteral(" class=\"btn-delete-icon\"");

WriteLiteral(">");

            
            #line 205 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
                                           Write(Html.Partial("_DeleteIcon", $"Remove {Model.MatchLocationName} from this match"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            </div>\r\n        </div>\r\n");

            
            #line 208 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
        Model.MatchLocationName = string.Empty;
        
            
            #line default
            #line hidden
            
            #line 209 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
   Write(Html.TextBoxFor(m => Model.MatchLocationName, new
        {
            @class = "form-control related-item__search",
            placeholder = "Type the ground or sports centre name",
            autocomplete = "off",
            type = "search",
            data_url = "/api/locations/autocomplete",
            data_template = "location-template",
            aria_label = "Type a ground or sports centre name add and press down arrow to select from the matching choices",
            disabled = "disabled"
        }));

            
            #line default
            #line hidden
            
            #line 219 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
          
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 223 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
   Write(Html.TextBoxFor(m => Model.MatchLocationName, new
        {
            @class = "form-control related-item__search",
            placeholder = "Type the ground or sports centre name",
            autocomplete = "off",
            type = "search",
            data_url = "/api/locations/autocomplete",
            data_template = "location-template",
            aria_label = "Type a ground or sports centre name add and press down arrow to select from the matching choices"
        }));

            
            #line default
            #line hidden
            
            #line 232 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
          
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<script");

WriteLiteral(" type=\"text/x-template\"");

WriteLiteral(" id=\"location-template\"");

WriteLiteral(@">
    <div class=""single-related-item__selected"">
        <div class=""related-item__selected__section"">
            <input type=""text"" readonly=""readonly"" value=""{{value}}"" class=""form-control"" id=""MatchLocationName"" name=""MatchLocationName"" />
        </div>
        <div class=""related-item__delete related-item__selected__section"">
            <input name=""MatchLocationId"" class=""related-item__data related-item__id"" type=""hidden"" value=""{{data}}"" />
            <button class=""btn-delete-icon"">");

            
            #line 242 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
                                       Write(Html.Partial("_DeleteIcon", "Remove {{value}} from this match"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n        </div>\r\n    </div>\r\n</script>\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 248 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.LabelFor(m => Model.Match.MatchNotes, RequiredFieldStatus.Optional, new { @class = "has-form-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 249 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.TextAreaFor(m => Model.Match.MatchNotes, new { @class = "form-control", aria_describedby = "notes-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 250 "..\..\Views\Partials\_CreateOrEditFriendlyMatch.cshtml"
Write(Html.ValidationMessageFor(m => Model.Match.MatchNotes, null, new { id = "notes-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
