#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    
    #line 2 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
    using Stoolball.MatchLocations;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
    using Stoolball.Web.HtmlHelpers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
    using Stoolball.Web.MatchLocations;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/_CreateOrEditMatchLocation.cshtml")]
    public partial class _Views_Partials__CreateOrEditMatchLocation_cshtml : System.Web.Mvc.WebViewPage<MatchLocationViewModel>
    {
        public _Views_Partials__CreateOrEditMatchLocation_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.LabelFor(m => Model.MatchLocation.PrimaryAddressableObjectName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.TextBoxFor(m => Model.MatchLocation.PrimaryAddressableObjectName, new { @class = "form-control", aria_describedby = "paon-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.ValidationMessageFor(m => Model.MatchLocation.PrimaryAddressableObjectName, null, new { id = "paon-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 14 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.LabelFor(m => Model.MatchLocation.SecondaryAddressableObjectName));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <p");

WriteLiteral(" class=\"form-text\"");

WriteLiteral(" id=\"saon-help\"");

WriteLiteral("><small>Only if there\'s more than one. For example, \'Pitch 1\' or \'Hall 2\'.</small" +
"></p>\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.TextBoxFor(m => Model.MatchLocation.SecondaryAddressableObjectName, new { @class = "form-control", aria_describedby = "saon-validation saon-help" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 17 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.ValidationMessageFor(m => Model.MatchLocation.SecondaryAddressableObjectName, null, new { id = "saon-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.LabelFor(m => Model.MatchLocation.StreetDescription, RequiredFieldStatus.Optional, new { @class = "has-form-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 22 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.TextBoxFor(m => Model.MatchLocation.StreetDescription, new { @class = "form-control", aria_describedby = "street-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 23 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.ValidationMessageFor(m => Model.MatchLocation.StreetDescription, null, new { id = "street-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 27 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.LabelFor(m => Model.MatchLocation.Locality, RequiredFieldStatus.Optional, new { @class = "has-form-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 28 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.TextBoxFor(m => Model.MatchLocation.Locality, new { @class = "form-control", aria_describedby = "locality-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 29 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.ValidationMessageFor(m => Model.MatchLocation.Locality, null, new { id = "locality-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 33 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.LabelFor(m => Model.MatchLocation.Town));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 34 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.TextBoxFor(m => Model.MatchLocation.Town, new { @class = "form-control", aria_describedby = "town-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 35 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.ValidationMessageFor(m => Model.MatchLocation.Town, null, new { id = "town-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 39 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.LabelFor(m => Model.MatchLocation.AdministrativeArea, RequiredFieldStatus.Optional, new { @class = "has-form-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.TextBoxFor(m => Model.MatchLocation.AdministrativeArea, new { @class = "form-control", aria_describedby = "area-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 41 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.ValidationMessageFor(m => Model.MatchLocation.AdministrativeArea, null, new { id = "area-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 45 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.LabelFor(m => Model.MatchLocation.Postcode, RequiredFieldStatus.Optional, new { @class = "has-form-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 46 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.TextBoxFor(m => Model.MatchLocation.Postcode, new { @class = "form-control postcode", aria_describedby = "postcode-validation", maxlength="9" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 47 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.ValidationMessageFor(m => Model.MatchLocation.Postcode, null, new { id = "postcode-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"map\"");

WriteLiteral(" data-apikey=\"");

            
            #line 50 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
                      Write(Model.GoogleMapsApiKey);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    <p");

WriteLiteral(" class=\"alert-danger alert\"");

WriteLiteral("><strong>You can set the location of this ground or sports centre using Google Ma" +
"ps, \r\n        but we can only show you the map if you <a");

WriteLiteral(" href=\"/privacy/cookies/\"");

WriteLiteral(">consent to maps</a>.</strong></p>\r\n</div>\r\n\r\n<fieldset");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" id=\"geoprecision\"");

WriteLiteral(">\r\n    <legend>How accurate is the map?</legend>\r\n    <div");

WriteLiteral(" class=\"custom-control custom-radio\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 58 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
   Write(Html.RadioButtonFor(m => Model.MatchLocation.GeoPrecision, GeoPrecision.Exact, new { @class = "custom-control-input", @id = "geo-0", aria_describedby = "precision-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <label");

WriteLiteral(" for=\"geo-0\"");

WriteLiteral(" class=\"custom-control-label\"");

WriteLiteral(">It shows exactly where the ground or sports centre is</label>\r\n    </div>\r\n    <" +
"div");

WriteLiteral(" class=\"custom-control custom-radio\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 62 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
   Write(Html.RadioButtonFor(m => Model.MatchLocation.GeoPrecision, GeoPrecision.Postcode, new { @class = "custom-control-input", @id = "geo-1", aria_describedby = "precision-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <label");

WriteLiteral(" for=\"geo-1\"");

WriteLiteral(" class=\"custom-control-label\"");

WriteLiteral(">It\'s the right postcode, and the ground or sports centre is nearby</label>\r\n    " +
"</div>\r\n    <div");

WriteLiteral(" class=\"custom-control custom-radio\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 66 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
   Write(Html.RadioButtonFor(m => Model.MatchLocation.GeoPrecision, GeoPrecision.Street, new { @class = "custom-control-input", @id = "geo-2", aria_describedby = "precision-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <label");

WriteLiteral(" for=\"geo-2\"");

WriteLiteral(" class=\"custom-control-label\"");

WriteLiteral(">The ground or sports centre is somewhere on this road</label>\r\n    </div>\r\n    <" +
"div");

WriteLiteral(" class=\"custom-control custom-radio\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 70 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
   Write(Html.RadioButtonFor(m => Model.MatchLocation.GeoPrecision, GeoPrecision.Town, new { @class = "custom-control-input", @id = "geo-3", aria_describedby = "precision-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <label");

WriteLiteral(" for=\"geo-3\"");

WriteLiteral(" class=\"custom-control-label\"");

WriteLiteral(">It shows the right town or village, but I don\'t know where the ground or sports " +
"centre is</label>\r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 73 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.ValidationMessageFor(m => Model.MatchLocation.GeoPrecision, null, new { id = "precision-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 74 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.HiddenFor(m => Model.MatchLocation.Latitude));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 75 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.HiddenFor(m => Model.MatchLocation.Longitude));

            
            #line default
            #line hidden
WriteLiteral("\r\n</fieldset>\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 79 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.LabelFor(m => Model.MatchLocation.MatchLocationNotes, RequiredFieldStatus.Optional, new { @class = "has-form-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <p");

WriteLiteral(" class=\"form-text\"");

WriteLiteral(" id=\"notes-help\"");

WriteLiteral("><small>Is it easy to find? Is there parking? Disabled facilities? Toilets?</smal" +
"l></p>\r\n");

WriteLiteral("    ");

            
            #line 81 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.TextAreaFor(m => Model.MatchLocation.MatchLocationNotes, new { @class = "form-control", aria_describedby = "notes-validation notes-help" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 82 "..\..\Views\Partials\_CreateOrEditMatchLocation.cshtml"
Write(Html.ValidationMessageFor(m => Model.MatchLocation.MatchLocationNotes, null, new { id = "notes-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<button");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Save ground or sports centre</button>");

        }
    }
}
#pragma warning restore 1591
