#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 4 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    
    #line 3 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
    using Humanizer;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
    using Stoolball.Web.Matches;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/_EditBowlingScorecard.cshtml")]
    public partial class _Views_Partials__EditBowlingScorecard_cshtml : System.Web.Mvc.WebViewPage<EditScorecardViewModel>
    {
        public _Views_Partials__EditBowlingScorecard_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
Write(Html.ValidationSummary(false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<table");

WriteLiteral(" class=\"table-as-cards bowling-scorecard-editor\"");

WriteLiteral(" data-autofocus=\"");

            
            #line 7 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
                                                                  Write(Model.Autofocus.ToString().ToLowerInvariant());

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    <caption>");

            
            #line 8 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
        Write(Model.CurrentInnings.MatchInnings.BowlingTeam.Team.TeamName);

            
            #line default
            #line hidden
WriteLiteral("\'s bowling, <span");

WriteLiteral(" class=\"text-nowrap\"");

WriteLiteral(">over-by-over</span></caption>\r\n    <thead>\r\n        <tr>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"bowling-scorecard-editor__header\"");

WriteLiteral(">Bowler</th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"bowling-scorecard-editor__header\"");

WriteLiteral(">Balls bowled <small");

WriteLiteral(" class=\"text-nowrap\"");

WriteLiteral(">(excluding extras)</small></th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"bowling-scorecard-editor__header\"");

WriteLiteral(">Wides</th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"bowling-scorecard-editor__header\"");

WriteLiteral(">No balls</th>\r\n            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"bowling-scorecard-editor__header\"");

WriteLiteral(">Over total</th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 19 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
        
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
         for (var i = 0; i < (Model.CurrentInnings.MatchInnings.OversBowled.Count); i++)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral(" class=\"bowling-scorecard-editor__field bowling-scorecard-editor__bowler\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 23 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
               Write(Html.LabelFor(m => Model.CurrentInnings.OversBowledSearch[i].Bowler, $"{(i + 1).Ordinalize(CultureInfo.CurrentCulture)} bowler", new { @class = "table-as-cards__label bowling-scorecard-editor__bowler-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 24 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
               Write(Html.TextBoxFor(m => Model.CurrentInnings.OversBowledSearch[i].Bowler, new { autocomplete = "off", data_lpignore = "true", @class = "scorecard__player-name", data_team = Model.CurrentInnings.MatchInnings.BowlingTeam.Team.TeamId.ToString() }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral(" class=\"bowling-scorecard-editor__field bowling-scorecard-editor__balls\"");

WriteLiteral(">\r\n                    <label");

WriteAttribute("for", Tuple.Create(" for=\"", 1858), Tuple.Create("\"", 1914)
, Tuple.Create(Tuple.Create("", 1864), Tuple.Create("CurrentInnings_OversBowledSearch_", 1864), true)
            
            #line 27 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
, Tuple.Create(Tuple.Create("", 1897), Tuple.Create<System.Object, System.Int32>(i
            
            #line default
            #line hidden
, 1897), false)
, Tuple.Create(Tuple.Create("", 1901), Tuple.Create("__BallsBowled", 1901), true)
);

WriteLiteral(" class=\"table-as-cards__label bowling-scorecard-editor__balls-label\"");

WriteLiteral(">Balls bowled <small");

WriteLiteral(" class=\"text-nowrap\"");

WriteLiteral(">(excluding extras)</small></label>\r\n                    <span>");

            
            #line 28 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
                     Write(Html.TextBoxFor(m => Model.CurrentInnings.OversBowledSearch[i].BallsBowled, new { autocomplete = "off", type = "number", min = "1", max = "12", @class = "scorecard__balls" }));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </td>\r\n                <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral(" class=\"bowling-scorecard-editor__field bowling-scorecard-editor__wides\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 31 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
               Write(Html.LabelFor(m => Model.CurrentInnings.OversBowledSearch[i].Wides, new { @class = "table-as-cards__label bowling-scorecard-editor__wides-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 32 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
               Write(Html.TextBoxFor(m => Model.CurrentInnings.OversBowledSearch[i].Wides, new { autocomplete = "off", type = "number", min = "0", @class = "scorecard__wides" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral(" class=\"bowling-scorecard-editor__field bowling-scorecard-editor__no-balls\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
               Write(Html.LabelFor(m => Model.CurrentInnings.OversBowledSearch[i].NoBalls, new { @class = "table-as-cards__label bowling-scorecard-editor__no-balls-label text-nowrap" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 36 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
               Write(Html.TextBoxFor(m => Model.CurrentInnings.OversBowledSearch[i].NoBalls, new { autocomplete = "off", type = "number", min = "0", @class = "scorecard__no-balls" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral(" class=\"bowling-scorecard-editor__field bowling-scorecard-editor__runs\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 39 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
               Write(Html.LabelFor(m => Model.CurrentInnings.OversBowledSearch[i].RunsConceded, new { @class = "table-as-cards__label bowling-scorecard-editor__runs-label text-nowrap" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 40 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
               Write(Html.TextBoxFor(m => Model.CurrentInnings.OversBowledSearch[i].RunsConceded, new { autocomplete = "off", type = "number", min = "0", @class = "scorecard__runs" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n");

            
            #line 43 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n<script");

WriteLiteral(" type=\"text/x-template\"");

WriteLiteral(" id=\"over-template\"");

WriteLiteral(@">
    <table>
        <tr>
            <th scope=""row"" data-stackable=""true"" class=""bowling-scorecard-editor__field bowling-scorecard-editor__bowler"">
                <label class=""table-as-cards__label bowling-scorecard-editor__bowler-label"" for=""CurrentInnings_OversBowledSearch_[0]__Bowler"">[0th] bowler</label>
                <input autocomplete=""off"" data-lpignore=""true"" class=""scorecard__player-name"" data-team=""");

            
            #line 51 "..\..\Views\Partials\_EditBowlingScorecard.cshtml"
                                                                                                    Write(Model.CurrentInnings.MatchInnings.BowlingTeam.Team.TeamId.ToString());

            
            #line default
            #line hidden
WriteLiteral("\" name=\"CurrentInnings.OversBowledSearch[0].Bowler\" id=\"CurrentInnings_OversBowle" +
"dSearch_[0]__Bowler\" type=\"text\" value=\"\" />\r\n            </th>\r\n            <td" +
" data-stackable=\"true\" class=\"bowling-scorecard-editor__field bowling-scorecard-" +
"editor__balls\">\r\n                <label for=\"CurrentInnings_OversBowledSearch_[0" +
"]__BallsBowled\" class=\"table-as-cards__label bowling-scorecard-editor__balls-lab" +
"el\">Balls bowled <small class=\"text-nowrap\">(excluding extras)</small></label>\r\n" +
"                <span><input autocomplete=\"off\" class=\"scorecard__balls\" min=\"1\"" +
" max=\"12\" name=\"CurrentInnings.OversBowledSearch[0].BallsBowled\" id=\"CurrentInni" +
"ngs_OversBowledSearch_[0]__BallsBowled\" type=\"number\" value=\"\" /></span>\r\n      " +
"      </td>\r\n            <td data-stackable=\"true\" class=\"bowling-scorecard-edit" +
"or__field bowling-scorecard-editor__wides\">\r\n                <label class=\"table" +
"-as-cards__label bowling-scorecard-editor__wides-label\" for=\"CurrentInnings_Over" +
"sBowledSearch_[0]__Wides\">Wides</label>\r\n                <input autocomplete=\"of" +
"f\" class=\"scorecard__wides\" min=\"0\" name=\"CurrentInnings.OversBowledSearch[0].Wi" +
"des\" id=\"CurrentInnings_OversBowledSearch_[0]__Wides\" type=\"number\" value=\"\" />\r" +
"\n            </td>\r\n            <td data-stackable=\"true\" class=\"bowling-scoreca" +
"rd-editor__field bowling-scorecard-editor__no-balls\">\r\n                <label cl" +
"ass=\"table-as-cards__label bowling-scorecard-editor__no-balls-label text-nowrap\"" +
" for=\"CurrentInnings_OversBowledSearch_[0]__NoBalls\">No balls</label>\r\n         " +
"       <input autocomplete=\"off\" class=\"scorecard__no-balls\" min=\"0\" name=\"Curre" +
"ntInnings.OversBowledSearch[0].NoBalls\" id=\"CurrentInnings_OversBowledSearch_[0]" +
"__NoBalls\" type=\"number\" value=\"\" />\r\n            </td>\r\n            <td data-st" +
"ackable=\"true\" class=\"bowling-scorecard-editor__field bowling-scorecard-editor__" +
"runs\">\r\n                <label class=\"table-as-cards__label bowling-scorecard-ed" +
"itor__runs-label text-nowrap\" for=\"CurrentInnings_OversBowledSearch_[0]__RunsCon" +
"ceded\">Over total</label>\r\n                <input autocomplete=\"off\" class=\"scor" +
"ecard__runs\" min=\"0\" name=\"CurrentInnings.OversBowledSearch[0].RunsConceded\" id=" +
"\"CurrentInnings_OversBowledSearch_[0]__RunsConceded\" type=\"number\" value=\"\" />\r\n" +
"            </td>\r\n        </tr>\r\n    </table>\r\n</script>\r\n\r\n<p");

WriteLiteral(" class=\"bowling-scorecard__full-name-tip d-none alert alert-info alert-tip\"");

WriteLiteral(" role=\"alert\"");

WriteLiteral(">Full names, if you know them, are better for comparing players.</p>\r\n");

        }
    }
}
#pragma warning restore 1591
