#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 2 "..\..\Views\Partials\_Header.cshtml"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    
    #line 3 "..\..\Views\Partials\_Header.cshtml"
    using Stoolball.Web.Account;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/_Header.cshtml")]
    public partial class _Views_Partials__Header_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<Stoolball.Web.Metadata.IHasViewMetadata>
    {
        
        #line 9 "..\..\Views\Partials\_Header.cshtml"
            
    private bool IsCurrentPage(string requestedPath, string sectionPath)
    {
        return Regex.IsMatch(requestedPath, $"^{sectionPath.Replace("/", @"\/")}?$");
    }

    private bool IsCurrentSection(string requestedPath, string sectionPath, List<string> rootUrlsForPlaySection)
    {
        if (requestedPath.Length <= 1) { return false; }
        var requestedSection = requestedPath.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries)[0].ToUpperInvariant();
        sectionPath = sectionPath.ToUpperInvariant();
        if (sectionPath == "/PLAY/")
        {
            return rootUrlsForPlaySection.Contains(requestedSection);
        }
        else
        {
            return requestedSection == sectionPath.Replace("/", string.Empty);
        }
    }

        #line default
        #line hidden
        
        public _Views_Partials__Header_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Partials\_Header.cshtml"
   
    var headerPhoto = Model.HeaderPhotoWithInheritance();
    var rootUrlsForPlaySection = new List<string>(6) { "PLAY", "TEAMS", "COMPETITIONS", "MATCHES", "TOURNAMENTS", "LOCATIONS" };
    string currentSection = null, currentPage = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("<header");

WriteLiteral(" class=\"header\"");

WriteLiteral(">\r\n    <nav");

WriteLiteral(" class=\"header__bar\"");

WriteLiteral(" aria-label=\"Stoolball England\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"header__inner\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"header__logo\"");

WriteLiteral(">\r\n");

            
            #line 35 "..\..\Views\Partials\_Header.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Partials\_Header.cshtml"
                     if (Request.RawUrl == "/")
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"header__logo-inner\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 1557), Tuple.Create("\"", 1599)
, Tuple.Create(Tuple.Create("", 1563), Tuple.Create<System.Object, System.Int32>(Href("~/images/logos/stoolball-england.svg")
, 1563), false)
);

WriteLiteral(" alt=\"Stoolball England\"");

WriteLiteral(" /></div>\r\n");

            
            #line 38 "..\..\Views\Partials\_Header.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteLiteral(" href=\"/\"");

WriteLiteral(" class=\"header__logo-inner print__no-url\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 1788), Tuple.Create("\"", 1830)
, Tuple.Create(Tuple.Create("", 1794), Tuple.Create<System.Object, System.Int32>(Href("~/images/logos/stoolball-england.svg")
, 1794), false)
);

WriteLiteral(" alt=\"Stoolball England\"");

WriteLiteral(" /></a>\r\n");

            
            #line 42 "..\..\Views\Partials\_Header.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n                <div");

WriteLiteral(" class=\"header__menu-large\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" role=\"menubar\"");

WriteLiteral(" aria-label=\"Stoolball England\"");

WriteLiteral(">\r\n");

            
            #line 46 "..\..\Views\Partials\_Header.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Partials\_Header.cshtml"
                          
                            var childrenOfHome = Umbraco.Content(Guid.Parse("7ea74fe5-4982-4bcf-bb8a-8e213c32f91c"))
                            .Children()
                            .Where(x => x.IsVisible());
                            foreach (var child in childrenOfHome)
                            {
                                var childUrl = child.Url();

            
            #line default
            #line hidden
WriteLiteral("                                <li");

WriteLiteral(" role=\"none\"");

WriteLiteral(">\r\n");

            
            #line 54 "..\..\Views\Partials\_Header.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\Partials\_Header.cshtml"
                                     if (currentPage == null && currentSection == null && IsCurrentPage(Request.RawUrl, childUrl))
                                    {
                                        currentPage = childUrl;

            
            #line default
            #line hidden
WriteLiteral("                                        <em");

WriteLiteral(" role=\"menuitem\"");

WriteLiteral(" aria-selected=\"true\"");

WriteLiteral(">");

            
            #line 57 "..\..\Views\Partials\_Header.cshtml"
                                                                            Write(child.Name);

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n");

            
            #line 58 "..\..\Views\Partials\_Header.cshtml"
                                    }
                                    else if (currentPage == null && currentSection == null && IsCurrentSection(Request.RawUrl, childUrl, rootUrlsForPlaySection))
                                    {
                                        currentSection = childUrl;

            
            #line default
            #line hidden
WriteLiteral("                                        <a");

WriteLiteral(" role=\"menuitem\"");

WriteLiteral(" aria-selected=\"true\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3209), Tuple.Create("\"", 3225)
            
            #line 62 "..\..\Views\Partials\_Header.cshtml"
      , Tuple.Create(Tuple.Create("", 3216), Tuple.Create<System.Object, System.Int32>(childUrl
            
            #line default
            #line hidden
, 3216), false)
);

WriteLiteral(">");

            
            #line 62 "..\..\Views\Partials\_Header.cshtml"
                                                                                            Write(child.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 63 "..\..\Views\Partials\_Header.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <a");

WriteLiteral(" role=\"menuitem\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3422), Tuple.Create("\"", 3438)
            
            #line 66 "..\..\Views\Partials\_Header.cshtml"
, Tuple.Create(Tuple.Create("", 3429), Tuple.Create<System.Object, System.Int32>(childUrl
            
            #line default
            #line hidden
, 3429), false)
);

WriteLiteral(">");

            
            #line 66 "..\..\Views\Partials\_Header.cshtml"
                                                                       Write(child.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 67 "..\..\Views\Partials\_Header.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </li>\r\n");

            
            #line 69 "..\..\Views\Partials\_Header.cshtml"
                            }
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n                    </ul>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"header__account d-print-none\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"btn header__account__button\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"header__account__button\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" title=\"Account\"");

WriteLiteral(">\r\n");

            
            #line 76 "..\..\Views\Partials\_Header.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\Partials\_Header.cshtml"
                             if (User.Identity.IsAuthenticated)
                            {
                                var gravatar = new Gravatar(User.Identity.Name);

            
            #line default
            #line hidden
WriteLiteral("                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4157), Tuple.Create("\"", 4176)
            
            #line 79 "..\..\Views\Partials\_Header.cshtml"
, Tuple.Create(Tuple.Create("", 4163), Tuple.Create<System.Object, System.Int32>(gravatar.Url
            
            #line default
            #line hidden
, 4163), false)
);

WriteLiteral(" alt=\"Account\"");

WriteLiteral(" width=\"30\"");

WriteLiteral(" height=\"30\"");

WriteLiteral(" class=\"header__account__account-image\"");

WriteLiteral(" />\r\n");

            
            #line 80 "..\..\Views\Partials\_Header.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4390), Tuple.Create("\"", 4432)
, Tuple.Create(Tuple.Create("", 4396), Tuple.Create<System.Object, System.Int32>(Href("~/images/icons/person-white-24dp.svg")
, 4396), false)
);

WriteLiteral(" alt=\"Account\"");

WriteLiteral(" width=\"30\"");

WriteLiteral(" height=\"30\"");

WriteLiteral(" />\r\n");

            
            #line 84 "..\..\Views\Partials\_Header.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </button>\r\n                        <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-right\"");

WriteLiteral(" aria-labelledby=\"header__account__button\"");

WriteLiteral(">\r\n");

            
            #line 87 "..\..\Views\Partials\_Header.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 87 "..\..\Views\Partials\_Header.cshtml"
                             if (User.Identity.IsAuthenticated)
                            {
                                if (Request.RawUrl == "/account")
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral("><em");

WriteLiteral(" aria-selected=\"true\"");

WriteLiteral(">My account</em></li>\r\n");

            
            #line 92 "..\..\Views\Partials\_Header.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral("><a");

WriteLiteral(" href=\"/account\"");

WriteLiteral(">My account</a></li>\r\n");

            
            #line 96 "..\..\Views\Partials\_Header.cshtml"
                                }
                                if (Request.RawUrl.StartsWith("/account/sign-out"))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral("><em");

WriteLiteral(" aria-selected=\"true\"");

WriteLiteral(">Sign out</em></li>\r\n");

            
            #line 100 "..\..\Views\Partials\_Header.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral("><a");

WriteLiteral(" href=\"/account/sign-out\"");

WriteLiteral(">Sign out</a></li>\r\n");

            
            #line 104 "..\..\Views\Partials\_Header.cshtml"
                                }
                            }
                            else
                            {
                                if (Request.RawUrl.StartsWith("/account/create"))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral("><em");

WriteLiteral(" aria-selected=\"true\"");

WriteLiteral(">Create an account</em></li>\r\n");

            
            #line 111 "..\..\Views\Partials\_Header.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral("><a");

WriteLiteral(" href=\"/account/create\"");

WriteLiteral(">Create an account</a></li>\r\n");

            
            #line 115 "..\..\Views\Partials\_Header.cshtml"
                                }
                                if (Request.RawUrl.StartsWith("/account/sign-in"))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral("><em");

WriteLiteral(" aria-selected=\"true\"");

WriteLiteral(">Sign in</em></li>\r\n");

            
            #line 119 "..\..\Views\Partials\_Header.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6672), Tuple.Create("\"", 6754)
, Tuple.Create(Tuple.Create("", 6679), Tuple.Create("/account/sign-in?ReturnUrl=", 6679), true)
            
            #line 122 "..\..\Views\Partials\_Header.cshtml"
                  , Tuple.Create(Tuple.Create("", 6706), Tuple.Create<System.Object, System.Int32>(HttpUtility.UrlEncode(Request.Url.PathAndQuery)
            
            #line default
            #line hidden
, 6706), false)
);

WriteLiteral(">Sign in</a></li>\r\n");

            
            #line 123 "..\..\Views\Partials\_Header.cshtml"
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </div>\r\n                </div>" +
"\r\n                <div");

WriteLiteral(" class=\"header__menu-small\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"btn header__menu-small__button\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"header__menu-small__button\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" title=\"Menu\"");

WriteLiteral(">\r\n                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 7247), Tuple.Create("\"", 7287)
, Tuple.Create(Tuple.Create("", 7253), Tuple.Create<System.Object, System.Int32>(Href("~/images/icons/menu-white-24dp.svg")
, 7253), false)
);

WriteLiteral(" alt=\"Menu\"");

WriteLiteral(" width=\"30\"");

WriteLiteral(" height=\"30\"");

WriteLiteral(" />\r\n                        </button>\r\n                        <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-right\"");

WriteLiteral(" aria-labelledby=\"header__menu-small__button\"");

WriteLiteral(">\r\n");

            
            #line 134 "..\..\Views\Partials\_Header.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 134 "..\..\Views\Partials\_Header.cshtml"
                              
                                foreach (var child in childrenOfHome)
                                {
                                    var childUrl = child.Url();
                                    if (currentPage == childUrl)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(">\r\n                                            <em");

WriteLiteral(" aria-selected=\"true\"");

WriteLiteral(">");

            
            #line 141 "..\..\Views\Partials\_Header.cshtml"
                                                                Write(child.Name);

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n                                        </li>\r\n");

            
            #line 143 "..\..\Views\Partials\_Header.cshtml"
                                    }
                                    else if (currentSection == childUrl)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(">\r\n                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 8255), Tuple.Create("\"", 8271)
            
            #line 147 "..\..\Views\Partials\_Header.cshtml"
, Tuple.Create(Tuple.Create("", 8262), Tuple.Create<System.Object, System.Int32>(childUrl
            
            #line default
            #line hidden
, 8262), false)
);

WriteLiteral(" aria-selected=\"true\"");

WriteLiteral(">");

            
            #line 147 "..\..\Views\Partials\_Header.cshtml"
                                                                                Write(child.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                        </li>\r\n");

            
            #line 149 "..\..\Views\Partials\_Header.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(">\r\n                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 8592), Tuple.Create("\"", 8608)
            
            #line 153 "..\..\Views\Partials\_Header.cshtml"
, Tuple.Create(Tuple.Create("", 8599), Tuple.Create<System.Object, System.Int32>(childUrl
            
            #line default
            #line hidden
, 8599), false)
);

WriteLiteral(">");

            
            #line 153 "..\..\Views\Partials\_Header.cshtml"
                                                           Write(child.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                        </li>\r\n");

            
            #line 155 "..\..\Views\Partials\_Header.cshtml"
                                    }
                                }
                            
            
            #line default
            #line hidden
WriteLiteral("\r\n                        </ul>\r\n                    </div>\r\n                </di" +
"v>\r\n            </div>\r\n        </div>\r\n    </nav>\r\n");

            
            #line 164 "..\..\Views\Partials\_Header.cshtml"
    
            
            #line default
            #line hidden
            
            #line 164 "..\..\Views\Partials\_Header.cshtml"
     if (headerPhoto != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <img");

WriteAttribute("srcset", Tuple.Create(" srcset=\"", 8960), Tuple.Create("\"", 9229)
            
            #line 166 "..\..\Views\Partials\_Header.cshtml"
, Tuple.Create(Tuple.Create("", 8969), Tuple.Create<System.Object, System.Int32>(headerPhoto.GetCropUrl("extra-small")
            
            #line default
            #line hidden
, 8969), false)
, Tuple.Create(Tuple.Create(" ", 9007), Tuple.Create("576w,", 9008), true)
            
            #line 167 "..\..\Views\Partials\_Header.cshtml"
, Tuple.Create(Tuple.Create("\r\n            ", 9013), Tuple.Create<System.Object, System.Int32>(headerPhoto.GetCropUrl("small")
            
            #line default
            #line hidden
, 9027), false)
, Tuple.Create(Tuple.Create(" ", 9059), Tuple.Create("768w,", 9060), true)
            
            #line 168 "..\..\Views\Partials\_Header.cshtml"
, Tuple.Create(Tuple.Create("\r\n            ", 9065), Tuple.Create<System.Object, System.Int32>(headerPhoto.GetCropUrl("medium")
            
            #line default
            #line hidden
, 9079), false)
, Tuple.Create(Tuple.Create(" ", 9112), Tuple.Create("992w,", 9113), true)
            
            #line 169 "..\..\Views\Partials\_Header.cshtml"
, Tuple.Create(Tuple.Create("\r\n            ", 9118), Tuple.Create<System.Object, System.Int32>(headerPhoto.GetCropUrl("large")
            
            #line default
            #line hidden
, 9132), false)
, Tuple.Create(Tuple.Create(" ", 9164), Tuple.Create("1200w,", 9165), true)
            
            #line 170 "..\..\Views\Partials\_Header.cshtml"
, Tuple.Create(Tuple.Create("\r\n            ", 9171), Tuple.Create<System.Object, System.Int32>(headerPhoto.GetCropUrl("extra-large")
            
            #line default
            #line hidden
, 9185), false)
, Tuple.Create(Tuple.Create(" ", 9223), Tuple.Create("2000w", 9224), true)
);

WriteLiteral("\r\n             sizes=\"100vw\"");

WriteAttribute("src", Tuple.Create(" src=\"", 9258), Tuple.Create("\"", 9296)
            
            #line 171 "..\..\Views\Partials\_Header.cshtml"
, Tuple.Create(Tuple.Create("", 9264), Tuple.Create<System.Object, System.Int32>(headerPhoto.GetCropUrl("large")
            
            #line default
            #line hidden
, 9264), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" class=\"header__photo\"");

WriteLiteral(" />\r\n");

            
            #line 172 "..\..\Views\Partials\_Header.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</header>\r\n");

        }
    }
}
#pragma warning restore 1591
