#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    
    #line 2 "..\..\Views\Partials\_MostCatches.cshtml"
    using Humanizer;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Partials\_MostCatches.cshtml"
    using Stoolball.Dates;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Partials\_MostCatches.cshtml"
    using Stoolball.Statistics;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Partials\_MostCatches.cshtml"
    using Stoolball.Web.Statistics;
    
    #line default
    #line hidden
    using Umbraco.Core;
    
    #line 6 "..\..\Views\Partials\_MostCatches.cshtml"
    using Umbraco.Core.Composing;
    
    #line default
    #line hidden
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/_MostCatches.cshtml")]
    public partial class _Views_Partials__MostCatches_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<StatisticsViewModel<BestStatistic>>
    {
        public _Views_Partials__MostCatches_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\Views\Partials\_MostCatches.cshtml"
  
    var dateTimeFormatter = Current.Factory.CreateInstance<DateTimeFormatter>();
    var serialiser = Current.Factory.GetInstance<IStatisticsFilterQueryStringSerializer>();
    var queryString = serialiser.Serialize(Model.AppliedFilter, Model.DefaultFilter);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Views\Partials\_MostCatches.cshtml"
 if (Model.Results.Any())
{

            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"statistics table-as-cards table-as-cards-reset-md\"");

WriteLiteral(">\r\n");

            
            #line 15 "..\..\Views\Partials\_MostCatches.cshtml"
        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Partials\_MostCatches.cshtml"
         if (Model.ShowCaption)
        {

            
            #line default
            #line hidden
WriteLiteral("            <caption>Most catches</caption>\r\n");

            
            #line 18 "..\..\Views\Partials\_MostCatches.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <thead>\r\n            <tr>\r\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"table-order\"");

WriteLiteral(">#</th>\r\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Player</th>\r\n");

            
            #line 23 "..\..\Views\Partials\_MostCatches.cshtml"
                
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Partials\_MostCatches.cshtml"
                 if (Model.ShowTeamsColumn)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Teams</th>\r\n");

            
            #line 26 "..\..\Views\Partials\_MostCatches.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"numeric statistic\"");

WriteLiteral(">Matches</th>\r\n                <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"numeric statistic\"");

WriteLiteral(">Catches</th>\r\n            </tr>\r\n        </thead>\r\n        <tbody>\r\n");

            
            #line 32 "..\..\Views\Partials\_MostCatches.cshtml"
            
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Partials\_MostCatches.cshtml"
              
                int? previousCatches = null;
                for (var i = 0; i < Model.Results.Count(); i++)
                {
                    var equalToPrevious = Model.Results[i].Result.Total == previousCatches;
                    previousCatches = Model.Results[i].Result.Total;

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td");

WriteLiteral(" class=\"table-as-cards__header-md\"");

WriteLiteral(">");

            
            #line 39 "..\..\Views\Partials\_MostCatches.cshtml"
                                                          Write(equalToPrevious ? "=" : ((Model.AppliedFilter.Paging.PageSize * (Model.AppliedFilter.Paging.PageNumber - 1)) + i + 1).ToString());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Player</span><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1808), Tuple.Create("\"", 1858)
            
            #line 40 "..\..\Views\Partials\_MostCatches.cshtml"
                                               , Tuple.Create(Tuple.Create("", 1815), Tuple.Create<System.Object, System.Int32>(Model.Results[i].Result.Player.PlayerRoute
            
            #line default
            #line hidden
, 1815), false)
);

WriteLiteral(">");

            
            #line 40 "..\..\Views\Partials\_MostCatches.cshtml"
                                                                                                                                                                        Write(Model.Results[i].Result.Player.PlayerName());

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n");

            
            #line 41 "..\..\Views\Partials\_MostCatches.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Partials\_MostCatches.cshtml"
                         if (Model.ShowTeamsColumn)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Teams</span><div>");

            
            #line 43 "..\..\Views\Partials\_MostCatches.cshtml"
                                                                                                                         Write(Model.Results[i].Result.Player.PlayerIdentities.Select(x => x.Team.TeamName).Humanize());

            
            #line default
            #line hidden
WriteLiteral("</div></td>\r\n");

            
            #line 44 "..\..\Views\Partials\_MostCatches.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral(" class=\"numeric-md\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Matches</span>");

            
            #line 45 "..\..\Views\Partials\_MostCatches.cshtml"
                                                                                                                                     Write(Model.Results[i].Result.TotalMatches);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral(" class=\"numeric-md\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Catches</span>");

            
            #line 46 "..\..\Views\Partials\_MostCatches.cshtml"
                                                                                                                                     Write(Model.Results[i].Result.Total);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n");

            
            #line 48 "..\..\Views\Partials\_MostCatches.cshtml"
                }
            
            
            #line default
            #line hidden
WriteLiteral("\r\n        </tbody>\r\n    </table>\r\n");

            
            #line 52 "..\..\Views\Partials\_MostCatches.cshtml"
    if (Model.AppliedFilter.MaxResultsAllowingExtraResultsIfValuesAreEqual.HasValue)
    {

            
            #line default
            #line hidden
WriteLiteral("        <p><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2807), Tuple.Create("\"", 2866)
            
            #line 54 "..\..\Views\Partials\_MostCatches.cshtml"
, Tuple.Create(Tuple.Create("", 2814), Tuple.Create<System.Object, System.Int32>(Request.Url.AbsolutePath
            
            #line default
            #line hidden
, 2814), false)
, Tuple.Create(Tuple.Create("", 2839), Tuple.Create("/most-catches", 2839), true)
            
            #line 54 "..\..\Views\Partials\_MostCatches.cshtml"
, Tuple.Create(Tuple.Create("", 2852), Tuple.Create<System.Object, System.Int32>(queryString
            
            #line default
            #line hidden
, 2852), false)
);

WriteLiteral(">Most catches – view all and filter</a></p>\r\n");

            
            #line 55 "..\..\Views\Partials\_MostCatches.cshtml"
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\Partials\_MostCatches.cshtml"
   Write(Html.Partial("_Paging", Model.AppliedFilter.Paging));

            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\Partials\_MostCatches.cshtml"
                                                            
    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
