#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/_StatisticsBasis.cshtml")]
    public partial class _Views_Partials__StatisticsBasis_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Partials__StatisticsBasis_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<p>The statistics below are based on scorecards added to this website. If you kno" +
"w someone who\'s played better, add the scorecard for that match – see <a");

WriteLiteral(" href=\"/organise/website/how-to-add-match-results/\"");

WriteLiteral(">How to add match results</a>.</p>");

        }
    }
}
#pragma warning restore 1591
