#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\ApproveMember.cshtml"
    using ContentModels = Umbraco.Web.PublishedModels;
    
    #line default
    #line hidden
    using Examine;
    
    #line 3 "..\..\Views\ApproveMember.cshtml"
    using Stoolball.Web.Email;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ApproveMember.cshtml")]
    public partial class _Views_ApproveMember_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ApproveMember>
    {
        public _Views_ApproveMember_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 5 "..\..\Views\ApproveMember.cshtml"
   Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");

            
            #line 7 "..\..\Views\ApproveMember.cshtml"
    
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\ApproveMember.cshtml"
     if (Model.ApprovalTokenValid)
    {
        
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\ApproveMember.cshtml"
   Write(Html.ProtectEmailAddresses(Model.ApprovalSuccessful.ToHtmlString().Replace("{{NAME}}", Model.MemberName)));

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\ApproveMember.cshtml"
                                                                                                                  
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\ApproveMember.cshtml"
   Write(Html.ProtectEmailAddresses(Model.ApprovalFailed));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\ApproveMember.cshtml"
                                                         
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
