#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\CreateClub.cshtml"
    using ClientDependency.Core.Mvc;
    
    #line default
    #line hidden
    using Examine;
    
    #line 4 "..\..\Views\CreateClub.cshtml"
    using Stoolball.Security;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\CreateClub.cshtml"
    using Stoolball.Web.Clubs;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CreateClub.cshtml")]
    public partial class _Views_CreateClub_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<ClubViewModel>
    {
        public _Views_CreateClub_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("head", () => {

WriteLiteral("\r\n    <meta");

WriteLiteral(" name=\"robots\"");

WriteLiteral(" content=\"noindex,follow\"");

WriteLiteral(" />\r\n");

});

            
            #line 8 "..\..\Views\CreateClub.cshtml"
  
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("~/scripts/jquery.validate.min.js");
    Html.RequiresJs("~/scripts/jquery.validate.unobtrusive.min.js");

    Html.RequiresJs("~/js/libs/jquery.autocomplete.min.js", 50);
    Html.RequiresCss("~/css/autocomplete.min.css");

    Html.RequiresCss("~/css/related-items.min.css");
    Html.RequiresJs("~/js/related-items.js");

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>Add a club</h1>\r\n\r\n");

            
            #line 23 "..\..\Views\CreateClub.cshtml"
    
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\CreateClub.cshtml"
     if (Model.IsAuthorized[AuthorizedAction.CreateClub])
    {
        using (Html.BeginUmbracoForm<CreateClubSurfaceController>
            ("CreateClub"))
        {
            
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\CreateClub.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\CreateClub.cshtml"
                                    

            
            #line default
            #line hidden
WriteLiteral("            <p");

WriteLiteral(" class=\"alert alert-info alert-tip\"");

WriteLiteral(">A club links teams together. Do you need to <a");

WriteLiteral(" href=\"/teams/add\"");

WriteLiteral(">add a team</a> instead?</p>\r\n");

            
            #line 30 "..\..\Views\CreateClub.cshtml"
            
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\CreateClub.cshtml"
       Write(Html.Partial("_CreateOrEditClub"));

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\CreateClub.cshtml"
                                              
        }
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\CreateClub.cshtml"
   Write(Html.Partial("_Login"));

            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\CreateClub.cshtml"
                               
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
