#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\EditMatchFormat.cshtml"
    using ClientDependency.Core.Mvc;
    
    #line default
    #line hidden
    using Examine;
    
    #line 5 "..\..\Views\EditMatchFormat.cshtml"
    using Stoolball.Security;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\EditMatchFormat.cshtml"
    using Stoolball.Web.HtmlHelpers;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\EditMatchFormat.cshtml"
    using Stoolball.Web.Matches;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EditMatchFormat.cshtml")]
    public partial class _Views_EditMatchFormat_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<EditMatchFormatViewModel>
    {
        public _Views_EditMatchFormat_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("head", () => {

WriteLiteral("\r\n    <meta");

WriteLiteral(" name=\"robots\"");

WriteLiteral(" content=\"noindex,follow\"");

WriteLiteral(" />\r\n");

});

            
            #line 9 "..\..\Views\EditMatchFormat.cshtml"
  
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("~/scripts/jquery.validate.min.js");
    Html.RequiresJs("~/scripts/jquery.validate.unobtrusive.min.js");

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>Edit ");

            
            #line 16 "..\..\Views\EditMatchFormat.cshtml"
        Write(Html.MatchFullName(Model.Match, x => Model.DateFormatter.FormatDate(x, false, false, false)));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");

            
            #line 18 "..\..\Views\EditMatchFormat.cshtml"
    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\EditMatchFormat.cshtml"
     if (Model.IsAuthorized[AuthorizedAction.EditMatch])
    {
        using (Html.BeginUmbracoForm<EditMatchFormatSurfaceController>("UpdateMatch"))
        {
            
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\EditMatchFormat.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\EditMatchFormat.cshtml"
                                    

            if (Model.Match.StartTime <= DateTimeOffset.UtcNow)
            {

            
            #line default
            #line hidden
WriteLiteral("                <p");

WriteLiteral(" class=\"alert alert-info alert-tip\"");

WriteLiteral(">You can add extra innings and overs but you cannot reduce them, because this mat" +
"ch has already happened.</p>\r\n");

            
            #line 27 "..\..\Views\EditMatchFormat.cshtml"
            }


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 30 "..\..\Views\EditMatchFormat.cshtml"
           Write(Html.LabelFor(m => Model.FormData.MatchInnings));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <p");

WriteLiteral(" class=\"form-text\"");

WriteLiteral(" id=\"innings-help\"");

WriteLiteral("><small>Most matches have 2 innings, one per team.</small></p>\r\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Views\EditMatchFormat.cshtml"
           Write(Html.TextBoxFor(m => Model.FormData.MatchInnings, new { @class = "form-control", aria_describedby = "innings-help innings-validation", @type = "number", min = (Model.Match.StartTime <= DateTimeOffset.UtcNow ? Model.FormData.MatchInnings : 2), step="2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 33 "..\..\Views\EditMatchFormat.cshtml"
           Write(Html.ValidationMessageFor(m => Model.FormData.MatchInnings, null, new { id = "innings-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 35 "..\..\Views\EditMatchFormat.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 37 "..\..\Views\EditMatchFormat.cshtml"
           Write(Html.LabelFor(m => Model.FormData.Overs, RequiredFieldStatus.Optional, new { @class = "has-form-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 38 "..\..\Views\EditMatchFormat.cshtml"
           Write(Html.TextBoxFor(m => Model.FormData.Overs, new { @class = "form-control", aria_describedby = "overs-validation", @type = "number", min = (Model.Match.StartTime <= DateTimeOffset.UtcNow ? Model.FormData.Overs : 1) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 39 "..\..\Views\EditMatchFormat.cshtml"
           Write(Html.ValidationMessageFor(m => Model.FormData.Overs, null, new { id = "overs-validation" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 41 "..\..\Views\EditMatchFormat.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Save match</button>\r\n");

            
            #line 43 "..\..\Views\EditMatchFormat.cshtml"
        }
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\EditMatchFormat.cshtml"
   Write(Html.Partial("_Login"));

            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\EditMatchFormat.cshtml"
                               
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
