#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\PlayerBowling.cshtml"
    using ClientDependency.Core.Mvc;
    
    #line default
    #line hidden
    using Examine;
    
    #line 5 "..\..\Views\PlayerBowling.cshtml"
    using Stoolball.Statistics;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\PlayerBowling.cshtml"
    using Stoolball.Web.Filtering;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\PlayerBowling.cshtml"
    using Stoolball.Web.Statistics;
    
    #line default
    #line hidden
    using Umbraco.Core;
    
    #line 3 "..\..\Views\PlayerBowling.cshtml"
    using Umbraco.Core.Composing;
    
    #line default
    #line hidden
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PlayerBowling.cshtml")]
    public partial class _Views_PlayerBowling_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<PlayerBowlingViewModel>
    {
        public _Views_PlayerBowling_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\Views\PlayerBowling.cshtml"
  
    Html.RequiresCss("/statistics/statistics.min.css");
    Html.RequiresJs("/js/filter.js");
    Html.RequiresCss("/css/filter.min.css");

    var bowlingFigures = new StatisticsViewModel<BowlingFigures>(Model, Services.UserService) 
    { 
        ShowCaption = true, 
        ShowPlayerColumn = false, 
        DefaultFilter = Model.DefaultFilter,
        AppliedFilter = Model.AppliedFilter 
    };
    bowlingFigures.Results.AddRange(Model.BowlingFigures);

    var serialiser = Current.Factory.GetInstance<IStatisticsFilterQueryStringSerializer>();
    var queryString = serialiser.Serialize(Model.AppliedFilter, Model.DefaultFilter);

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 25 "..\..\Views\PlayerBowling.cshtml"
Write(Html.Partial("_PlayerHeader"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"nav-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1048), Tuple.Create("\"", 1094)
            
            #line 29 "..\..\Views\PlayerBowling.cshtml"
, Tuple.Create(Tuple.Create("", 1055), Tuple.Create<System.Object, System.Int32>(Model.Player.PlayerRoute
            
            #line default
            #line hidden
, 1055), false)
            
            #line 29 "..\..\Views\PlayerBowling.cshtml"
, Tuple.Create(Tuple.Create("", 1080), Tuple.Create<System.Object, System.Int32>(queryString
            
            #line default
            #line hidden
, 1080), false)
);

WriteLiteral(">Batting</a>\r\n        </li>\r\n        <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(">\r\n            <em");

WriteLiteral(" class=\"nav-link active\"");

WriteLiteral(">Bowling</em>\r\n        </li>\r\n        <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"nav-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1286), Tuple.Create("\"", 1341)
            
            #line 35 "..\..\Views\PlayerBowling.cshtml"
, Tuple.Create(Tuple.Create("", 1293), Tuple.Create<System.Object, System.Int32>(Model.Player.PlayerRoute
            
            #line default
            #line hidden
, 1293), false)
, Tuple.Create(Tuple.Create("", 1318), Tuple.Create("/fielding", 1318), true)
            
            #line 35 "..\..\Views\PlayerBowling.cshtml"
, Tuple.Create(Tuple.Create("", 1327), Tuple.Create<System.Object, System.Int32>(queryString
            
            #line default
            #line hidden
, 1327), false)
);

WriteLiteral(">Fielding</a>\r\n        </li>\r\n        <li");

WriteLiteral(" class=\"nav-item nav-item-admin\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"nav-link nav-link-filter\"");

WriteLiteral(">Edit filter</button>\r\n        </li>\r\n    </ul>\r\n");

WriteLiteral("    ");

            
            #line 41 "..\..\Views\PlayerBowling.cshtml"
Write(Html.Partial("_Filters", new FilterViewModel
{
    FilteredItemTypeSingular = "Statistics",
    FilteredItemTypePlural = "Statistics",
    FilterDescription = Model.FilterDescription,
    from = Model.AppliedFilter.FromDate,
    to = Model.AppliedFilter.UntilDate
}));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 50 "..\..\Views\PlayerBowling.cshtml"
    
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\PlayerBowling.cshtml"
     if (Model.BowlingStatistics.TotalInnings == 0)
    {
        
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\PlayerBowling.cshtml"
   Write(Html.Partial("_NoData"));

            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\PlayerBowling.cshtml"
                                
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <table");

WriteLiteral(" class=\"table-as-cards table-as-cards-reset-md\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Innings</th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Overs</th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Maidens</th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Runs</th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Wickets</th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">5 wickets</th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Best</th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Economy</th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Average</th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"text-wrap\"");

WriteLiteral(">Strike rate</th>\r\n                </tr>\r\n            </thead>\r\n            <tbod" +
"y>\r\n                <tr>\r\n                    <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Innings</span>");

            
            #line 73 "..\..\Views\PlayerBowling.cshtml"
                                                                                                              Write(Model.BowlingStatistics.TotalInnings);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Overs</span>");

            
            #line 74 "..\..\Views\PlayerBowling.cshtml"
                                                                                                            Write(Math.Round(Model.BowlingStatistics.TotalOvers, 1));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Maidens</span>");

            
            #line 75 "..\..\Views\PlayerBowling.cshtml"
                                                                                                              Write(Model.BowlingStatistics.TotalMaidens);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Runs</span>");

            
            #line 76 "..\..\Views\PlayerBowling.cshtml"
                                                                                                           Write(Model.BowlingStatistics.TotalRunsConceded);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Wickets</span>");

            
            #line 77 "..\..\Views\PlayerBowling.cshtml"
                                                                                                              Write(Model.BowlingStatistics.TotalWickets);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">5 wickets</span>");

            
            #line 78 "..\..\Views\PlayerBowling.cshtml"
                                                                                                                Write(Model.BowlingStatistics.FiveWicketInnings);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Best</span>");

            
            #line 79 "..\..\Views\PlayerBowling.cshtml"
                                                                                                            Write(Model.BowlingStatistics.BestInningsWickets.HasValue ? Model.BowlingStatistics.BestInningsWickets + "/" + (Model.BowlingStatistics.BestInningsRunsConceded.HasValue ? Model.BowlingStatistics.BestInningsRunsConceded.Value.ToString() : "–") : "–");

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Economy</span>");

            
            #line 80 "..\..\Views\PlayerBowling.cshtml"
                                                                                                               Write(Model.BowlingStatistics.Economy.HasValue ? Math.Round(Model.BowlingStatistics.Economy.Value, 2).ToString() : "–");

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Average</span>");

            
            #line 81 "..\..\Views\PlayerBowling.cshtml"
                                                                                                               Write(Model.BowlingStatistics.Average.HasValue ? Math.Round(Model.BowlingStatistics.Average.Value, 2).ToString() : "–");

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" data-stackable=\"true\"");

WriteLiteral("><span");

WriteLiteral(" class=\"table-as-cards__label\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">Strike rate</span>");

            
            #line 82 "..\..\Views\PlayerBowling.cshtml"
                                                                                                                   Write(Model.BowlingStatistics.StrikeRate.HasValue ? Math.Round(Model.BowlingStatistics.StrikeRate.Value, 2).ToString() : "–");

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n            </tbody>\r\n        </table>\r\n");

            
            #line 86 "..\..\Views\PlayerBowling.cshtml"

        if ((Model.BowlingStatistics.TotalInnings != Model.BowlingStatistics.TotalInningsWithRunsConceded && Model.BowlingStatistics.Average.HasValue) ||
           (Model.BowlingStatistics.TotalInnings != Model.BowlingStatistics.TotalInningsWithRunsConceded && Model.BowlingStatistics.Economy.HasValue) ||
           (Model.BowlingStatistics.TotalInnings != Model.BowlingStatistics.TotalInningsWithBallsBowled && Model.BowlingStatistics.StrikeRate.HasValue))
        {

            
            #line default
            #line hidden
WriteLiteral("            <p");

WriteLiteral(" class=\"table-small-print\"");

WriteLiteral(">\r\n                <small>\r\n");

            
            #line 93 "..\..\Views\PlayerBowling.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 93 "..\..\Views\PlayerBowling.cshtml"
                     if (Model.BowlingStatistics.TotalInnings != Model.BowlingStatistics.TotalInningsWithRunsConceded)
                    {
                        if (Model.BowlingStatistics.Economy.HasValue && Model.BowlingStatistics.Average.HasValue &&
                            Model.BowlingStatistics.TotalInningsWithRunsConceded == Model.BowlingStatistics.TotalInningsWithBallsBowled && Model.BowlingStatistics.StrikeRate.HasValue)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral("Economy, average and strike rate are based on ");

            
            #line 98 "..\..\Views\PlayerBowling.cshtml"
                                                                        Write(Model.BowlingStatistics.TotalInningsWithRunsConceded);

            
            #line default
            #line hidden
WriteLiteral(" innings with overs, runs and wickets recorded.\r\n");

            
            #line 99 "..\..\Views\PlayerBowling.cshtml"
                        }
                        else if (Model.BowlingStatistics.Economy.HasValue && Model.BowlingStatistics.Average.HasValue)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral("Economy and average are based on ");

            
            #line 102 "..\..\Views\PlayerBowling.cshtml"
                                                           Write(Model.BowlingStatistics.TotalInningsWithRunsConceded);

            
            #line default
            #line hidden
WriteLiteral(" innings with overs, runs and wickets recorded.\r\n");

            
            #line 103 "..\..\Views\PlayerBowling.cshtml"
                        }
                        else if (Model.BowlingStatistics.Economy.HasValue)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral("Economy is based on ");

            
            #line 106 "..\..\Views\PlayerBowling.cshtml"
                                              Write(Model.BowlingStatistics.TotalInningsWithRunsConceded);

            
            #line default
            #line hidden
WriteLiteral(" innings with overs and runs recorded.\r\n");

            
            #line 107 "..\..\Views\PlayerBowling.cshtml"
                        }
                        else if (Model.BowlingStatistics.Average.HasValue)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral("The average is based on ");

            
            #line 110 "..\..\Views\PlayerBowling.cshtml"
                                                  Write(Model.BowlingStatistics.TotalInningsWithRunsConceded);

            
            #line default
            #line hidden
WriteLiteral(" innings with runs and wickets recorded.\r\n");

            
            #line 111 "..\..\Views\PlayerBowling.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 113 "..\..\Views\PlayerBowling.cshtml"
                     if (Model.BowlingStatistics.TotalInnings != Model.BowlingStatistics.TotalInningsWithBallsBowled && Model.BowlingStatistics.StrikeRate.HasValue &&
                        (!Model.BowlingStatistics.Economy.HasValue || !Model.BowlingStatistics.Average.HasValue || Model.BowlingStatistics.TotalInningsWithRunsConceded != Model.BowlingStatistics.TotalInningsWithBallsBowled))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("The strike rate is based on ");

            
            #line 116 "..\..\Views\PlayerBowling.cshtml"
                                                  Write(Model.BowlingStatistics.TotalInningsWithBallsBowled);

            
            #line default
            #line hidden
WriteLiteral(" innings with overs and wickets recorded.\r\n");

            
            #line 117 "..\..\Views\PlayerBowling.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </small>\r\n            </p>\r\n");

            
            #line 120 "..\..\Views\PlayerBowling.cshtml"

        }

        
            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\PlayerBowling.cshtml"
   Write(Html.Partial("_BowlingFigures", bowlingFigures));

            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\PlayerBowling.cshtml"
                                                        
    }

            
            #line default
            #line hidden
WriteLiteral("    </div>");

        }
    }
}
#pragma warning restore 1591
