#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    
    #line 3 "..\..\Views\SeasonActions.cshtml"
    using Stoolball.Security;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\SeasonActions.cshtml"
    using Stoolball.Web.Competitions;
    
    #line default
    #line hidden
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Core.Models.PublishedContent;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SeasonActions.cshtml")]
    public partial class _Views_SeasonActions_cshtml : Umbraco.Web.Mvc.UmbracoViewPage<SeasonViewModel>
    {
        public _Views_SeasonActions_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("head", () => {

WriteLiteral("\r\n    <meta");

WriteLiteral(" name=\"robots\"");

WriteLiteral(" content=\"noindex,follow\"");

WriteLiteral(" />\r\n");

});

WriteLiteral("<div");

WriteLiteral(" class=\"container-xl\"");

WriteLiteral(">\r\n    <h1>Edit ");

            
            #line 8 "..\..\Views\SeasonActions.cshtml"
        Write(Model.Season.SeasonFullName());

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");

            
            #line 10 "..\..\Views\SeasonActions.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\SeasonActions.cshtml"
     if (Model.IsAuthorized[AuthorizedAction.EditCompetition] || Model.IsAuthorized[AuthorizedAction.DeleteCompetition])
    {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Settings for ");

            
            #line 12 "..\..\Views\SeasonActions.cshtml"
                    Write(Model.Season.Competition.CompetitionName);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 13 "..\..\Views\SeasonActions.cshtml"
        var competitionModel = new CompetitionViewModel(Model, Services.UserService) { Competition = Model.Season.Competition };
        foreach (var permission in Model.IsAuthorized)
        {
            competitionModel.IsAuthorized.Add(permission.Key, permission.Value);
        }
        
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\SeasonActions.cshtml"
   Write(Html.Partial("_CompetitionActions", competitionModel));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\SeasonActions.cshtml"
                                                              


            
            #line default
            #line hidden
WriteLiteral("        <h2>Settings for the ");

            
            #line 20 "..\..\Views\SeasonActions.cshtml"
                        Write(Model.Season.SeasonName());

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 21 "..\..\Views\SeasonActions.cshtml"
        if (Model.IsAuthorized[AuthorizedAction.EditCompetition])
        {

            
            #line default
            #line hidden
WriteLiteral("            <dt><a");

WriteAttribute("href", Tuple.Create(" href=\"", 991), Tuple.Create("\"", 1035)
            
            #line 23 "..\..\Views\SeasonActions.cshtml"
, Tuple.Create(Tuple.Create("", 998), Tuple.Create<System.Object, System.Int32>(Model.Season.SeasonRoute
            
            #line default
            #line hidden
, 998), false)
, Tuple.Create(Tuple.Create("", 1023), Tuple.Create("/edit/season", 1023), true)
);

WriteLiteral(">Edit the ");

            
            #line 23 "..\..\Views\SeasonActions.cshtml"
                                                                    Write(Model.Season.SeasonName());

            
            #line default
            #line hidden
WriteLiteral("</a></dt>\r\n");

WriteLiteral("            <dd>Set the introduction, types of match played, players per team, ov" +
"ers per match and more.</dd>\r\n");

WriteLiteral("            <dt><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1212), Tuple.Create("\"", 1255)
            
            #line 25 "..\..\Views\SeasonActions.cshtml"
, Tuple.Create(Tuple.Create("", 1219), Tuple.Create<System.Object, System.Int32>(Model.Season.SeasonRoute
            
            #line default
            #line hidden
, 1219), false)
, Tuple.Create(Tuple.Create("", 1244), Tuple.Create("/edit/teams", 1244), true)
);

WriteLiteral(">Teams in the ");

            
            #line 25 "..\..\Views\SeasonActions.cshtml"
                                                                       Write(Model.Season.SeasonName());

            
            #line default
            #line hidden
WriteLiteral("</a></dt>\r\n");

WriteLiteral("            <dd>Set which teams are playing in the season.</dd>\r\n");

WriteLiteral("            <dt><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1390), Tuple.Create("\"", 1433)
            
            #line 27 "..\..\Views\SeasonActions.cshtml"
, Tuple.Create(Tuple.Create("", 1397), Tuple.Create<System.Object, System.Int32>(Model.Season.SeasonRoute
            
            #line default
            #line hidden
, 1397), false)
, Tuple.Create(Tuple.Create("", 1422), Tuple.Create("/edit/table", 1422), true)
);

WriteLiteral(">Edit results table for the ");

            
            #line 27 "..\..\Views\SeasonActions.cshtml"
                                                                                     Write(Model.Season.SeasonName());

            
            #line default
            #line hidden
WriteLiteral("</a></dt>\r\n");

WriteLiteral("            <dd>Set whether to show a results table and, for leagues, how points " +
"are calculated.</dd>\r\n");

            
            #line 29 "..\..\Views\SeasonActions.cshtml"
            if (Model.IsAuthorized[AuthorizedAction.DeleteCompetition])
            {

            
            #line default
            #line hidden
WriteLiteral("                <dt><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1712), Tuple.Create("\"", 1751)
            
            #line 31 "..\..\Views\SeasonActions.cshtml"
, Tuple.Create(Tuple.Create("", 1719), Tuple.Create<System.Object, System.Int32>(Model.Season.SeasonRoute
            
            #line default
            #line hidden
, 1719), false)
, Tuple.Create(Tuple.Create("", 1744), Tuple.Create("/delete", 1744), true)
);

WriteLiteral(">Delete the ");

            
            #line 31 "..\..\Views\SeasonActions.cshtml"
                                                                     Write(Model.Season.SeasonName());

            
            #line default
            #line hidden
WriteLiteral("</a> ");

            
            #line 31 "..\..\Views\SeasonActions.cshtml"
                                                                                                    Write(Html.Partial("_AdminOnly"));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n");

WriteLiteral("                <dd>Lose the results of this season. Remove it from the details o" +
"f matches and teams.</dd>\r\n");

            
            #line 33 "..\..\Views\SeasonActions.cshtml"
            }
        }
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\SeasonActions.cshtml"
   Write(Html.Partial("_Login"));

            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\SeasonActions.cshtml"
                               
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
