name: "Debug"

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Debug
      shell: pwsh
      run: |
         gci "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow"