name: "Debug"

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
    - name: Debug
      shell: pwsh
      run: |
        Write-Output $env:PATH
        gci $env:PATH